### ISSUE TITLE
FastCopy 4.0.0: Dest dir wrong from command line

### ISSUE THREAD

**Issue by HansS7** [FastCopyLab/FastCopy#10]
**Describe the bug**
I start FastCopy from a batch with this command line:

FastCopy.exe /cmd=update /bufsize=128 ^
  /speed=autoslow /no_exec ^
  /stream /reparse /linkdest /verify=FALSE /skip_empty_dir=FALSE ^
  /exclude="Thumbs.db;" ^
  "E:\\temp\\_WST-HS" /to="\\\\WST-094\\E$\\temp\\_WST-HS"

It worked as expected in v3.9.2, but in 4.0.0 DestDir is "\\\\WST-094\\E$\\temp\\_WST-HS\\" ("\\" wrongly appended). So all files are copied to wrong directory :-(.

**To Reproduce**
Always reproducible with command line like given above.

**Command line options and various settings**
See above.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.0.0
 - OS ver: Win10-64-pro 21H2

**Comment by FastCopyLab** [comment]
Thank you for your report.
We have released v4.0.1, which fixes this issue.
