### ISSUE TITLE
同期でディスクフルエラーでました

### ISSUE THREAD

**Issue by kyuningeng** [FastCopyLab/FastCopy#100]
同期で
☑コピー前に削除を実行
ならもうディスクフルエラーは出ないと思ったんですが、、
出ました！
まだ直っていないのでしょうか？？

さすがにコピー先ディスクの空き容量が58.3MBでは
無理なんですか？？

仕方ないのでコピー元ディスクで248GB位のファイルを
削除して●空き容量を259GBまで増やしたら、、
同期がいまく行きました。。
空き容量11.6GBでは動かなかったのに

どうしてでしょう？

Windows10 21H2 pro 64bit
FastCopy ver4.1.7

参考画像
[https://1drv.ms/u/s!An5FOcISHAY8l8F2P8uZaOcca4opgw?e=WmehPI](url)
[https://1drv.ms/u/s!An5FOcISHAY8l8F4Fm72qDgy4ZFdOQ?e=ctg2LT](url)
[https://1drv.ms/u/s!An5FOcISHAY8l8F5QTQlMsOlCBA5Ww?e=unG1HQ](url)
[https://1drv.ms/u/s!An5FOcISHAY8l8F6bxaNulTsTDvHTg?e=r9V3Hb](url)
[https://1drv.ms/u/s!An5FOcISHAY8l8F32wqLT7ts73Jfqg?e=cBzyB3](url)

**Comment by kyuningeng** [comment]
補足です

<Source>  D:　3TB HDD
　↓　同期（サイズ・日付）
<DestDir> H:　3TB HDD


ログファイルには特に変なところはありませんでした
まず6000位のファイルを一斉に削除して
その後14700番目位のファイルの追加でディスクフルで中断です（1回目のこと）

以下ログ参考です（4回実行しました）

●2回目が全く動かなかったのが、非常に不思議です！！
●1回目ですでに、6000位のファイルを削除しているので
●コピー先は空き容量が増えたはずです
●１年以上前の古い　☑コピー前に削除を実行　がない時（v3.92）でも
●確か、中断したあと2回目で同期完了していたと思います

-----------------------------------1回目
=================================================
FastCopy(ver4.1.7 (Admin)) start at 2022/07/07 15:15:36
<Source>  D:\
<DestDir> H:\
<Exclude> $Recycle.Bin\;System Volume Information\
<Command> 同期（サイズ・日付） (with Verify)
-------------------------------------------------
- H:\PT...\実行すること.txt   <20150922-112111 32>
- H:\PT...25エラー.txt   <20150125-130940 103>
　・
　・中略
　・
+ H:\...\bin\Log\   <20220502-075232>
+ H:\...エラー\   <20220329-183707>
SetEndOfFile(ディスクに十分な空き領域がありません。112) : H:\...\waifu2x-caffe.zip

TotalRead  = 881,805 MiB
TotalWrite = 881,803 MiB
TotalFiles = 144,539 (14,669)
TotalSkip  = 1,702,154 MiB
SkipFiles  = 421,314 (53,294)
TotalDel   = 486,020 MiB
DelFiles   = 5,811 (237)
TotalTime  = 02:16:27
TransRate  = 112.9 MB/s
FileRate   = 17.7 files/s
VerifyRead = 0.0 MiB
VerifyFiles= 0

Result : (ErrFiles : 2 / ErrDirs : 0) at 2022/07/07 17:40:19




1回目でエラーなのでおもむろに「実行」ボタンをしても
以下の通り、動きませんでした
-----------------------------------2回目
=================================================
FastCopy(ver4.1.7 (Admin)) start at 2022/07/07 17:41:17
<Source>  D:\
<DestDir> H:\
<Exclude> $Recycle.Bin\;System Volume Information\
<Command> 同期（サイズ・日付） (with Verify)
-------------------------------------------------

---- Estimating ... ----
PreTrans = 0.0 MiB
PreFiles = 0 (4,093)
PreTime  = 30.3 sec
PreRate  = 0.00 files/s

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/07/07 17:41:49




2回目で変化がなかったので、再度「実行」ボタンを押したところ
またディスクフルエラーです
-----------------------------------3回目
=================================================
FastCopy(ver4.1.7 (Admin)) start at 2022/07/07 17:42:25
<Source>  D:\
<DestDir> H:\
<Exclude> $Recycle.Bin\;System Volume Information\
<Command> 同期（サイズ・日付） (with Verify)
-------------------------------------------------
SetEndOfFile(ディスクに十分な空き領域がありません。112) : H:\...\waifu2x-caffe.zip

TotalRead  = 2.0 MiB
TotalWrite = 0.0 MiB
TotalFiles = 0 (0)
TotalSkip  = 2,583,958 MiB
SkipFiles  = 565,853 (70,638)
TotalTime  = 05:04
TransRate  = 0.00 MB/s
FileRate   = 0.00 files/s
VerifyRead = 0.0 MiB
VerifyFiles= 0

Result : (ErrFiles : 2 / ErrDirs : 0) at 2022/07/07 17:53:18





仕方ないのでコピー元ディスクで248GB位のファイルを
削除して●空き容量を259GBまで増やしたら、、
同期がいまく行きました。。4回目のこと
-----------------------------------4回目
=================================================
FastCopy(ver4.1.7 (Admin)) start at 2022/07/07 17:53:19
<Source>  D:\
<DestDir> H:\
<Exclude> $Recycle.Bin\;System Volume Information\
<Command> 同期（サイズ・日付） (with Verify)
-------------------------------------------------
- H:\...Time20191129091924   <20210701-085515 10> ←この削除連続で空き容量248GB位を増やした
- H:\...Time20200210021033   <20210701-085515 10> ←この削除連続で空き容量248GB位を増やした
　・
　・中略
　・
+ H:\...\waifu2x-caffe.zip   <20201006-145544 681,985,133 xxh3=bdf1cc514ad5656fa41d21b21165268b> ←追加できた●
+ H:\...スワード20200116.zip   <20201014-071255 877 xxh3=207579e193f13be4075d7327cde3e3bd>

TotalRead  = 2,067 MiB
TotalWrite = 2,067 MiB
TotalFiles = 188 (0)
TotalSkip  = 2,591,513 MiB
SkipFiles  = 675,067 (73,474)
TotalDel   = 253,605 MiB
DelFiles   = 5,371 (371)
TotalTime  = 01:36
TransRate  = 34.2 MB/s
FileRate   = 2.97 files/s
VerifyRead = 2,067 MiB
VerifyFiles= 188

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/07/07 17:54:56
-----------------------------------

![1](https://user-images.githubusercontent.com/108708213/177885330-1e9ebd49-83de-4082-9eaf-106d561cba75.jpg)


![2](https://user-images.githubusercontent.com/108708213/177885356-cb7824de-1bda-4070-8b5c-515470ea2b16.jpg)

![3](https://user-images.githubusercontent.com/108708213/177885380-b4280cb9-eec1-48fa-9bd5-7205d803faa0.jpg)

![4](https://user-images.githubusercontent.com/108708213/177885420-a14792d7-7190-4e1b-b604-56b6fb9575b4.jpg)


![5](https://user-images.githubusercontent.com/108708213/177885440-4e09ea00-094d-4cd4-858d-91180d6bb157.jpg)

**Comment by seeringly** [comment]
ふと思ったのですが、今回の現象はfastcopyの問題ではなく
うちのPCの（壊れた？OS）システムの問題かもしれません

いまはシステムを初期化（クリーンインストール）して、様子を見ています
また同期エラーが出れば、ご報告します
（ただし、ディスクの同期は数ヶ月に1回しかしませんが）

既にロジックを見直しているとは思いますが、、もし万一何かわかればお願いします。。。。

-----------------------------再テスト結果
念のために、コピー元ディスクの空き容量を9GBくらいにするために
コピー元ディスクに240GBのダミーデータを作成し再度同期をしたところ
コピー元ディスクに２つのあり得ない？新しいファイルができていました

D:\DumpStack.log.tmp　←本来ないファイル BSODにはなっていない
D:\pagefile.sys　←本来ないファイル　無論ページファイルをコピー元ディスク（D:）
　　　　　　　　　に作る設定はしていない

もしも、この２ファイルが初めから存在していたなら、1回目の同期で既にエラーが出たはず！

4回目までにはなかった２ファイルが、5回目にいきなり現れたということです
▼奇妙です

=================================================5回目
FastCopy(ver4.1.7 (Admin)) start at 2022/07/09 07:06:40
<Source>  D:\
<DestDir> H:\
<Exclude> $Recycle.Bin\;System Volume Information\
<Command> 同期（サイズ・日付） (with Verify)
-------------------------------------------------
OpenFile(プロセスはファイルにアクセスできません。別のプロセスが使用中です。32) : D:\DumpStack.log.tmp　←4回目までなかったファイル
OpenFile(プロセスはファイルにアクセスできません。別のプロセスが使用中です。32) : D:\pagefile.sys　←4回目までなかったファイル
+ H:\test1\   <20220709-070253>
+ H:\test1\testfile.dat   <20220709-070253 257,698,037,760 xxh3=c5eed3e6e09a4a3d395e4ac87318d6ab>　←正しい240GBダミーファイル

TotalRead  = 245,760 MiB
TotalWrite = 245,760 MiB
TotalFiles = 1 (1)
TotalSkip  = 2,593,581 MiB
SkipFiles  = 675,255 (73,209)
TotalTime  = 01:05:46
TransRate  = 71.1 MB/s
FileRate   = 0.00 files/s
VerifyRead = 245,760 MiB
VerifyFiles= 1

Result : (ErrFiles : 2 / ErrDirs : 0) at 2022/07/09 08:12:26

![Dドライブを指定していないのにDドライブにページファイルができていた](https://user-images.githubusercontent.com/108869061/178124647-ebcc0608-9f5e-41cc-b7b0-154ee463e661.jpg)
