### ISSUE TITLE
説明文の変更は？

### ISSUE THREAD

**Issue by seeringly** [FastCopyLab/FastCopy#101]
fastcopyを起動した画面内の
■DestDir指定の末尾に \ があるかどうかで、挙動が変化します。
■（詳しくはヘルプをご参照下さい）

を以下の様に変えることはできますか？
毎回悩むのをもうやめたいです！

---------------------------------------------
DestDir指定の末尾に \ があるかどうかで、挙動が変化します。

１）DestDir指定の末尾に \ があると、子フォルダが作成されます。
Source  C:\test1\
DestDir C:\test2\　←●

結果　C:\test2\test1\　子フォルダ（test1\）が作成されます

２）子フォルダ（test1\）を作成したくない場合は、
DestDir指定の末尾の \ を取り除いて下さい。

Source  C:\test1\
DestDir C:\test2　←●

結果　C:\test2\　内にファイルが作成されます

３）例外として、G: ドライブのフォルダのない直下にファイルをコピーする場合には、
Source の末尾に * を付与します

Source  C:\test1\*　←●
DestDir G:\　←理由：この \ は取り除けませんから

結果　G:\　内にファイルが作成されます

**Comment by seeringly** [comment]
訂正です。単に \ と書くと「\」マークが表示されないようですね
Source C:\test1「\」*　←●
が正しい意味です

３）例外として、G: ドライブのフォルダのない直下にファイルをコピーする場合には、
Source の末尾に * を付与します

Source C:\test1\\*　←●
DestDir G:\　←理由：この \ は取り除けませんから

結果　G:\　内にファイルが作成されます

**Comment by shirouzu** [comment]
検討します
