### ISSUE TITLE
Sudden speed drop in March 2022

### ISSUE THREAD

**Issue by robwhitelock** [FastCopyLab/FastCopy#102]
I have been using FastCopy for years.  I copy a very large database daily.  Approximately 600 GB in size.  Copying from one rotational drive to another as daily backup.

Recently I have noticed that what used to take under 6 hours now takes just under 12 hours.  The database grows daily, but not that fast.  When I started researching, I discovered that the logs from sometime last March show a sudden drop in copy speed, and it has stayed consistent.  

Is this expected behaviour due to some change in the FastCopy code?  I see no other evidence of strangeness in my database.

Thank you!

**Comment by shirouzu** [comment]
You can try v3.92 (release date 2020-08-02)
https://github.com/FastCopyLab/FastCopyDist

**Comment by robwhitelock** [comment]
Thank you!  I trust there is a way to keep it from auto updating?

**Comment by shirouzu** [comment]
Please see.
![image](https://user-images.githubusercontent.com/1759911/179528388-c5c7a0ad-473c-4b99-820a-c07a24c778c5.png)
