### ISSUE TITLE
Fails to keep Alternate NTFS Stream in folders

### ISSUE THREAD

**Issue by squromiv** [FastCopyLab/FastCopy#103]
**Describe the bug**
AltStream checkbox is set. NTFS streams are not saved during copy/move process.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.1.8 (run from Admin)
 - OS ver: Windows Server 2016x64

**Comment by shirouzu** [comment]
Sorry, but that is a FastCopy limitation.
FastCopy supports file's alt-stream only.
I will consider to support folder's alt-stream.

**Comment by squromiv** [comment]
> I will consider to support folder's alt-stream

Thanks a lot! I am waiting for it. It`s such a basic feature in other apps.
> Sorry, but that is a FastCopy limitation

Sorry, no info about it in description of FastCopy or in help.
