### ISSUE TITLE
「fastcopy」＋「fccheck.exe（破損チェッカー）」最強・最高！

### ISSUE THREAD

**Issue by seeringly** [FastCopyLab/FastCopy#104]
破損ファイルチェッカー「fccheck.exe」実行したら、

確かにサイレントデータ破壊起きていました
4ヶ月位で本当に壊れるですね？
怖いです
見つかったのは３つでしたが、全約69.6万ファイル中で

●こまめに「fccheck.exe」実行しないと危ないです！！
■https://bit.ly/37rgI88 ←新アドレス
fccheck.zip ダウンロード

「結果例」
[NG]Different hash. D:\a.txt

副次ストリーム内のハッシュ値（2022/03/07  08:36　時点）
3757a90dd028fcb2a47ae9b36dda04cb

再計算ハッシュ値
2fa2da128fae37276bce3d5a0c15c810

------------------------------検証
c:\fccheck> dir /r D:\a.txt
 ドライブ D のボリューム ラベルは ボリューム です
 ボリューム シリアル番号は 2A7D-A39E です

 D:\ のディレクトリ

2022/03/07  08:36             1,930 a.txt
                                133 a.txt:fc_verify:$DATA
               1 個のファイル               1,930 バイト

-----------副次ストリーム内のハッシュ値
c:\fccheck> more <  D:\a.txt:fc_verify:$DATA
{done=20220228-134625(0x1d82c5e24778430), ftime=20220131-090608(0x1d81636592564f8), size=1629, xxh3=3757a90dd028fcb2a47ae9b36dda04cb}

-----------再計算ハッシュ値
c:\fccheck> fchash D:\a.txt

xxh3 <2fa2da128fae37276bce3d5a0c15c810>: a.txt

テキストファイルも壊れるんですね！？

**Comment by shirouzu** [comment]
>1 個のファイル 1,930 バイト
>size=1629,

サイズが変わっているので、コピー後に変更があったように見えますね。（サイレント破壊ではなく）
