### ISSUE TITLE
どのコピーが一番早く終わりますか？

### ISSUE THREAD

**Issue by kyuningeng** [FastCopyLab/FastCopy#105]
今流行りの「fccheck.exe」用

Ｄ：ドライブ
　↓
Ｅ：ドライブ

コピー先（Ｅ：）の全てのファイルに、「ベリファイ情報を付与」しようと思っています

やり方はどれが賢いですか？

●まずコピー先ＨＤＤ（Ｅ：）をフォーマットする

１）ベリファイ付きで「差分（上書きなし）」
２）ベリファイ付きで「差分（サイズ・日付）」
３）ベリファイ付きで「差分（最新日付）」
４）ベリファイ付きで「コピー（全上書き）」
５）ベリファイ付きで「同期（サイズ・日付））」

コピー先が空なので
理論上は、どれでも同じ時間だと思いますが、

実際のロジックは違っているでしょうから、、、？

それとも本当に全部同じ時間で終わりますか？
最近ＨＤＤが大きいのでコピーが大変です

**Comment by shirouzu** [comment]
差は無いと思いますが、ご自分でお試しください。
