### ISSUE TITLE
Windows 11 New Modern Right Click Menu Support

### ISSUE THREAD

**Issue by Lozt247** [FastCopyLab/FastCopy#106]
Hi there big fan 
The best file copy software out there.
just wondering if we can have win11 modern right click menu support that would be awesome.

Thank you for your hard work

Oh and tabbed windows for multiple file copies would be awesome so all stay in one open program like google chrome tabs icing on the case
thanks again

**Comment by shirouzu** [comment]
Yes, I think so.
I will consider it.
