### ISSUE TITLE
Improve pause/resume with multiple transfers in queue

### ISSUE THREAD

**Issue by vertigo220** [FastCopyLab/FastCopy#107]
I'm actually tempted to file this as a bug, because of the second part to this, but the pause/resume feature doesn't work well when there are multiple transfers. If you start a transfer from C -> D, then start a few more from C -> D, they will process one at a time in order. The first problem is that if you pause the current transfer, the next one doesn't start (though this does make sense, since you may be trying to reduce activity on the drive for something else and don't want to pause all the transfers individually) and, _most importantly_, if you pause one of the transfers waiting but not the current one, when it's turn comes up, it doesn't proceed, as expected, but neither do any of the others after it.

This often becomes an issue when I have several transfers queued, and I pause a big one to have several smaller ones after it go first, so they'll finish sooner and I don't have all the windows open in the taskbar. But then I have to manually start each one. If the _nonactive_ transfer is paused, that should be taken as an intention to skip it and do the others first. Or else maybe there could be a button to adjust the priority/queue order.

The second issue, which I consider more of a bug, is that if this is done, when the last transfer, aside from the paused one, is started, then before it's finished the paused one is resumed, with the expectation that it will then automatically resume once the other transfer finishes, it actually starts right away. It doesn't account at all for what else is occurring.

I realize it's not really intended to be used in this complex way, and is just a basic copy program designed for speed, so it handles queue processing on a very basic level and doesn't even try to track what's actually going on, but ideally it should.

**Comment by shirouzu** [comment]
Sorry, this is not a bug, but a specification.
