### ISSUE TITLE
Indicate file transfer type (copy / move)

### ISSUE THREAD

**Issue by vertigo220** [FastCopyLab/FastCopy#108]
It would be helpful to have it show whether it's copying or moving the files, both before (while in queue) and during transfer.

**Comment by shirouzu** [comment]
Sorry, but I did not understand what you wrote.
To know the copy mode, why don't you just look at this section?
![image](https://user-images.githubusercontent.com/1759911/181888394-47f506ce-1e5e-4532-ad2a-f63ec54d3b0b.png)

Is it about balloon notification?

**Comment by vertigo220** [comment]
I suppose that's valid. I guess I just didn't think of that because I don't use the overwrite mode, so when copying it says "Diff (No overwrite)" which isn't clear that it's copying. It does say "Move (Size/Date)" when moving, so I guess I can use that to tell. I just feel like having it say what it's doing somewhere, either in the title bar or one of the status boxes, would just help make it more clear and immediately obvious which operation type it's performing, but since technically the information is there, even if not super clear, I guess it's not too important.
