### ISSUE TITLE
Freeze During RDP Session

### ISSUE THREAD

**Issue by JaredEStoddard** [FastCopyLab/FastCopy#109]
Connected from Win 11 to a remote server (Win Server 2019) using RDP over a VPN.  Attempting to transfer large files (e.g. 14Gb).

From the remote server, I can trigger FC from \\tsclient (mapped local drive) to local drive (triggered from remote server0, but not local drive to \\tsclient. When copying remote to local, the icon takes half a spin before the RDP window freezes altogether.

[Troubleshooting]
Shrew  client, Cisco AnyConnect: Fail.
Manual cut/paste: Pass.
Same config (but Win10):  Pass.
v4.1.5, v4.1.8:  Fail.

Any ideas?

**Comment by shirouzu** [comment]
I think tsclient is not normal filesystem.
I have come across some strange behavior on several occasions with tlsclient.
So I recommend not to use fastcopy with tsclient.
Please use explorer or etc.

**Comment by JaredEStoddard** [comment]
First, let me say that FC is one of my *most valuable* development tools.
It's brilliant! Thank you!

tsclient isn't a filesystem but a shared resource via RDP. I tried using an
explicitly mapped drive with the same result.  My problem is that it has
worked in the past (for years) on Win10 but not now on Win11.

I'm a dev as well, and use FC not only to publish our site, but
occassionally pull large production databases from the server.

I recently *had* to migrate to Win11 so have two environments that are
essentially the same except for OS.  Using OS copy takes me about an
hour... FC takes me about 12 min. You can see why I'm panicked...

Would you consider reopening the case?

Again, thank you for this tool...

Jared

**Comment by shirouzu** [comment]
I was able to reproduce it.
This seems to be a Windows 11 issue.
Not using asynchronous I/O may prevent the problem, but will slow it down.
![image](https://user-images.githubusercontent.com/1759911/181926192-4d63d3db-e2c6-43dd-98ec-977b36bcca21.png)

**Comment by JaredEStoddard** [comment]
Thank you so much for looking into it.  And, again, thank you for the wonderful software.

 

Jared
