### ISSUE TITLE
作成日付によるフィルタ

### ISSUE THREAD

**Issue by middlingphys** [FastCopyLab/FastCopy#11]
FromDate・ToDate（/from_date・/to_date）で更新日付によるフィルタが可能ですが、これと同様の、作成日付によるフィルタを追加していただくことはできるでしょうか。

**Comment by shirouzu** [comment]
更新日付よりも作成日付が使いたい、というのはどういった状況でしょうか？

**Comment by middlingphys** [comment]
ダウンロードフォルダにあるファイルを、ダウンロード日時を条件にして処理する（例えばダウンロード後一定期間が経ったファイルを削除する）というような使い方を考えています。
更新日時==ダウンロード日時であれば問題ないのですが、更新日時がLast-Modifiedに基づいて設定される場合があるため、更新日時を条件にすると意図しないファイルが処理されてしまう場合があります。
一方、作成日時はダウンロード日時に一致するため、作成日時を条件にできれば意図した通りの処理ができる、と思い要望しました。

**Comment by shirouzu** [comment]
なるほど、そういったユースケースと。
