### ISSUE TITLE
ファイル破損チェッカーは使っていますが

### ISSUE THREAD

**Issue by synjunbtee** [FastCopyLab/FastCopy#110]
■ファイル破損チェッカー
■https://bit.ly/37rgI88
■fccheck.zip ダウンロード

「fccheck.exe」が登場してやっとサイレントデータ破壊

（ファイル破損）チェックができるようになりました

ただ、既存の

☐ベリファイ情報を付与（副次ストリームへのハッシュ情報等付与）

していなかった昔の古いデータが多数あります

全部またコピー仕直せば済みますが、、、

全部またコピー仕直すのは大変です
新しいHDDの用意なども

そこで
昔の古い「ベリファイ情報を付与」していなかったデータに

「ベリファイ情報を付与」する方法はありませんか？
機能追加できませんか？

**Comment by shirouzu** [comment]
今のところありません/できません。

そろそろ、このツールの宣伝広告のようなissueを建てまくるのは勘弁願えませんか？
（願わくば、別の場所でやってほしいです）
