### ISSUE TITLE
「実行前に確認ダイアログ」のチェックを外しても、実行前に確認ダイアログウィンドウが出てしまう。

### ISSUE THREAD

**Issue by jannefe** [FastCopyLab/FastCopy#111]
**エラー内容**
「実行前に確認ダイアログ」のチェックを外しても、実行前に確認ダイアログウィンドウが出てしまう。

**再現方法**
挙動の確認の為に、一度、「実行前に確認ダイアログ」にチェックを入れたのですが、その後はチェックを外してもコピーや移動の開始前に確認ダイアログが出てしまいます。

FastCopy ver（原則として最新版のみ） :4.1.8

はじめまして。
便利なソフトをありがとうございます。

現在、シェル拡張のドラッグ & ドロップ拡張を使ってFastCopyを起動しているのですが、
コピーや移動の前に
確認ダイアログが必ず出てしまうようになってしまいました。
バージョンはFastCopy4.1.8で、設定→一般設定→その他にある「実行前に確認ダイアログ」のチェックは外しています。
iniの編集で何とかなりそうですが、どこを書き換えれば良いのか教えてもらえませんか？

確信はないのですが、FastCopyをインストール後、一度も「実行前に確認ダイアログ」のチェックを入れた事がないタイミングでは、
実行前の確認ダイアログは出ていなかったと思います。
挙動の確認の為に、一度、チェックを入れたのですが、その後はチェックを外しても確認ダイアログが出続けしまいます。

**Comment by synjunbtee** [comment]
FastCopy ver（原則として最新版のみ） :4.1.8

Windows10 21H2 OSbuild19044.1826 pro 64bit
---------------------
うちでは再現しませんでした

OSのバージョンですかね？

Windows11 ですか？

**Comment by shirouzu** [comment]
こちらを設定も確認してみてください。
![image](https://user-images.githubusercontent.com/1759911/181883004-9bc99b5c-9d91-4e21-ba53-e9ca4373a38f.png)

**Comment by jannefe** [comment]
> FastCopy ver（原則として最新版のみ） :4.1.8
> 
> ## Windows10 21H2 OSbuild19044.1826 pro 64bit
> うちでは再現しませんでした
> 
> OSのバージョンですかね？
> 
> Windows11 ですか？

Windows 10でした。shirouzuさんの方法で解決しました(勘違いしていました)。ありがとうございました。

**Comment by jannefe** [comment]
shirouzuさんの方法で解決しました(勘違いしていました)。GitHubに不慣れなもので、過去に同じ投稿があった事に気づけませんした。お騒がせしてすいませんでした。
