### ISSUE TITLE
Copy files from NAS : first level subdirectory not created in DestDir

### ISSUE THREAD

**Issue by Cpr63** [FastCopyLab/FastCopy#112]
**Question**
Bug or wrong command options ?

Tried to copy files from \\NUBO (Synology Nas)  to PC with following command

D:\BU\FastCopy>FastCopy.exe /Logfile="test.log" \\NUBO\DIMI\ /to=D:\BU\TEST\

Result : 
source subdirectory "DIMI" is not created in the DestDir
the subdirectories from DIMI are direct created under D:\BU\TEST\
it seems the FastCopy program is omitting the last "\" when the source directory is on a NAS 

LOGFILES
test.log=================================================
FastCopy(ver4.1.8) start at 2022/07/31 15:52:42
<Source>  \\NUBO\DIMI\
<DestDir> D:\BU\TEST\
<Command> Diff (Size/Date)
<FileLog> D:\BU\FastCopy\Log\20220731-155242-0.log
-------------------------------------------------

TotalRead  = 35 MiB
TotalWrite = 35 MiB
TotalFiles = 13 (9)
TotalTime  = 47.6 sec
TransRate  = 0.79 MB/s
FileRate   = 0.27 files/s

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/07/31 15:53:30
=================================================

20220731-155242-0.log=================================================
FastCopy(ver4.1.8) start at 2022/07/31 15:52:42
<Source>  \\NUBO\DIMI\
<DestDir> D:\BU\TEST\
<Command> Diff (Size/Date)
-------------------------------------------------
+ D:\BU\TEST\
+ D:\BU\TEST\#recycle\   <20220130-211358>
+ D:\BU\TEST\#recycle\desktop.ini   <20220130-211358 74>
+ D:\BU\TEST\2Sort\   <20220131-074902>
+ D:\BU\TEST\2Sort\Aandelenregister\   <20220130-215109>
+ D:\BU\TEST\2Sort\Aandelenregister\aandelen-aan-toonder.pdf   <20090703-193524 242,957>
+ D:\BU\TEST\2Sort\IMME\   <20220131-074904>
+ D:\BU\TEST\2Sort\IMME\20200304_075904.jpg   <20200304-065904 3,520,174>
+ D:\BU\TEST\2Sort\IMME\20200502_105900.jpg   <20200502-105901 3,637,389>
+ D:\BU\TEST\2Sort\IMME\20200502_105913.jpg   <20200502-105914 3,311,517>
+ D:\BU\TEST\2Sort\IMME\20200502_105923.jpg   <20200502-105924 3,476,943>
+ D:\BU\TEST\2Sort\IMME\20200502_111655.jpg   <20200502-111655 2,583,805>
+ D:\BU\TEST\2Sort\IMME\20200502_111706.jpg   <20200502-111706 2,220,854>
+ D:\BU\TEST\2Sort\Kamion\   <20220130-215109>
+ D:\BU\TEST\2Sort\Kamion\IMG-20200301-WA0014.jpg   <20200301-201945 178,600>
+ D:\BU\TEST\2Sort\Sealer voor plastiek\   <20220130-215110>
+ D:\BU\TEST\2Sort\Sealer voor plastiek\20191106_103333.jpg   <20191106-103333 3,674,547>
+ D:\BU\TEST\2Sort\Sealer voor plastiek\20191106_103352.jpg   <20191106-103352 3,475,107>
+ D:\BU\TEST\2Sort\Stapelaar\   <20220130-215110>
+ D:\BU\TEST\2Sort\Stapelaar\Makro-Totalifter\   <20220130-215111>
+ D:\BU\TEST\2Sort\Stapelaar\Makro-Totalifter\Stapelaar-01-StackingLifting.pdf   <20200213-103913 7,066,311>
+ D:\BU\TEST\2Sort\Stapelaar\Makro-Totalifter\Stapelaar_13991306_totallifterLeaflet_ENG.pdf   <20200213-103510 4,115,997>

TotalRead  = 35 MiB
TotalWrite = 35 MiB
TotalFiles = 13 (9)
TotalTime  = 47.6 sec
TransRate  = 0.79 MB/s
FileRate   = 0.27 files/s

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/07/31 15:53:30
=================================================

**Comment by shirouzu** [comment]
UNC name "\\\\server\\share_name\\" is volume name, like a "C:\\".
("share_name" part is not sub directory)
So, if you want to add "DIMI", please use /to=D:\\BU\\TEST\\DIMI\

**Comment by Cpr63** [comment]
Thanks for the fast reply and clear explanation !
