### ISSUE TITLE
「実行前に確認ダイアログ」が機能しない

### ISSUE THREAD

**Issue by sincos2854** [FastCopyLab/FastCopy#113]
素晴らしいソフトウェアを公開してくださりありがとうございます。
不具合と思われる現象が発生したので報告します。

**エラー内容**
下記のWindowsのクリーンインストール後にFastCopyをクリーンインストールした環境です。
右ドラッグでのコピー及び移動で確認ダイアログを表示したくないのですが、
「一般設定」-「その他」-「実行前に確認ダイアログ」
のチェックボックスをオンにしてもオフにしても確認ダイアログが表示されてしまいます。

**再現方法**
任意のファイルもしくはフォルダをマウス右ドラッグでコピーもしくは移動しようとする。

**コマンドライン・オプションや各種設定**
「設定」-「一般設定」-「その他」-「実行前に確認ダイアログ」のチェックボックスの
オン・オフ両方

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : v4.1.8 
OS ver : Windows 10 Pro x64 21H2 build 19044.1865

**スクリーンショット**
一般設定_その他.png
![一般設定_その他](https://user-images.githubusercontent.com/107011405/182283172-21c4b7ee-bdce-4aec-8b12-73fae4307593.png)

**Comment by shirouzu** [comment]
シェル経由は別途、確認チェックボックスがあります。
（たしかに判りづらいので、将来 I/F を変更するかもしれません）
https://github.com/FastCopyLab/FastCopy/issues/111#issuecomment-1200111998
