### ISSUE TITLE
RAID0大容量ディスクへのコピー時70MB/s制限について

### ISSUE THREAD

**Issue by decosket** [FastCopyLab/FastCopy#115]
**質問**
お世話になっております。質問をお許し下さい。
・FastCopy ver.4.1.8 使用
・OS:Windows10 Pro (21H2)
・使用RAIDカード:NEC N8103-150(LSI MegaRAID SAS 9266-8i)
・RAID:16TB HDD×4または8TB HDD×8、RAID0構成
　容量:64TB(58.2TiB)
上記構成のドライブへ、内蔵HDD、外付けHDD(USB3.0)、
ネットワークドライブから、いずれからも70MB/s付近で
コピー・転送速度が頭打ち(制限された)状態となります。
Windows10のエクスプローラーでは同環境170MB/s以上の
速度が出ています。
・試したこと
1. 別HDDモードへの変更、物理ドライブグループの手動指定
⇒70MB/sで変わりません
2. Windows10Proエクスプローラーの使用
⇒170MB/s以上の上限速度が出ているようです
3. 同一HDDモードでのSSD内コピー ⇒200MB/s以上速度出ます
4. 内蔵HDD、外付けHDD(USB3.0)、2.5GbE LANのネットワーク
　ドライブからコピー、転送 ⇒全て70MB/s付近で頭打ち
5. Windows10のストライピング(ソフトRAID:RAID0)で、
　8TB×2、16TB(14.55TiB)RAIDドライブへのコピー、転送
⇒200MB/s以上の速度が出ています

上記の速度頭打ち(制限)の理由、設定・対処法について
ご教示頂ければ幸いです。

**Comment by shirouzu** [comment]
ちょっと思い当たる節がないのですが、I/O設定で、
・非同期I/O数を20以上に増やす
もしくは
・非同期I/O数を1にして、I/O単位を8MBにしてみる
あたりでしょうか。
（それ以外にも、試行錯誤してみると良いかも）
