### ISSUE TITLE
Checksum Hash for released installer

### ISSUE THREAD

**Issue by dgleba** [FastCopyLab/FastCopy#118]
**Question**
Is there an official checksum or hash of the released software? I want to ensure I am getting an unaltered copy.
I want to ensure that no one has added any malware to the download after you prepared the release.

![Screenshot from 2022-08-19 09-57-55](https://user-images.githubusercontent.com/4622715/185635192-9b9edc21-8ae3-4da2-b1a9-c6f477eb37d7.png)

**Comment by shirouzu** [comment]
You can verify that FastCopy.exe and FastCopy installer are an official version from the code signature.
![image](https://user-images.githubusercontent.com/1759911/185729404-12d76cb5-59c6-4165-b199-19ce71558521.png)

**Comment by dgleba** [comment]
Thanks!
