### ISSUE TITLE
fcp.exeで同期せずにリストアップをファイル出力できますか？

### ISSUE THREAD

**Issue by kamitatoro** [FastCopyLab/FastCopy#119]
**質問**

いつも便利に使用させて頂いています。

同期モードでフォルダを同期したときの結果を、実際には同期せずにリストだけ取得するために、
```
fastcopy.exe /cmd=sync /filelog=log1.txt /no_exec from_dir /to=to_dir
```
で起動後、「リストアップ」ボタンをSHIFT+クリックして、log1.txtをテキストエディタで開いて確認しています。

CUI版で同じようにリストだけを取得することは可能でしょうか？
```
fcp.exe /cmd=sync /filelog=log1.txt /no_exec from_dir /to=to_dir
```
を実行するとコマンドヘルプが表示され、処理が実行されないのですが、他の方法はありますでしょうか？

**Comment by shirouzu** [comment]
残念ながら、今のところ出来ません。

**Comment by kamitatoro** [comment]
承知しました。ご回答ありがとうございます。
