### ISSUE TITLE
FastCopy ver4.0.1 - issue with 'Filter' 'FromDate'

### ISSUE THREAD

**Issue by filou-git** [FastCopyLab/FastCopy#12]
Hi 
I was using FastCopy ver3.92 without any issue. After upgrade to ver4.0.1, I noticed that the copy using 'Filter' 'FromDate' was not working anymore. It listed all files without taking into account the filter. I was using this Filter function a lot in the past without problem.
I reinstalled ver3.9.2 and the filter FromDate just working fine again. So the issue is related to ver4.0.1.

Thanks and regards

**Comment by FastCopyLab** [comment]
Thank you for your report.
We have released v4.0.2, which fixes the problem.

**Comment by filou-git** [comment]
Great, it works again with v4.0.2

Many thanks!
