### ISSUE TITLE
「接続できません」でアイコンを真っ赤にできますか？

### ISSUE THREAD

**Issue by rytntecjn** [FastCopyLab/FastCopy#120]
タスクバーの小さなアイコンだけ見ていても、
ディスクがいっぱいでコピーできず
「接続できません」で中断しているのがわかりません
（勿論写真1を表示すればわかりますが、写真1を表示すること自体を
気づきにくいです）

理由は単にタスクバーの小さなアイコンに変化がないからです
（どう見てもアイコンは正常3%コピー中を表しています）

タスクバーの小さなアイコン（写真2の左側の①）を真っ赤に染めるなり
変化がおきれば異常（中断）がわかり安いと思います

![写真1](https://user-images.githubusercontent.com/112218954/187005872-c0a28be5-47fc-4761-b59d-280b55c3699d.jpg)

![写真2](https://user-images.githubusercontent.com/112218954/187005897-5a87e0bd-493a-4a90-8b08-cd2ac7b89c8a.jpg)

**Comment by shirouzu** [comment]
検討しておきます。
