### ISSUE TITLE
Does verify detect read errors?

### ISSUE THREAD

**Issue by chanclr** [FastCopyLab/FastCopy#121]
**Question**
Does verify detect read errors? Currently it does
Read(Src) → xxHash(Src) → Write(Dst) → Read(Dst) → xxHash(Dst) → Compare xxHash(Src/Dst)

What if there is an error during Read(Src)?
What about this?
Read(Src) → Write(Dst) → Read(Src) → xxHash(Src) → Read(Dst) → xxHash(Dst) → Compare xxHash(Src/Dst)

**Remarks**

**Comment by rytntecjn** [comment]
I do not understand the true meaning.

"Does the verify detect a read error?"

And if the answer is NO, what is the next step?

or

If the answer is YES, what does it do next?

"Read(Src) → Write(Dst) → Read(Src) → xxHash(Src) → Read(Dst) → xxHash(Dst) → Compare xxHash(Src/Dst)."

Do you want it changed like this?

Do you think your idea is better than the current one?

Maybe YES?

**Comment by shirouzu** [comment]
> Does verify detect read errors? 

Sorry, it is no.

**Comment by shirouzu** [comment]
P.S FastCopyPro v5.0's "perfect verify" can now also detect the read(src) errors.
