### ISSUE TITLE
コピーリトライ機能（の設定）

### ISSUE THREAD

**Issue by FastCopy420** [FastCopyLab/FastCopy#122]
**機能リクエスト内容**
ReadFile(データ エラー (巡回冗長検査 (CRC) エラー) です。23)　のエラーが出てコピーをスキップする場合、スキップまでの再試行回数を設定できるようにしてほしい

**補足**
上記エラーでコピーがスキップされたファイルをwindowsのエクスプローラーでコピーすると、時間はかかりますがコピーできる場合があるためです。
（不思議なことにエクスプローラー単体でコピーを行うと、何度もリトライするかキャンセルするかの確認Windowが出てきて巧くコピーする事が出来ないことがあるのですが、FastCopyでコピーを行っている最中にエクスプローラーでコピーを行うと・・・時間はかかりますがファイルのコピーができるのです）

**Comment by rytntecjn** [comment]
同じコピーを「TeraCopy」でやると、ちゃんとコピーできませんか？

「理由」
「TeraCopy」は単なるファイルコピーソフトではなく、
エラーで読み込めないファイルを回復させる機能があるようです。

ReadFile(データ エラー (巡回冗長検査 (CRC) エラー)でもコピー
できるのでは？

fastcopyはスキップのみで、回復機能はありません

**Comment by shirouzu** [comment]
これはOS側が勝手にリトライしているだけなので、残念ながらFastCopy側では制御できないですね。

> エラーで読み込めないファイルを回復させる機能

うん？
（取り出してHDDサーフェイスのアナログ信号を読み取る等は別とするならば）ソフトウェアで実現できる気がしないのですが、それは公式の情報でしょうか？？

**Comment by rytntecjn** [comment]
今は質問された方に聞いているところです

その方が「TeraCopy」では問題なく全部コピーできました

というのを待ちましょう

ただ「TeraCopy」が嫌いで、やらない可能性もありえます。。

**Comment by shirouzu** [comment]
いやいや。
私は、公式に謳っている機能ですか？と聞いているのですが。
Yes or No で答えられる話ですよね。

**Comment by FastCopy420** [comment]
皆様

お返事いただきましてありがとうございます。
FastCopy側で制御する事が出来ないという情報を教えていただきましてありがとうございました！

こんなに素早いお返事があるものと思っていなかったため、要望として書き込みしましたがHDDの復旧は既に諦めた
後の書き込みでした。

読み込みが出来なくなったHDDは、リトライを続けるのがしんどかったのでデータを諦めて分解してしまいました。
ゆえに「TeraCopy」を試すことはできませんでした。

該当HDDは子供と一緒に分解してしまい、今はプラッタは糸で吊って子供の楽器に・・・
ヘッドを動かす永久磁石は取り出され冷蔵庫に貼り付けられています。

解決法を考えていただきましたのに試す事が出来なくてすいませんでした。
