### ISSUE TITLE
入力ボックスについては行数制限があります

### ISSUE THREAD

**Issue by secrethcb** [FastCopyLab/FastCopy#124]
**質問**
there is a line limit about the input box, about 1000 lines , if there are 10000 file paths，then can not input or paste them into source input box.

入力ボックスに入力できるパス情報は 1,000 行のみで、削除するファイルが 1,000 個を超える場合は入力ボックスに入力できません。

**備考**

**Comment by shirouzu** [comment]
現在の制限は、32767文字です。
（将来、40億文字まで制限を広げる予定です）

しかし性能面から言うと、src は少ないエントリで使うのが好ましいです。

**Comment by secrethcb** [comment]
> 現在の制限は、32767文字です。 （将来、40億文字まで制限を広げる予定です）
> 
> しかし性能面から言うと、src は少ないエントリで使うのが好ましいです。

Okay, it is useful for operating huge number of files Specified. waiting...
