### ISSUE TITLE
Fast copy UNC path make new folder in destination

### ISSUE THREAD

**Issue by wongcc2012** [FastCopyLab/FastCopy#125]
(Resolved).
please help to DELETE the post

**Comment by shirouzu** [comment]
Please see.
https://github.com/FastCopyLab/FastCopy/issues/112#issuecomment-1200589495

**Comment by wongcc2012** [comment]
I have multiple folders How can I use the GUI to copy all of them in single job?
If not do you mean I have to use the command-line? How can I get / generate the full command line from the GUI?

**Comment by shirouzu** [comment]
>I have multiple folders How can I use the GUI to copy all of them in single job?

Sorry, it can't.
You must use multiple jobs or batch files.

**Comment by wongcc2012** [comment]
if using batch files, how can I get the command from the GUI?

**Comment by shirouzu** [comment]
Sorry, it can't.

**Comment by wongcc2012** [comment]
how can I get the parameters from the command line?

**Comment by shirouzu** [comment]
??
Sorry, I couldn't understand what you wrote.
If you want to make command line, please see.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline
