### ISSUE TITLE
It would be nice to have an option to have FastCopy overwrite an existing Log File instead of appending to it.

### ISSUE THREAD

**Issue by Retr0Pixel** [FastCopyLab/FastCopy#127]
For Example, this is one of my three Backup Jobs i use FastCopy for:
FastCopy.exe /job=BackupDriveC /estimate=FALSE /no_ui /log /logfile=E:\Backup\Logs\DrvCLog.log /filelog /filelog=E:\Backup\Logs\DrvCList.log

Since it always appends to the existing Logfiles, they grow quite large over time. I am using this Method for about 4 Months now and the DrvCList.log grew to about 800 MB.

**Comment by shirouzu** [comment]
I will consider it.
