### ISSUE TITLE
[Bug] At the log, Destination file to be replaced is returning the date and size of the Source file instead

### ISSUE THREAD

**Issue by byblo** [FastCopyLab/FastCopy#128]
Hello.

At "Listing" function for Sync/Date mode, when "Delete before copying" is enabled and a file is about to replace another, the reported file date and size are taken from the source instead the destination.

For instance, for:
Source: `R:\1`
DestDir: `R\2`
Containing files: R:\1\_folder.m3u (20210713), when R:\2\_folder.m3u (20101006)

The Listing result with FastCopy 4.2.1 is giving me this:
--------------------------------------------------------------------------------
`- R:\2\_folder.m3u   <20210713-163424 16,646>`
`+ R:\2\_folder.m3u   <20210713-163424 16,646>`
`Finished. (ErrorFiles : 0  ErrorDirs : 0)`
`  (2022/11/01 19:37:13)`
--------------------------------------------------------------------------------

When It should be instead:
--------------------------------------------------------------------------------
`- R:\2\_folder.m3u   <20101006-011225 3>`
`+ R:\2\_folder.m3u   <20210713-163424 16,646>`
`Finished. (ErrorFiles : 0  ErrorDirs : 0)`
`  (2022/11/01 19:37:13)`
--------------------------------------------------------------------------------
Notice the `<20101006-011225 3>` which is correct for the destination file to be replaced by `<20210713-163424 16,646>`

**Comment by shirouzu** [comment]
Thank you for your report.
I confirmed it.
