### ISSUE TITLE
Sync also attributes

### ISSUE THREAD

**Issue by byblo** [FastCopyLab/FastCopy#129]
Hello.

Would be nice if FastCopy also sync files by attributes if they are not matching.

For instance, if both files from source and destination are identiqual, but source is read-only but not hidden attribute, then destination should be updated if attributes are not similar. (no file copy, only attributes copy)

For instance:

Source: r:\1\test.bin +A-H
Destination r:\2\test.bin +H

Should give the result:
Destination r:\2\test.bin +A-H

**Comment by shirouzu** [comment]
I will consider it.
