### ISSUE TITLE
timestamp 

### ISSUE THREAD

**Issue by mi99ss99** [FastCopyLab/FastCopy#13]
**Question**
Hi, I've use Fastcopy v3.92 for the following statement
FastCopy.exe /cmd=diff /no_ui /force_Close /Estimate /filelog=%mylogfile% /bufsize=2000 "SOURCE" /to="DESTINATION"
after Fastcopy autoupdate to v4.02, the same statement, the detail log have timestamp. May I ask which statement can disable this function. and how can i resotore to old fastcopy version. Thank you for your help.
(Please do not ask anything that you can figure out by experimenting at hand).

**Remarks**
Please add any additional information or screenshots.
![圖片](https://user-images.githubusercontent.com/50563296/150903810-52977ff1-0a4c-48f8-a711-276075d3ccc0.png)
and what does it numbers imply for. Thanks

**Comment by FastCopyLab** [comment]
Sorry, after ver4.0, there is no way to stop it.
(And we do not provide access to older versions.)

**Comment by mi99ss99** [comment]
Thank you.
