### ISSUE TITLE
[request feature] Alternate Data Streams list of file to synchronize

### ISSUE THREAD

**Issue by byblo** [FastCopyLab/FastCopy#130]
Hello.

I am using intensively the Alternate Data Streams system on my NTFS files.

When synchronizing my files, with the Sync(Size/Date), the app is missing the ADS content differences between a file from the source and the destination if they both exists already and are similar in size and date.

For instance, if a source has both same files but different ADS files content, for instance if:
 r:\Source\test.bin:cache.ini <50KB> and r:\Destination\test.bin:cache.ini <12KB>, the FastCopy will unfortunately miss to update the ADS content.

Would be nice to have some new edit box to specify which ADS files has to be checked and synched.

For instance, an edit box to enter something like:   [:cache.ini, :thumbnail.jpg]

Of course, this will slower and maybe a lot the listing function, since the app will need to:
- In case file does exists only on source, then copy the ADS file on destination.
- In case file does exists only on destination, then delete the ADS file on destination.
- In case both files has the ADS file with different file size, then copy the ADS file on destination.
- In case both files exists but has same size, then compare by content to know if destination needs to be updated.

Maybe slower, but this would be a great addition for intensive ADS users to synchronise their files properly.

**Comment by shirouzu** [comment]
??
If alt-streams is added, won't the timestamp be updated?

**Comment by byblo** [comment]
Yes timestamp is usualy updated after adding/modifying an alt-stream, but some tools are restoring the main original timestamp after the modification: the philosophy behind is that the main file timestamp is mandatory against secondary alt-stream files.

Also, It would be better to only update the alt-stream file than the whole file.
For instance, if an big 8GB file has only one of its alt-stream of 50KB modified (or removed), it would be better to only syncronize the updated alt-steam file, and not the whole 8GB file that is unchanged.
