### ISSUE TITLE
7-zip(7z.dll)を利用した圧縮ファイルサポート

### ISSUE THREAD

**Issue by SysVR** [FastCopyLab/FastCopy#131]
**機能リクエスト内容**
圧縮ファイル内のファイル/フォルダ、圧縮ファイル自体をディレクトリとして
SourceまたはDestDirに指定。

**補足**
7z.exe(コマンドラインプログラム)を見たらFastCopyでアーカイブファイル対応できそうだと思ったため。

**Comment by shirouzu** [comment]
それはちょっと難しそうですね。
