### ISSUE TITLE
slow copy while syncing (from scheduler)

### ISSUE THREAD

**Issue by claaaaash** [FastCopyLab/FastCopy#132]
**Describe the bug**
I experience strange slow copying while executing fastcopy from .bat file with sync option as follows:

    fastcopy /cmd=sync /exclude=$RECYCLE.BIN\;"System Volume Information\";"Dropbox\.dropbox.cache\";"~$*.xl*";"~$*.doc*";"install\DiskSpd\amd64\" /auto_close /verify H:\ /to=M:\

Recently, I have added a big file (>60GB) to disk H: and would like to have it synced to M: with the command above. I have fast hardware, and if I copy manually this file with fastcopy (i.e., using right-click "copy" context menu), I have ~5GBytes/sec. If I execute cmd line above, I have only ~300MB/s. I checked that fastcopy options (Diff HDD, buffer size, I/O unit, overlap I/O num) — they are identical. "Verify" options has no impact (it allows copying and verifying at 12GB/s). CPU usage is zero during 300MB/s copying. I tried to disable MS defender, but no difference.

**To Reproduce**
Steps to reproduce the behavior: execute the command line above on large file(s).

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.
See above. 

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.2.1
 - OS ver: win 10 LTSC

**Screenshots**
Left: fastcopy from cmd line (.bat file), right: the same file copying manually via right click/context menu.
![fastcopy_slow](https://user-images.githubusercontent.com/118083649/201498163-1f825fc2-10f5-4524-a712-24107bf12145.png)

**Comment by shirouzu** [comment]
It is strange.
What would happen if you ran the sync command manually instead of in a batch file?

**Comment by claaaaash** [comment]
Hm, if I run it from cmd, it is fast (as right panel). I just re-checked, even running .bat file itself is fast. The problem occurs when I run this .bat file from the windows task scheduler. Any ideas what can impact execution of fastcopy from task scheduler?

**Comment by shirouzu** [comment]
When launched from the task scheduler, the I/O priority is lowered.
See below for a solution.
https://serverfault.com/a/257183

**Comment by claaaaash** [comment]
After following the suggestion and changing task priority to <Priority>4</Priority> everything works as it should. So, there is no bug in FastCopy :) Btw, I did not expect that the difference in performance can be so huge due to priority.

Thank you for prompt and accurate replies. FastCopy is the best and fastest!)
