### ISSUE TITLE
Performance similar to DiskSpd

### ISSUE THREAD

**Issue by claaaaash** [FastCopyLab/FastCopy#134]
**System description**
I have a raid controller (with many SSDs) connected to PCIe 4.0 x16 interface which is able to provide theoretical 32GB/s one way, and full duplex speed is twice of that, ie. 64GB/s. With [DiskSpd](https://github.com/microsoft/diskspd) benchmark tool (version `2.1.0-dev (2021/7/1)`) I was able to get >40GB/s, while FastCopy provides ~24GB/s (see screenshot). For DiskSpd, I used the following settings:

    diskspd.exe -b1M -t2 -o256 -d20 -Sh -si -w50 testfile.dat

I.e., sequential 50% read+50% write in 1MB blocks using two threads and 256 outstanding operations. With FastCopy copying the same 512GB `testfile.dat`, the maximum performance I was able to get is with these settings::

- Diff HDD mode
- Buffer Size = 2049MB
- I/O unit = 256MB
- OverLap I/O = 2
- verify is off

Using `ACL`and `AltStream` has no impact on performance. 

**Question**
Is it possible to achieve performance for sequential read+write similar to DiskSpd? Also targeting performance above half-duplex speeds.

![diskspd_vs_fastcopy](https://user-images.githubusercontent.com/118083649/201518045-3be8ab2e-b5df-4f7a-8470-bfd60459c235.png)

**Comment by shirouzu** [comment]
I don't know but,...
-b1M means I/O unit 1MB in FastCopy settings.
-o256 means OverLap I/O Num 256 in FastCopy settings.

**Comment by claaaaash** [comment]
I understand that. But if I use I/O unit of 1MB and OverLap I/O of 256, I get only 5GB/s of total I/O with FastCopy.

DiskSPD has open source code, can this help you to find what exactly DiskSPD doing differently to perform faster I/O?

**Comment by shirouzu** [comment]
Yes.
But to investigate, it requires not only the source code but also very high speed RAID system :-)

**Comment by claaaaash** [comment]
I would like to assist you doing benchmarks on my hardware, if you like.

**Comment by shirouzu** [comment]
Thank you!

**Comment by shirouzu** [comment]
Could you tell me the result of diskspd.exe test without -t2 option?

**Comment by claaaaash** [comment]
I believe I need to specify the number of threads. For this single-threaded test

    diskspd.exe -b1M -t1 -o256 -d10 -Sh -si -w50 testfile.dat

the performance is the same, ~42GB/s. BTW, can we switch to email communication?

**Comment by claaaaash** [comment]
I think I found one more hint: for some reason, FastCopy does not respect/provide the requested queue length. For example, the screenshot shows diskspd with `-b1M -t1 -o256`, while FastCopy `I/O unit 1MB` and `Overlap I/O num 256`, i.e. identical to diskspd. The actual FastCopy queue length according to perfmon is only ~3, while for diskspd it is >200. (Please notice multiplier of 0.1 to blue Y-axis values). Red color is total I/O in 10^9 bytes per sec.

![diskspd_vs_fastcopy_queue_length](https://user-images.githubusercontent.com/118083649/201779246-757e123f-1719-4e6b-8569-0372d62fd060.png)

**Comment by shirouzu** [comment]
It is very interesting.
I will investigate.

**Comment by shirouzu** [comment]
I have investigated.
Please try this with Admin mode.
https://fastcopy.jp/archive/special/FastCopy4.2.1r2_installer.exe

**Comment by claaaaash** [comment]
Thank you. Strange, but it is almost the same (say not 3 but 5 queue length). Screenshot for `I/O unit 1MB` and `Overlap I/O num 256`:

![diskspd_vs_fastcopy_queue_length_4_2_1r2](https://user-images.githubusercontent.com/118083649/202143024-cabe4e8c-5004-42c9-b87d-cdfba85dd3b6.png)

**Comment by shirouzu** [comment]
Run as administrator?

**Comment by claaaaash** [comment]
Sorry, my bad, it was without admin. With admin, QD is excellent now (screenshot)! Moreover, QD is twice of what is specified in GUI of FastCopy. Look at I/O red curves, they are smoother now, probably because with larger QD it is easier to predict/schedule I/O load.

But I/O performance in GB/s stayed approximately the same, below half-duplex level. Is there any way to break this level (32GB/s, towards 40BG/s as in `diskspd.exe -b1M -t1 -o256 -d20 -Sh -w50 testfile.dat`)? Just one more difference: `diskspd` performs benchmark within one single file, while fastcopy creates 2nd file, probably this can be a hint or limitation.

(By the way, I run `diskspd` without admin)

![diskspd_vs_fastcopy_queue_length_4_2_1r2_admin](https://user-images.githubusercontent.com/118083649/202152534-c4cfa830-02d7-47ad-8361-a6bf9906025a.png)

**Comment by shirouzu** [comment]
>this can be a hint or limitation.

Yes.
If you delete testfile.dat and run diskspd without admin, you get a warning message and you get small qd at opening.
(Because SetFileValidData API requires admin mode and large number of qd requires allocated file.)

I will consider good test sequence...please wait.

**Comment by shirouzu** [comment]
Please try this.

1. add test mode in FastCopy. (test mode is write only mode)
![image](https://user-images.githubusercontent.com/1759911/202156276-d4df8c5a-614a-43da-8e1a-621114c5e1e1.png)

2. restar FastCopy and select test mode.
![image](https://user-images.githubusercontent.com/1759911/202156668-65424821-123c-4875-8a23-9f8d63a35828.png)

3. Elevate to admin.

4. Describe "w=512G,1,1" in Source, and RAID-path in DestDir
![image](https://user-images.githubusercontent.com/1759911/202158381-7e4f5780-6e8f-4289-b7e4-eab1c9a4d551.png)

5. run

(test file will be create as RAID-path\dname_0\fname_0)

**Comment by claaaaash** [comment]
This procedure has created a file `dname_0\fname_0` with ~19GB/s write speed. And, by the way, QD from perfmon now was corresponding to what I specified (i.e., 128 in FastCopy and ~128 in perfmon, not twice of that).

**Comment by shirouzu** [comment]
Thank you.
It is not good result, but I don't know what caused this.

**Comment by claaaaash** [comment]
Wait, I think this is totally normal result: -write only- performance in `diskspd` is about 24GB/s too. One needs both read and write to enable full duplex mode.

**Comment by shirouzu** [comment]
I see.
Anyway, I don't know what caused this.

P.S The copy(not test) mode use QD not only dest-write but also src-read, so the number of QD will be twice of the settings.

**Comment by claaaaash** [comment]
Got it. So, you may close this issue. If you will have new ideas and would like to test, please re-open the issue or comment here; hope not to miss notification :)

**Comment by shirouzu** [comment]
Thank you for your cooperation.
Please let me know if you notice anything else, as I too would like to resolve this issue.

**Comment by claaaaash** [comment]
May be one more idea from my experience with I/O on linux systems: before copying, is there a way 
1) to create an empty file with  zero size and re-open it after creation, or 
2) to create an empty file of the final size, close it, re-open and start populating with the source file? I.e., something like fopen -> fseek(to the final destination) -> fwrite(some zero) -> flose -> fopen again.

I do not know if this is possible under windows and if this will make any difference at all, without introducing additional issues.

**Comment by shirouzu** [comment]
Thank you.
Unfortunately, FastCopy already works that way.
(It works well for contiguous areas)

**Comment by shirouzu** [comment]
Can I request two tests? (normal copy)
buffer: 512MB, I/O: 1MB, OverLap: 128
buffer: 512MB, I/O: 2MB, OverLap: 64

**Comment by claaaaash** [comment]
Here are the results:

![diskspd_vs_fastcopy_qd_64_128](https://user-images.githubusercontent.com/118083649/202204815-71dd1ad2-ebe9-4519-b662-0dfffd64288e.png)

**Comment by shirouzu** [comment]
Thank you.
Hum...
Can I request explorer and robocopy tests?
(I want to know 40GB/s is only benchmark or not)

**Comment by claaaaash** [comment]
yes, please specify what exactly you would like to see.

But from my previous experience, when I was looking for the copy software, explorer was similar to robocopy, And explorer performance is — I just rechecked — ~2.5GB/s copy (or 5GB/s total I/O). I.e., with FastCopy, it is totally different dimension of performance with 12GB/s copy (or 24GB/s total I/O). Actually, -only- with FastCopy with proper settings: I also checked other 3rd party tools, but they were similar to explorer.

**Comment by shirouzu** [comment]
Thank you. OK.
I wanted to know is the copy speed of Explorer/Robocopy are at a similar level, significantly faster(like diskspd), or significantly slower than FastCopy.

**Comment by claaaaash** [comment]
As explained, Diskspd > fastcopy >> explorer and Co.

Probably, under windows/ntfs copying into the new file is the principal limitation and cannot be overcome to enable full duplex performance :/

**Comment by claaaaash** [comment]
And one more small follow up question: now, how can I use fastcopy from right click drag and drop menu in admin mode? I added the context menu entry, but when I drag and drop with right click, and select "copy", nothing happens at all. I have chosen "run this program as admin" for "C:\Users\user_name\FastCopy\FastCopy.exe"  executable properties, but it has no impact on right click drag and drop.

**Comment by shirouzu** [comment]
When confirming a drag-and-drop copy, please select the elevate button.
("run this program as admin" can't be used via shell extension)

![image](https://user-images.githubusercontent.com/1759911/202322534-0e29eff5-f6e8-4702-b9b3-3492aa1ed193.png)

**Comment by claaaaash** [comment]
The problem is that after I release the mouse button after drag&drop, there is totally nothing (no menu, no windows).

**Comment by shirouzu** [comment]
Does it happen even if "run this program as admin" is unchecked?

**Comment by claaaaash** [comment]
If this option is unchecked in properties of "C:\Users\user_name\FastCopy\FastCopy.exe", then I can normally copy via right click drag&drop, as before.

**Comment by claaaaash** [comment]
I found what was needed to do. Either

1) "misc settings -> confirm before executing" is unchecked, then one needs to stop copying after drag and drop, click "elevate" text at top right corner, and resume copying

2) "misc settings -> confirm before executing" is checked, then there is a button available as on your screenshot

You may close this issue.

**Comment by shirouzu** [comment]
Could you try this with Admin mode?
https://fastcopy.jp/archive/special/FastCopy4.2.1r6_installer.exe

1. Select test mode.
2. Elevate to admin.
3. Describe "w=512G,1,1,3" in Source and RAID-path in DestDir
4. Run

(I hope the speed is 19GB/ -> 24GB/s)

**Comment by claaaaash** [comment]
It is 26024MB/s now

**Comment by shirouzu** [comment]
Thank you. good "test write" result.

By the way, the following is about fastcopy's normal copy mode.
In my environmet (PCIe v3.0 and NVMe x4 RAID and FastCopy v4.2.1r6), my best parameteter was this.
 diff hdd mode
 bufsize is 2048MB
 overlap num is 128 (not 256)
 I/O size is 1MB
 Admin mode
(the results was about the same speed as diskspd)

Your environment may require a larger buffer size. (4096MB or more)

**Comment by claaaaash** [comment]
I just tried different combinations. The best seems to be 1MB, 128IO, buf > 1G. IO 128 vs 256 shows no difference. Here can be many factors, including firmware of the raid controller I use (it is adaptec SmartRAID Ultra 3258p-32i /e in my case).

Concerning your situation, one needs to find our theoretical half-duplex speed for your number of PCIe 3.0 lanes. Then compare your actual results with this theo. speed. It may happen that due to software layer the full duplex is simply not enabled on your system. In this case, you will see identical results for diskspd and fastcopy at current FC version.

My FC copy performance is ~26000MB/s now, which is just write performance limit. I.e., it is the maximum achievable half-duplex performance. Any number above will require enabling full-duplex which, as we found, seems to be not possible while creating new file (destination) on the fly.

**Comment by shirouzu** [comment]
Yes, it is. Thank you.

> as we found, seems to be not possible while creating new file (destination) on the fly.

However, I am not sure what is causing this.
But I can't think of a good experiment, so I have to do pending this. sorry.

**Comment by shirouzu** [comment]
Perhaps I may have discovered the cause.
Please try this.
https://fastcopy.jp/archive/special/FastCopy4.2.1r8_installer.exe

note.
1. admin mode
2. buffer size must be less than 1000MB(not 1024).
3. diff hdd mode

**Comment by claaaaash** [comment]
the same :| (I tried 64-128-256IO, 1-2MB, buf. size 520-1000MB).

**Comment by shirouzu** [comment]
Thanks for the test.
However, I am disappointed with the results of the test.
I have to do pending this. sorry.

**Comment by claaaaash** [comment]
I am available for more benchmarks if you will have new ideas.

**Comment by shirouzu** [comment]
I added CPU affinity settings.
You may not get good results, but could you please try this?
https://fastcopy.jp/archive/special/FastCopy4.2.1r9_installer.exe

(old version is None. please try Assign one and Assign separate mode)
![image](https://user-images.githubusercontent.com/1759911/204974394-d747d1a3-fa00-461b-b83a-49e51ae85fa6.png)

**Comment by claaaaash** [comment]
I have tried: in principle, the same ("none" and "one logical" is very slightly better compared to "separate logical").

I just recalled one more thing. I am using threadripper pro platform (asus WRX80E-SAGE + 5975wx cpu), and full duplex speeds I was able to get only when CPU I/O priority was set to the PCIe channel number with raid controller installed (NBIO Common Options -> Preferred IO -> Manual + bus number). May be, this is quite specific option, and on the other systems you will not get full duplex at all. You mentioned that you have PCIe v3.0 and NVMe x4 RAID hardware. How much of the total I/O bandwidth do you have while copying a large file?

**Comment by shirouzu** [comment]
Thank you.
However, it was a disappointing result.

> CPU I/O priority was set to the PCIe channel number with raid controller installed 

Hum...I see. but unfortunately, My M/B does not have this option.

> How much of the total I/O bandwidth do you have while copying a large file?

It looks like this.
  read only test:   9.95GB
  write only test: 11.44GB
  read/write simultaneous: 12.77GB.

**Comment by claaaaash** [comment]
> Hum...I see. but unfortunately, My M/B does not have this option.

This seems to be AMD epyc/threadripper-specific option.

And, how many PCIe lanes your card holding NVMe's has? Is it 16x PCIe 3.0?

**Comment by shirouzu** [comment]
The card is HighPoint SSD7505, it is PCIe4.0 x16.
But my M/B is Z370, PCIe3.0 x16 :-(

**Comment by claaaaash** [comment]
Then you have about 80% of the half duplex performance, in principle the same as me. Have you tried to check diskSpd code, what do they do differently?

I was thinking that you may try adding test mode for FastCopy, where the destination file is first fully created (i.e., the whole file is written with some zeros), and only then copy starts, also measuring the performance. In this case the copy process will be altering already existing file without changing its size or creating it. Probably, this could help to test the possibility to observe full duplex at all. But again, it appears that only on my system, because, as you reported, diskSpd shows similar to FastCopy performance on your system.

**Comment by claaaaash** [comment]
Hey, man, it works!!! :) What I have done is 1) rebooted PC, 2) disabled IOMMU in BIOS, 3) disabled PCIe hot swap in BIOS. I do not know what exactly helped out of this. About IOMMU I got an idea while looking for PCIe bus actual performance and finding this article: https://doi.org/10.1145/3230543.3230560

Look at this beauty :) FastCopy is really the fastest.

![fastcopy_fast](https://user-images.githubusercontent.com/118083649/205041842-98c2f0a1-1d09-4a42-a5f7-d507bbddc07c.png)

**Comment by shirouzu** [comment]
That's great!
