### ISSUE TITLE
Elapsed Time In Log File

### ISSUE THREAD

**Issue by therube** [FastCopyLab/FastCopy#136]
Display an elapsed time in the Log file.

`- Result : (ErrFiles : 0 / ErrDirs : 1) at 2022/11/03 14:40:36`

`+ Result : (ErrFiles : 0 / ErrDirs : 1) at 2022/11/03 14:40:36, ET 1:20.00`

**Comment by shirouzu** [comment]
Why do you want a time zone?

**Comment by therube** [comment]
Sorry, Elapsed Time (on the Result line).

So you can see (easily) how long the copy operation took (1:20.00, in my example).

Now you do have a start time:
fcp(ver4.2.0) start at 2022/11/15 19:59:29
And and end time:
Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/11/15 20:45:23

And you can compute an Elapsed Time: 20:45:23 - 19:59:29.

But if it just said something like:

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/11/15 20:45:23, Elapsed Time: 0:45:54

That's easier then (manually) computing it.

**Comment by shirouzu** [comment]
Oh...Sorry.
The elapsed time is already displayed as the TotalTime field.

**Comment by therube** [comment]
Heh.  Now don't I feel silly.
Sometimes you can't see the forest through the trees.

Thanks.
