### ISSUE TITLE
Long File Name in an Overwrite Situation, Writes To Unexpected Location

### ISSUE THREAD

**Issue by therube** [FastCopyLab/FastCopy#137]
Long File Name in an Overwrite Situation, Writes To Unexpected Location

This is just something to ponder...

If you have a source filename, with a length of 255 (let's abbreviate to LFN255)
& you did something like:

Source: W:\LFN255
DestDir: .

(with '.' meaning the current working directory, with the intent being to make an "in-place" copy
-however odd that may be...)

That will (most likely) create a copy of W:\LFN255 - but in some unexpected location.

Ordinarily what would happen is that with a filename, say 'testfile', it would be copied, & named like: 'testfile(1)'.

In the case when dealing with LFN255, the file is copied - elsewhere.
Elsewhere may depend on how/where the copy was invoked from.

In a particular case, I was running Everything (search) & used the FastCopy context-menu item to (try to) perform an in-place copy of said LFN255 file.

Result was that the file copy ended up, not anywhere on the source drive (happened to be W:), but instead, in Everything's instalDir, which was on C:.

Obviously a LFN255, with (1) appended, so LFN255(1) (which would be a 258 character filename) is not valid in Windows.

So... what to do?

Simply ERROR, cannot create?

Truncate the output name such that it ends up being LFN255(-3.chars)+(1), so LFN252(1) ?
& if you did the same again, it would be LFN252(2)... ?

So... in general, if filename length >252, an "in-place" copy (however odd _that_ may be), acts oddly.

Granted using FastCopy to make an in-place copy is probably not an expected action.
But, & in particular when dealing with LFN, there aren't too many options out there.
(No COPY program that i know that can do it. So if you can "tweak" something, like FastCopy, to do what you need ;-).)

The above works fine if the filename length is <253, but then you need to know that the length is in fact <253 ahead of time...

---

From a command-line, fcp.exe works as expected, actually, as it fails.

`fcp.exe /force_start=2 "LFN255" /to=.`

"CreateFile(The filename, directory name, or volume label syntax is incorrect.123)"
-That is fine.  At least the file is not copied somewhere unexpected.

**Comment by shirouzu** [comment]
I recommend not to use "." in destdir with the GUI version of FastCopy.
(Current directory of the GUI version of FastCopy, often it will be in unexpected places. it depends on launch program's behavior)
