### ISSUE TITLE
FastCopy location to PATH

### ISSUE THREAD

**Issue by KamikazeePL** [FastCopyLab/FastCopy#138]
Add to installer option to add FastCopy instalation path to environment variable **PATH** so I could start it FastCopy from command line  without full path to EXE file.

Example without PATH I need type full path  to run 
`C:\fastcopy\fastcopy.exe` 
when PATH is setted I run
`fastcopy.exe` and program starts.

**Comment by shirouzu** [comment]
I will consider it.
