### ISSUE TITLE
How to launch FastCopy with a Job settings without execute the Job

### ISSUE THREAD

**Issue by agiudiceandrea** [FastCopyLab/FastCopy#139]
**Question**

It is possible to launch FastCopy specifying a Job with the command FastCopy.exe /job=JOBNAME. In this case the job is immediately executed.
Is it possible to launch FastCopy specifying a Job without the immediate job execution?

**Comment by shirouzu** [comment]
Did you try /no_exec option?
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by agiudiceandrea** [comment]
You are right! It works. I missed that option... Sorry for the noise.
