### ISSUE TITLE
re deldir.bat

### ISSUE THREAD

**Issue by GeorgePP** [FastCopyLab/FastCopy#14]
**Question**
Describe your question.
(Please do not ask anything that you can figure out by experimenting at hand).
Please advise - is this part of FastCopy installation.  Kasperksy Lab Total Security  placed deldir.bat  in restricted applications group. 
**Remarks**
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
What is deldir.bat??

**Comment by GeorgePP** [comment]
Thank you - you have  answered no part of FC .  
Recently as I started FC,  Kaspersky TL warned  Suspicious activity,  deldir.bat  blocked deep level access to a folder that contained FC.exe  ( this is from memory, not exact) I did not respond tried to find deldir.bat, found in C:\Users\GEORGE\AppData\Local\Temp\tlib-4b4fc65632fdbc58.  This happened about three times then Kasperksy  reports  Event: Application Control was triggered  Component: Application Control Result description: Blocked Reason: Rights and placed deldir.bat in restricted applications. When i tried to find it again planning to change bat to txt and read it the folder had dissappeared - not in Recycle Bin or in Quarantine.  I tried to find it in backups 1 and 3 days old - not found. I have given up, I have done scans and nothing reported.

**Comment by shirouzu** [comment]
OK, I see.

**Comment by GeorgePP** [comment]
It happened again a few times. I manged to copy the bat file and renamed as txt -see atached
To me it seems that when I start FC the file  fastcopy_update64.exe  and deldir.bat are created both in their own folders in  C:\Users\GEORGE\AppData\Local\Temp\...   then Kaspersky reports suspicious activity, then if I allow it, or if I ignore it both folders and contents are deleted. If this is an innocent process (? normal or a bug) I could change deldir.bat In Kaspersky Applicaton control to "safe" to stop this appearing.     

[deldir.txt](https://github.com/FastCopyLab/FastCopy/files/7975108/deldir.txt)
![deldir2](https://user-images.githubusercontent.com/16808684/151896016-5ccd4bff-34d1-47ca-b640-3c66e50280ec.png)
:
