### ISSUE TITLE
管理者権限でbatを実行するとFastCopyのウィンドウが表示できない。

### ISSUE THREAD

**Issue by kakogawa** [FastCopyLab/FastCopy#141]
**エラー内容**
管理者権限で実行したbatからFastCopyを実行した時
FastCopyのウィンドウが表示できません。

**スクリーンショット**
![fastcopy2](https://user-images.githubusercontent.com/96918428/205442821-a0866e7f-51ec-4afa-9b7d-9f11a5292bf6.jpg)

赤枠のどこをクリックしてもFastCopyのウィンドウが表示できません。
終了するにはタスクマネージャーからプロセスを終了させなくてはなりません。
ただしコピー処理はちゃんと実行されているようです。

**再現方法**
下記のbatファイルを管理者権限で実行
FastCopy.exe "test" /to="test2"

管理者権限でない場合はFastCopyウィンドウがちゃんと表示できています。

**バージョン・環境**
Windows 10 64bit
FastCopy ver 4.2.1

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
何らかの対処を入れておきます。
