### ISSUE TITLE
request: filter saved between restarts

### ISSUE THREAD

**Issue by alanbork** [FastCopyLab/FastCopy#142]
Just like the source and dest are saved to the registry/ini file when you quit, I wish the filter settings were also saved. I need a fairly complex filter to block the recycle bin etc, and it's beyond what I can type from memory. Actually, it would be great if including that was just a checkbox setting somewhere, so that the filter box wasn't already full with the mandatory minimum filtering options for backing up a hard drive. But just saving the last filter would be sufficient.

**Comment by shirouzu** [comment]
??
It has already been implemented.
You can see the filter history in the pull-down list.

**Comment by alanbork** [comment]
Good point. Wasn't obvious given that the other two UI's that save history automatically show their last contents on restart.
