### ISSUE TITLE
How can you Include or Exclude a File in a Copy 

### ISSUE THREAD

**Issue by sparks79** [FastCopyLab/FastCopy#144]
**Question**I want to Copy My User Folder from My C:/  Drive to a Portable SSD.
The User Folder has the most Common Folders that I need, Like Documents, Pictures, music etc.
But I want to Exclude Other Folders and Files that I don't need.
How can I do that
Describe your question.
(Please do not ask anything that you can figure out by experimenting at hand).

**Remarks**
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
I'm not sure, but the following may help.
https://fastcopy.jp/help/fastcopy_eng.htm#filter
