### ISSUE TITLE
どうか機能実装の検討をお願いします  

### ISSUE THREAD

**Issue by fanz010** [FastCopyLab/FastCopy#146]
**機能リクエスト内容**
内容を記述します。
<html>
<body>

このソフトを使い始めたいと思っていますhush計算してベリファイ機能はありますねHUSHが違う同一名ファイルも時間やサイズの誤差がちいさすぎてうわがきされてしまうという弱点があるようです

コピーや移動の際に日付とサイズしかみていないようなのでファイル名が一緒ならHUSHで同一かいなか判断してダイアログをだす もしくはちがうならそれぞれコピーや移動していただきたいです

 掲示板をみたのですがこの部分がきちんとしていないために
ファイルを誤って上書きし喪失してる人たちが続出していたようです

コピーや移動をするまえに怪しいファイル元先両方をハッシュチェックしてください
ファイル名でまずしらべて ファイルサイズ 日付の順でしらべる
サイズが完全一致なのにファイル名が違う場合もハッシュチェックしたりしてダイアログで音出しながら提示

考え方が逆でファイル名とサイズが完全一致していても念のためハッシュチェックする
ほうがよいかとおもいます

あるいはそこをふくめた自動処理を設定でできるようにしてほしいです
FFCはダイアログがでますが音が出ないのが欠点です
そこでハッシュチェックしていればファイル喪失リスクはかなりさけられます

現状コマンドラインもMOVEは上書きしかないようですね

移動処理も移動元ファイルをOSのゴミ箱へ移動できるようにしていただけませんか？もとにもどすこともできたほうが安全です今のままだと不安が大きくて扱えないのでFFCの方を利用するかもしれません

またUIですが画面中央の結果についてはフォントを15ポイントまで大きくすることができるようです ソフト内の他のフォントも同時に変更してまたポイントももっと大きくできるようにしていただきたいです 文字が小さすぎて見づらいのですどうか機能実装の検討をお願いします
--

</body>
</html>
**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
すみませんがポリシーが違いすぎるので、別のソフトをお使いいただくのが良いと思います。
