### ISSUE TITLE
How do I tell FC to MOVE (and not COPY) a file?

### ISSUE THREAD

**Issue by pstein** [FastCopyLab/FastCopy#148]
How do I tell FC to MOVE (and not COPY) a file?

**Comment by a-raccoon** [comment]
You cannot.  FastCopy performs actual COPY (Duplication) operations, or Move (Duplication + Deletion) operations across two volumes, but not Move(Rename) operations on the same volume.  This is a hard design limit.

If you only need to move (rename) a file on the same volume (drive letter), then use MS Windows built-in Move.
