### ISSUE TITLE
設定がオフでも実行前に確認ダイアログが表示される

### ISSUE THREAD

**Issue by Moyashi-M** [FastCopyLab/FastCopy#150]
**エラー内容**
右クリックメニュー、もしくはドラッグ＆ドロップメニューから実行した際、
設定の「その他」の「実行前に確認ダイアログ」のチェックをオフにしていても確認ダイアログが表示されてしまいます。

**再現方法**
右クリックメニュー、もしくはドラッグ＆ドロップメニューより
「コピー」「削除」「移動」を実行

**コマンドライン・オプションや各種設定**
デフォルトの設定でも発生しました。
コマンドラインは使用しておりません。

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :4.2.1
OS ver:Windows10 Pro

**スクリーンショット**
![image](https://user-images.githubusercontent.com/112129659/213638743-d3aaf8a3-771d-4863-8cff-d125edab2a55.png)

![image](https://user-images.githubusercontent.com/112129659/213638835-f9ad6f3a-a51b-4db7-b95d-7c908029219c.png)

![image](https://user-images.githubusercontent.com/112129659/213638898-66c88aef-4a8a-4d98-95a8-eaf5ff5c8579.png)

**Comment by shirouzu** [comment]
シェル拡張による実行では、シェル拡張タブに「コピー…を確認しない」という項目があるので、それもチェックしてください。
![image](https://user-images.githubusercontent.com/1759911/213690485-6e310ea8-021e-49c1-9ade-fe1f78c5d8d8.png)

**Comment by Moyashi-M** [comment]
正常動作確認いたしました。
申し訳ございません。

恥ずかしながら
複数回目を通したにもかかわらず、なぜか毎回見逃してしまっていたようです。
