### ISSUE TITLE
UIフォントの変更

### ISSUE THREAD

**Issue by jarupxx** [FastCopyLab/FastCopy#151]
**機能リクエスト内容**
日本語UIフォントをメイリオや游ゴシック変更してほしい
英語UIでは問題ないのですが、日本語UIでスケーリングを変更するとテキストが欠けてしまいます
フォントをメイリオや游ゴシックに変更して頂けるとこの問題が解決します

**補足**
公式
![MS UI Gothic](https://user-images.githubusercontent.com/20138367/213906570-0babb6e2-2ff2-4c33-910d-b6d67d620347.png)
Meiryo UIに改造
![Meiryo UI](https://user-images.githubusercontent.com/20138367/213906569-fbd2ebb0-2a95-4f67-9f52-6ad2a2751bcb.png)

**Comment by shirouzu** [comment]
なるほど。
FastCopyでは MS Shell Dlg 2 という、MS推奨のデフォルトの抽象？フォント（ロケールによって変化）にしていますが、イマイチみたいですねぇ…ちょっと考えてみます。
https://learn.microsoft.com/ja-jp/windows/win32/intl/using-ms-shell-dlg-and-ms-shell-dlg-2
