### ISSUE TITLE
Save selected operation mode between startups

### ISSUE THREAD

**Issue by mrc16** [FastCopyLab/FastCopy#152]
**Describe the solution you'd like**

Every time I run FastCopy, I have to choose the option I need (Sync). I would like the selected value to be saved.

**Comment by shirouzu** [comment]
Please set [main] default_copy_mode=4 in fastcopy2.ini

**Comment by mrc16** [comment]
> Please set [main] default_copy_mode=4 in fastcopy2.ini

Thanks!
