### ISSUE TITLE
The server does not have enough storage space to process this command 1130

### ISSUE THREAD

**Issue by baldycoder** [FastCopyLab/FastCopy#153]
**Question**
Describe your question.
When I used FASTCOPY to synchronize a file of around 400G, I got an error: WriteFile（the server did not have enough storage space to process this command 1130）. I'm pretty sure the destination and source disks are sufficient. This problem comes up occasionally. Do you have any analytical thoughts on this question?
Thank you for your answer.
 

**Remarks**
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
Please use this format.
https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=
