### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by namoen0301** [FastCopyLab/FastCopy#155]
**Describe the solution you'd like**
Have a native Windows ARM64 build of FastCopy.

**Additional context**
Currently run FastCopy on a ARM64 Windows host is running the x86 emulation, Having a native ARM64 build will definitely speed things up significantly.

I have a arm64 device so can test and give feedback.

**Comment by shirouzu** [comment]
It is interesting, but will consider if the number of users increases.
