### ISSUE TITLE
"confim in copy(drag&drop)/move/paste" sometimes not working

### ISSUE THREAD

**Issue by tulei770415** [FastCopyLab/FastCopy#157]
Hello, I used fastcopy 4.2.2, "confirm in copy(drag&drop)/move/paste" sometimes not working, for example: I setting "confirm in copy(drag&drop)/move/paste" in menu, and I plug usb drive and move file from usb drive to computer, it don't need to confirm, after this move file from computer to usb drive, it also don't need confirm, this issue don't happen every time, I encounter about 5/6 times, I think this is bug.

**Comment by shirouzu** [comment]
It could not be reproduced at hand.
Are there any conditions for reproduction?

**Comment by tulei770415** [comment]
I tried several times, when plug usb drive to computer, then move file from usb drive to computer, sometimes it still not need confirm, I use netac usb3.0 flash usb drive(now I use fastcopy 4.2.2, it update from 3.xx  version).

**Comment by shirouzu** [comment]
The reproduction conditions and reproduction procedure are not clear and cannot be corrected.
Please report back when you know them.

**Comment by tulei770415** [comment]
Hello, I reproduced this issue and recorded a video, please review attach.
[video and log.zip](https://github.com/FastCopyLab/FastCopy/files/10868010/video.and.log.zip)

**Comment by shirouzu** [comment]
You seem to be doing shell extensions for the current user as well as shell extensions for globals.
Elevate FastCopy, open the shell extension settings with administrator rights and turn it off.

**Comment by tulei770415** [comment]
Thanks for your reply, according to your requirement, no problem after operation, if this problem happen again, I will feed back.
