### ISSUE TITLE
FAT32の最大ファイルサイズを超えたファイルのコピーで領域が足りないと表示される

### ISSUE THREAD

**Issue by hatachu-jp** [FastCopyLab/FastCopy#159]
**エラー内容**
問題の内容を記述
SetEndOfFile(ディスクに十分な空き領域がありません。112) : E:\TOSHIBA dynabook R734M Win10 本部用\R734M-21H2Honbu.TIB

**再現方法**
再現手順を列挙
FAT32 でフォーマットされたＵＳＢメモリに１８ＧＢのファイルをコピーしようとしたところ、領域が足りないと表示されまぎらわしかったので、報告します。ファイルシステムの制限なのに空き領域がありませんと表示され、まぎらわしかったです。ＮＴＦＳでフォーマットし直してコピーはしました。

**コマンドライン・オプションや各種設定**
コマンドライン・オプションや標準から変更している設定項目などを記述

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : 4.2.2
OS ver: Windows 10 Pro 22H2 64 Bit

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット

**Comment by shirouzu** [comment]
検討しておきます。
ただこれ、Windows側が出しているエラーコードをそのまま表示しているのですよね。
