### ISSUE TITLE
Output hash files and check hash files

### ISSUE THREAD

**Issue by ckw-123** [FastCopyLab/FastCopy#16]
It would be great if FcHash could output hash files and check hash files specified by command line.

**Comment by shirouzu** [comment]
Yes, it is good idea.

**Comment by malvarenga123** [comment]
I would also like to request an option to set the output format to:
```
hash1hash1hash1hash1 *filename1.ext
hash2hash2hash2hash2 *filename2.ext
```
Which is used by most hashing programs.

**Comment by kyunjingan** [comment]
It would be nice to have something like this.
You can compare the current hash value with the hash value in the AltStream created by fastcopy.
Try it to see if you have a corrupt file!

First of all
☑Add verifyInfo.(AltStream(:fc_verify))with hashinfo etc)

and copy all files to an empty HDD
a.txt
a.txt:fc_verify:$DATA
It's trivial if there are no pairs of

https://1drv.ms/u/s!An5FOcISHAY8luZYb8xnHmT65Mtc5A?e=Sf0Q0y
fccheck.zip Download！
