### ISSUE TITLE
fcp.exe /logfile

### ISSUE THREAD

**Issue by mattia72** [FastCopyLab/FastCopy#160]
**Question**
If I use fcp.exe with parameter /logfile like this:
    
    fcp.exe /cmd=sync /logfile=dest\fc.log src /to=dest
 
I get two identical log files in **Log** and in **dest** folder.
Is there a way to avoid creation of the default log in **Log** folder?

**Remarks**
I installed FastCopy with [scoop](https://github.com/ScoopInstaller/Scoop) so my Log folder is a symlink from FastCopy install folder to scoop persisted FastCopy settings.

**Comment by shirouzu** [comment]
What is the Log folder?
it is file log?
![image](https://user-images.githubusercontent.com/1759911/222164836-6654e8ba-22d4-4853-962d-77848b4b2087.png)

**Comment by mattia72** [comment]
I want to set the log folder to the destination folder: `dest`.
My Log settings in GUI affects the command line switches also?
![image](https://user-images.githubusercontent.com/2544095/222400515-33d3788f-1044-411c-94ae-504ad4bda97e.png)

**Comment by mattia72** [comment]
I want to set the log folder to the destination folder: `dest`.
My Log settings in GUI affects the command line switches also?
![image](https://user-images.githubusercontent.com/2544095/222400515-33d3788f-1044-411c-94ae-504ad4bda97e.png)

**Comment by shirouzu** [comment]
filelog name can be specified /filelog option.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by mattia72** [comment]
Ok, thanks. I was a little bit confused with the two parameters `/logfile` and `/filelog`, 
but now I think, it's clear.
