### ISSUE TITLE
Update the website it looks old

### ISSUE THREAD

**Issue by chrisribe** [FastCopyLab/FastCopy#161]
**Describe the solution you'd like**
The current website looks so old and out of date. It should be updated to look better. 
It's scares off users from downloading thinking it's hacky / super old / probably does not work.

This application is so useful and much better in speed than windows explorer.

**Additional context**
![image](https://user-images.githubusercontent.com/1999791/222159529-148a909c-9790-4f56-b26a-1a2ae279c283.png)

**Comment by shirouzu** [comment]
For example, what designs do you feel are outdated?
Are there any websites with a design you would recommend?

**Comment by chrisribe** [comment]
Anything really would do, something less year 2000. 
Right now it feels like it was put together a long time ago and not maintained.

These are just examples of "updated" styles.
- https://lawsofux.com
- https://dribbble.com/shots/4689117-Bluebell-App-Showcase
- https://dribbble.com/shots/20508192-SCOOTA-Scooter-Product-Website
- https://httptoolkit.com
- https://www.espruino.com
- https://commercejs.com

**Comment by chrisribe** [comment]
Hope that helps to inspire you :)

**Comment by shirouzu** [comment]
Thank you.
