### ISSUE TITLE
移動や差分、コピーで「サイズが小さくなった」のみ「日付が新しい場合」のみのモードがほしいです。

### ISSUE THREAD

**Issue by officecab** [FastCopyLab/FastCopy#163]
**機能リクエスト内容**
　こんにちは
いつも利用させてもらっております。

差分、コピー、同期で、「サイズ・日付」が選択できるのですが、
例えば、ファイルサイズが小さく（大きく）なったときだけとか、
日付が新しい（古い）ときだけとか設定できると非常に助かります。

そうすることで、間違った上書きのミスが減るかと思います。
できれば、サイズと日付の組み合わせが選べて設定できると非常によいです。
（日付は変わらないけど、サイズのみ変更等）

それと、こちらは可能かどうかわかりませんが、
デジカメのExifの撮影日での判断などもできると便利かもしれません。

よろしくお願いします

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
検討しておきます。
