### ISSUE TITLE
ver.5.0 not able to install

### ISSUE THREAD

**Issue by ageback** [FastCopyLab/FastCopy#166]
1. Run FastCopy5.0.0_installer.exe
2. Check "I agree to the license"

"Next" button is still disabled, not clickable.

![图片](https://user-images.githubusercontent.com/1097481/231612557-044b2505-1e32-4733-9ae4-cef5a244f8cd.png)

**Comment by shirouzu** [comment]
Oh...

Please use command-line install with /silent.
> FastCopy5.0.0_installer.exe /silent

more options be shown with /h option.

**Comment by ageback** [comment]
May I ask what's wrong with the Next button?

**Comment by shirouzu** [comment]
I do not know the cause.
Since it does not occur in the test with Win7 to Win11 at hand.

**Comment by shirouzu** [comment]
Please try this.
https://fastcopy.jp/archive/special/FastCopy5.0.3r2_installer.exe
