### ISSUE TITLE
Windows11、シェル拡張

### ISSUE THREAD

**Issue by XERE** [FastCopyLab/FastCopy#169]
**エラー内容**
5.0.2のシェル拡張で、実行ファイルへのショートカットを右クリックし、従来のコンテクストメニューを表示させるとfastcopy、とだけ書かれたメニューが二つあります

**再現方法**
Windows11で、新しいバージョンのシェル拡張を使っている場合で、デスクトップ上にある実行ファイルへのショートカットファイルを右クリックし、さらに従来のコンテクストメニューを表示させる

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :5.0.2
OS ver:Windows11 22H2

**Comment by shirouzu** [comment]
うーん、手元では再現しないですね。
シェル設定で、サブメニューは利用していますでしょうか？
（そもそも、Win11ではトップレベルにメニューを出しているので、従来コンテキストメニュー側には何も出さないほうがスマートかな）

**Comment by shirouzu** [comment]
下記に、従来コンテキストメニューには FastCopyメニューを出さないバージョンを置いておきましたので、こちらで確認してみてもらえますか？
ただシェル拡張DLLをExplorerが開いたままだと思ううので、インストール前にシェル拡張を一旦無効化した上で、Explorerを再起動する or 再ログインする、などした上でインストールしてみてください。

https://fastcopy.jp/archive/special/FastCopy5.0.2r1_installer.exe

**Comment by XERE** [comment]
![image](https://user-images.githubusercontent.com/1268711/232218665-93cdf9e3-0ae1-4536-b669-3eb59c255904.png)
5.0.2r1を試してみたのですが、このようなメニューになります。
サブメニュー化を有効にした場合はこれが出なくなりますが、今度はモダンコンテクストメニューに何も表示されません。
![image](https://user-images.githubusercontent.com/1268711/232219159-cfafe910-d2d0-4b21-9cbf-1b341efad974.png)


従来のコンテクストメニューの方が便利で一発で従来のコンテクストメニューが出るようにしている方もいますし、

個人的にはモダンコンテクストメニューはシンプルな形に保ちたいので、
従来のコンテクストメニューどちらを有効にするかが選べたほうがありがたいかもしれません。

**Comment by shirouzu** [comment]
正しくシェル拡張DLLが置き換わっていない気がします。
もう一度、再ログイン or リブートしてみてもらえますか？

**Comment by XERE** [comment]
5.0.2r1をシェル関連付け解除＆再インストールと再起動％シェル関連付け、をしてみたのですが、
やはり同じです。
一度アンインストールしてみてから再度やってみます。

なお、特権モードではなくユーザー権限でシェルには関連付けています。

それから、fastcopyのインストール先のフォルダのNTFSのセキュリティ権の設定で
不思議な設定がされているのですが、こちらは正常でしょうか issueを分けた方がよかったらそうします
![image](https://user-images.githubusercontent.com/1268711/232262597-edc0d440-455d-4960-ad64-69ce2d7b5b9c.png)
![image](https://user-images.githubusercontent.com/1268711/232262650-f1772126-fe69-449e-90c3-f47f0062080c.png)

**Comment by XERE** [comment]
再度再インストールし、Explorerを強制再起動してやってみたのですが、

サブメニュー化をONの場合
ショートカットファイルを右クリックする
モダンコンテクストメニュー→FastCopyがある、サブメニュー化できている
クラシックコンテクストメニュー→FastCopyがいる、サブメニュー化できている
フォルダを右クリックする
モダンコンテクストメニュー→FastCopyがいる、サブメニュー化できている
クラシックコンテクストメニュー→FastCopyの項目がない

サブメニュー化をOFFの場合
フォルダ
モダンコンテクストメニュー→FastCopyいる
クラシックコンテクストメニュー→FastCopyの項目がない

exeファイルへのショートカット
モダンコンテクストメニュー→FastCopyいる
クラシックコンテクストメニュー→FastCopyがふたつある
![image](https://user-images.githubusercontent.com/1268711/232263053-73289e64-392d-41cf-a31f-8d123ad62792.png)


という状況です。
クラシックコンテクストメニューにFastCopyが一切表示されない場合がある、という状況が起こりました。

ショートカットのファイルについては、exeファイルから手動インストールなどでショートカットを作ったものと、
インストーラーによって作られたショートカットでは挙動が違うように思います。

**Comment by shirouzu** [comment]
詳細なレポート有難うございます。
なにぶん、こちらで再現できないのが厳しいところです。

>クラシックコンテクストメニューにFastCopyが一切表示されない

が r1 での動作変更点でした。
ただ、それでも状況により、FastCopy というエントリが表示されることがあるわけですね。
このエントリの正体がよくわからないですが、このエントリをクリックした場合、どういった動作が起きるのでしょうか？

**Comment by XERE** [comment]
このふたつあるfastcopyをクリックすると
ひとつはショートカット先のパスが指定されたfadtcopyが開きます
もうひとつはショートカットのリンク先のパスが表示され、削除するかどうか聞くダイアログが表示（fastcopyで削除するコンテクストメニューと同様）
が起動します。

このあたり、レジストリを弄れば表示させないようにできそうな気もしますのでちょっとツールをつかってらしらべてみます。

クラシックコンテキストメニューにはサブメニューで表示させずモダンではサブメニューにしたい
というようなこともできるといいですね。

**Comment by XERE** [comment]
{CF6181BA-D469-441A-BE79-BB70A2EC3D0B} というキーワードで検索すると、
ところ各所にレジストリエントリがあって
fastcopyMenuFlags2というキーはbff18fffになっていますね
コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\*\shellex\ContextMenuHandlers\FastCopyUser

コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\CLSID\{CF6181BA-D469-441A-BE79-BB70A2EC3D0B}
コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\Directory\Background\shellex\ContextMenuHandlers\FastCopyUser


今回問題なのは
コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\Folder\shellex\ContextMenuHandlers\FastCopyUser

コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\InternetShortcut\shellex\ContextMenuHandlers\FastCopyUser

コンピューター\HKEY_USERS\S-1-5-21-2418352930-3577474244-349985747-1002\Software\Classes\lnkfile\shellex\ContextMenuHandlers\FastCopyUser

などが今回のと関係ありそうです。

関係なさそうな情報ならごめんなさいね

**Comment by shirouzu** [comment]
再現環境が作れたので、次のバージョンで何らかの対処を入れておきます。
詳細なレポートありがとうございました。
