### ISSUE TITLE
FastCopy 4.02 Exception

### ISSUE THREAD

**Issue by r-finger** [FastCopyLab/FastCopy#17]
FastCopy 4.02 has been freezing solid after running for a short while. Several tasks are running on one Windows Server 2016 1607 machine and all the tasks lock up seemingly simultaneously. A fastcopy_exception.log/.dmp was generated.

This same thing happened on another source and target machine pair on another host running FastCopy 4.0 but I did not retain the fastcopy_exception files in that case because it was the first time it happened. Sorry.

Source and destination servers and host running FastCopy were all rebooted and the problem persisted.

There was previously no issue using 3.92 with this same configuration. The issue seems to affect one particular target server (of two target servers) in the case where the exception log was generated.

To reproduce:
- Run several simultaneous tasks (12 or so) from various sources to two targets
- Wait up to a few hours until the UI seems to freeze
- Note that the source and target servers function fine
- Look for a fastcopy_exception bundle

Command Line:
C:\PS\FastCopy.exe /cmd=sync /no_ui /balloon=FALSE /force_start /force_close /reparse=FALSE /stream /skip_empty_dir=FALSE /exclude=".TemporaryItems\";".Trashes\";"DfsrPrivate\";"System Volume Information\";"*.tmp";"~*.*";"autorun.inf";"desktop.ini";"hiberfil.sys";"pagefile.sys";"Thumbs.db" /logfile="C:\Temp\Logs\FastCopy-MigrationLogs\KOQIBNK 2022-01-27 08.10'16(-05) 'Split from Parent Task ISIPRD' (FastCopy)\KOQIBNK 2022-01-27 08.10'16(-05) 'Split from Parent Task ISIPRD' (FastCopy) TARGETSERVER1.log" "\\sourceserver\C$\SamplePath\Subfolder\Target" /to="\\TargetServer1\TargetShare\SamplePath\Subfolder\Target"

Fastcopy 4.02
Windows Server 2016 v1607

Sent fastcopy_exception to exp@fastcopy.jp

**Comment by shirouzu** [comment]
Please send the fastcopy_exception.dmp/log to exp@fastcopy.jp

**Comment by r-finger** [comment]
Sent. Thank you for the quick response!

**Comment by shirouzu** [comment]
I am analyzing, but it seems to be a strange situation where the problem file has zero attributes and cannot be opened.

**Comment by shirouzu** [comment]
Please try this. (prevent to exception even if attr is zero)
[FastCopy4.0.2d_installer.zip](https://github.com/FastCopyLab/FastCopy/files/7951669/FastCopy4.0.2d_installer.zip)

**Comment by r-finger** [comment]
I am trying this now and will let you know. Thank you for everything you do!

**Comment by r-finger** [comment]
The problem has occurred again. A new fastcopy_exception has been sent to
***@***.***

**Comment by shirouzu** [comment]
It is strange in many ways.
By the way, can you answer the following questions?

> Is source filesystem special?

**Comment by shirouzu** [comment]
OK, thank you.

In v4.0.2d, It appears to be crashing right from the start.
Does this happen every time you use v4.0.2d?

**Comment by r-finger** [comment]
No, in the list of almost 400 FastCopy jobs that are executed, nearly half
completed with 4.02d before the crash occurred according to my logs

**Comment by shirouzu** [comment]
Thank you.
However, I can't get a dump file, so I can't explore the cause in earnest.

I am attaching v4.0.2d2, which is a version of the compiler closer to v3.92.
Please try to get it working.
[FastCopy4.0.2d_installer.zip](https://github.com/FastCopyLab/FastCopy/files/7959106/FastCopy4.0.2d_installer.zip)

**Comment by shirouzu** [comment]
Thank you.
However, I can't get a dump file, so I can't explore the cause in earnest.

I am attaching v4.0.2d2, which is a version of the compiler closer to v3.92.
Please try this.

P.S I mistaken attach v4.0.2d(old ver) instead of v4.0.2d2. Please use this.
[FastCopy4.0.2d2_installer.zip](https://github.com/FastCopyLab/FastCopy/files/7959141/FastCopy4.0.2d2_installer.zip)

**Comment by r-finger** [comment]
Thank you, understandable. I need to run with v3.92 to complete this job,
which will be a couple days. After that, I will try this new version. I
appreciate your help.

**Comment by CrackMd5** [comment]
Problem still existss with v4.0.2d2. Please check the files:
[dmp_log.zip](https://github.com/FastCopyLab/FastCopy/files/7965241/dmp_log.zip)

First, clear all files in dest folder. Then run this command:
` d:\tools\fastcopy\fastcopy.exe /open_window /estimate /no_confirm_stop  /cmd=diff /force_close /include="*.config;*.cmd;*.urls;*.ini;*.exe;*.dll"  /reparse=FALSE  d:\run t:\run-dict  /to=t:\temp\config`

Problem displayed.

![ff](https://user-images.githubusercontent.com/45376821/151686033-aa228120-8959-4755-8e97-57ebe6d401dd.jpg)

But the follow commands will work OK:
` d:\tools\fastcopy\fastcopy.exe /open_window /estimate /no_confirm_stop  /cmd=diff /force_close /include="*.config;*.cmd;*.urls;*.ini;*.exe;*.dll"  /reparse=FALSE  d:\run   /to=t:\temp\config`

` d:\tools\fastcopy\fastcopy.exe /open_window /estimate /no_confirm_stop  /cmd=diff /force_close /include="*.config;*.cmd;*.urls;*.ini;*.exe;*.dll"  /reparse=FALSE   t:\run-dict  /to=t:\temp\config`

If not del dest files , All work OK.


...
[md5](https://www.cmd5.org)

**Comment by shirouzu** [comment]
Thank you for your report. I will analyze it.
(Perhaps it is another problem)

**Comment by shirouzu** [comment]
We release v4.0.3.
Please use v4.0.3 instead of v4.0.2d2. > r-finger san.

By the way, the problem seems to relate BackupRead/BackupWrite API.
The APIs are only used in ACL/AltStream option.
Is it possible to test without using /stream?

**Comment by r-finger** [comment]
Sorry, I was not able to test without /stream. However, after upgrading to v4.0.3, the job has been running without creating an exception, and I believe it is past the point where it was previously stopping.

If anything changes in this regard, I will reply. Thanks again for all you do!

**Comment by shirouzu** [comment]
Thank you for your report.
I hope nothing goes wrong, but please let me know if anything does.

**Comment by CrackMd5** [comment]
Thank you. Everything is OK now.
