### ISSUE TITLE
コンテキスト キー 競合

### ISSUE THREAD

**Issue by BrufordY** [FastCopyLab/FastCopy#170]
Fastcopyのコンテキストの貼り付けはキーが"P"で標準の貼り付けと同じなのでワンキーで選択できません。
コンテキストのキーを被らないよう変更出来るとありがたいです。

**Comment by BrufordY** [comment]
![2023-04-16_121704](https://user-images.githubusercontent.com/130877369/232264562-f2a47570-48d3-4d64-bef7-088595529f3e.jpg)

**Comment by BrufordY** [comment]
(P)が三つもあるのでワンキーで動作させられません。

**Comment by shirouzu** [comment]
検討しておきます。
