### ISSUE TITLE
Setup 5.0.3:  Frame caption is in Japanese language (インストールモード)

### ISSUE THREAD

**Issue by salemjo** [FastCopyLab/FastCopy#171]
Thanks for update 5.xx

Frame caption (Installation mode) is in Japanese language (インストールモード)

**To Reproduce**
Run FastCopy5.0.3_installer.exe
Accept license and click next
![FastCopy5 0 3_installer](https://user-images.githubusercontent.com/104968650/232470799-c55e4c13-f88e-443c-97fe-3878f584ce53.jpg)

**Comment by shirouzu** [comment]
Thank you for your report.
I will fix it in the next version.
