### ISSUE TITLE
v5 - unable to install

### ISSUE THREAD

**Issue by jerrymessina** [FastCopyLab/FastCopy#172]
I'm unable to install V5.0.3
I accept the terms but the 'next' button is never enabled.

I saw the previous post on this and tried installing via command prompt with '/silent', but the program immediately closed without installing.

**Comment by shirouzu** [comment]
Hum...What is your OS version?

Please try in command prompt
 > winget install fastcopy

**Comment by shirouzu** [comment]
Please try this?
https://fastcopy.jp/archive/special/FastCopy5.0.3r1_installer.exe

**Comment by jerrymessina** [comment]
sorry, I forgot to mention...  win7 x64

I tried FastCopy5.0.3r1_installer.exe with the same result

**Comment by shirouzu** [comment]
Humm.....
Could you try this?
https://fastcopy.jp/archive/special/FastCopy5.0.3r2_installer.exe
If it is failed, please run it with /AGREE_LICENSE option.

**Comment by jerrymessina** [comment]
That worked. It allowed me to install it normally (after checking "I agree" the Next button became enabled).
I didn't have to try to use the command prompt method or /AGREE_LICENSE.

Thanks!

**Comment by shirouzu** [comment]
I see, thank you!
