### ISSUE TITLE
PreAllocate for speed (privilege) setting NOT works properly

### ISSUE THREAD

**Issue by pks1217** [FastCopyLab/FastCopy#173]
OS: Windows 11 22H2
FastCopy version: v5.0.3

I've configured "PreAllocate for speed (privilege)" in "Main Settings\Copy Options" as follows.
None(default) -> Always
![스크린샷 2023-04-18 184337](https://user-images.githubusercontent.com/47659740/232742267-f6e123af-4d3a-4702-82dc-b06a8302059a.png)

But, when I open "Copy Options" settings again, the manual tweak as above restores to default.
![스크린샷 2023-04-18 184406](https://user-images.githubusercontent.com/47659740/232742439-13f7806c-d1c8-4868-8a1f-18e76ba7cb4c.png)

What's wrong with my handling of the settings?
I've loaded FastCopy as administrator privilege as below.
![스크린샷 2023-04-18 184229](https://user-images.githubusercontent.com/47659740/232742884-d6215bdc-3764-4793-a57c-a9a5a1cab378.png)

p.s.)
I still have no idea what "privilege mode" means.
Can you explain it in a more easy way, plz?

**Comment by shirouzu** [comment]
Thank you for your report.
I will fix it in the next release.
P.S "privilege mode" means Admin mode.
