### ISSUE TITLE
サイレントデータ破壊されたファイルのコピー時にエラーを吐く

### ISSUE THREAD

**Issue by jarupxx** [FastCopyLab/FastCopy#176]
**機能リクエスト内容**
ベリファイ情報を付与したサイレントデータ破壊されたファイルをコピーするとエラーもなくコピーされ、ベリファイ情報が破壊された情報に更新されてしまう。
そうならないようにエラーを吐く機能をリクエストしたい。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
検討しておきます。

**Comment by jarupxx** [comment]
ハッシュが無く破損か検証しようがない時代が長く続きましたが、Fastcopyの記録によって後から検証できるようになりました。それ自体画期的ですが、リアルタイムで得られればFastcopyを通してサイレントデータ破壊を残さない環境に進化します。
前向きに検討くださりありがとうございます。
