### ISSUE TITLE
FAST COPY KEYBOARD SHORTCUT

### ISSUE THREAD

**Issue by hashem1000** [FastCopyLab/FastCopy#177]
Hello, 
Thanks for FastCopy. 
 I have a question about FastCopy.
i previous Versions, I just type a 's' in drop-down menu and pick 'sync (size/update)' option.
in new versions it is not possible and only may be selected by mouse.
I recommend to have a shortcut key for all commands (e.g. alt+s for sync... and so on)
thank you.
best regards, 
Hashem Pakdel from Iran

**Comment by shirouzu** [comment]
The implementation of pull-down menus has replaced combo boxes as menus, and their realization is not easy.
I will consider it.

**Comment by hashem1000** [comment]
yes. exactly. thank you for yr consideration.
