### ISSUE TITLE
Check mark to the left of the selected job is missing in some installations

### ISSUE THREAD

**Issue by srcher** [FastCopyLab/FastCopy#178]
**Question**
Windows 7 or 10:
In some installations the check-mark to the left of the selected job is missing. Fastcopy executes the selected job, but with many items in the jobs list, the user can become doubtful about which job was selected and executed. In this respect the check mark is important. 

**Remarks**
I believe all installations I did under win xp did show the check mark. With respect to win 7 or 10, I have not been able to detect any pattern with respect to which installations that show the check mark and which that do not.

**Comment by shirouzu** [comment]
It could not be confirmed at hand.
Can you explain with a screenshot?

**Comment by srcher** [comment]
Hello, sorry for a belated response. It is not so easy to document non-existent check mark by way of a picture[!]. Suffice it to say that after having gone to JobMng(J) and clicked on a job in the list in order to select it, there is no check mark in the left margin at the line of the job.
