### ISSUE TITLE
SMB Multichannelへの設定について

### ISSUE THREAD

**Issue by nomadm4** [FastCopyLab/FastCopy#179]
**質問**
NASへの書き込みで1Gbpsを2本束ねて使用しております。
Windowsでの通常コピーでは約200MB/sの速度なのですが、FastCopyでは80MB/s前後となります。
何か設定が必要な項目はありますでしょうか。

**備考**
![FastCopy](https://user-images.githubusercontent.com/12942602/234151286-93113252-45f8-4a53-8432-d4bb7eef0efb.png)
![WinCopy](https://user-images.githubusercontent.com/12942602/234151290-135f050f-f24c-41af-adc8-ee37750a5bf8.png)

**Comment by shirouzu** [comment]
スピード設定が「Auto Slow」になっていますが、これを「Full Speed」に変えてみて下さい。
それから、I/O設定画面をキャプチャしてみてもらえますか？

**Comment by nomadm4** [comment]
迅速なご回答ありがとうございます。
スピード設定を「Full Speed」へ変更したところ期待通りの速度が出ました。
I/O設定は特にいじっておらず初期値のままです。
ありがとうございました。

![FastCopy](https://user-images.githubusercontent.com/12942602/234153107-145fc975-7132-439a-a2d3-494efca2aaf2.png)
![IO](https://user-images.githubusercontent.com/12942602/234153110-edf53b74-f0cb-4916-a851-89d1d26d2e61.png)

**Comment by shirouzu** [comment]
それはなによりでした。
