### ISSUE TITLE
Ver.5への自動アップデート後にVer.4へダウングレードしての使用について

### ISSUE THREAD

**Issue by YOFWIKE** [FastCopyLab/FastCopy#180]
**質問**
いつも大変便利に使用させていただいております。ありがとうございます。
本日FastCopyを起動しましたところ自動アップデートがデフォルトの有効のままであったためVer.5系にアップデートされました。
その後現状有償のVer.5 の利用は見送っておるため、アンイストールしVer.4系にて再度インストールを行いました。

御社サイトよりVer.4以下は無償利用継続という理解の元、自動アップデートが生じたPCにおいては
同様の処理にてVer.4を継続利用させていただいても問題ございませんでしょうか。

アップデートの際に弊社セキュリティ検知システムにて「Anomalous Rundll32 Execution」として検知されましたため
引き続きライセンス違反がないように使用させていただきたく投稿させていただきました次第です。
（もちろん過去バージョンも有償化の際はそれに従い、利用停止や有償版導入を実施致します）

お忙しい中お手数ですが宜しくお願い致します。

**Comment by shirouzu** [comment]
> 御社サイトよりVer.4以下は無償利用継続という理解の元、自動アップデートが生じたPCにおいては
> 同様の処理にてVer.4を継続利用させていただいても問題ございませんでしょうか。

はい、問題ありません。
（なお、v4系はサポートやBugfixが提供されない点にはご注意ください）

**Comment by YOFWIKE** [comment]
迅速なご回答誠にありがとうございます！
サポート/Bugfixにつきましてもご案内ありがとうございます。
留意の上使用させていただきます。
