### ISSUE TITLE
Windows11のモダンコンテクストメニューでの「貼り付け」機能

### ISSUE THREAD

**Issue by XERE** [FastCopyLab/FastCopy#181]
**機能リクエスト内容**
ファイルを「右クリックからのコピー/切り取り」
右クリックからの「貼り付け」を多用していました。
この機能をモダンコンテクストメニューで実現してほしいです。

また、モダンコンテクストメニューにはアイコンを追加せず、旧来のコンテクストメニューにのみシェル拡張をすることができるようにも要望します。
**補足**
現状はモダンコンテクストメニューには「コピー」「削除」しかありません。

**Comment by shirouzu** [comment]
貼り付けもサポートしているはずなのですが、おかしいですね。
シェル拡張の設定画面で「貼り付け」はチェックされてますか？
されている場合、念のため、再ログインしても貼り付けが現れないかどうか、確認してみてください。
それからサブメニューは使っていますか？

**Comment by XERE** [comment]
サブメニュー化はしていないです。

サブメニュー化については、フォルダーの何も無いところを右クリックした時サブメニュー化しているとfastcopy関連の項目は表示されずフォルダーの中のなんらかのアイテムを右クリックした時は表示されています。
クラシックコンテクストメニューについては問題なく表示されています。

詳しく検証する時間が今週はとれそうもないので返信が遅くなりそうですが、今はこの状態です。

**Comment by XERE** [comment]
こんにちは、別マシンでも試したのですが、
やはりエクスプローラーのコピーメニューにおいてモダンコンテクストメニューでは「貼り付け」は出ないようです。
これはサブメニューにしていても同様です。

フォルダの何もない場所での右クリックでは別マシンではFastCopyのメニューは「サブメニュー」の時のみ表示されていないようです。

**Comment by shirouzu** [comment]
確認しました。地の部分を右クリックではダメで、フォルダ名を右クリックしないと出ないっぽいですね。
モダンメニューはなかなか勝手が違うのでうまく修正できるか判りませんが、見ておきます。
