### ISSUE TITLE
事前に空きが少なくて、コピーできないことを知らせ欲しいです

### ISSUE THREAD

**Issue by polycanmei** [FastCopyLab/FastCopy#182]
差分コピー前提で
コピー元
から
コピー先
へ
コピーする場合に、事前に
コピー先の空き領域を計算して

仮にコピー先に入りきらない場合には

「コピー先に十分な空き領域がなく、全てをコピーすることができません。それでも実行しますか？」
「はい」「いいえ」
を表示はできますか？

よく、途中で「空きがありません（ディスクフル）」が出て、止まってしまいます
今日も出ました
単純に480GBのSSDから全部を250のSSDへ差分コピーしたら
途中で止まりました。これは初めからできないとわかるのではないですか？
勿論うっかりですが

**Comment by shirouzu** [comment]
検討しておきます
