### ISSUE TITLE
Change Default Log Folder

### ISSUE THREAD

**Issue by hasack** [FastCopyLab/FastCopy#183]
Please can there be an option to change the folder for the file logs?

**Comment by shirouzu** [comment]
There is no configuration.
But commad line has /LOGFILE= and /FILELOG= options.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by hasack** [comment]
Hi H. Shirouzu,

Thank you for pointing me to the command line.
However, is there a way of updating the GUI so that end users don't have to use the command line. It would be helpful for those (particularly in businesses) that need to use the application, but aren't good on the command line?

Thanks

Alistair

**Comment by shirouzu** [comment]
I will consider it.

**Comment by hasack** [comment]
Thank you
