### ISSUE TITLE
FastCopy fails to keep a clean Right Click Menu regarding Shell Extension

### ISSUE THREAD

**Issue by feng-yu-healthbank** [FastCopyLab/FastCopy#185]
# Describe the bug
1. FastCopy adds right click menu to Windows 11 even if "Right Click Menu" is deselected.
2. FastCopy is unable to remove all context menus it added when context menu was disabled.

## To Reproduce Problem 1
- Open FastCopy
- Open Main Settings
- Go to "Shell Extension"
- Click "Enable", and deselect (tick off) all under "Right Click Menu" since I want only drag menus
- Click "OK" or "Apply"

### Expected: 

1. I get drag drop menus, and no right click menus.
2. When I drag drop and click on the drag drop menu, FastCopy should perform a copy or move action.

### Actual: 

1. I get both right click menus and drag drop menus. 
2. The drag drop menus do nothing when clicked. No file was copied or moved.

## To Reproduce Problem 2

- Get back to the "Shell Extension"
- Deselect "Enable" and click OK

### Expected: 

I get all context menus removed

### Actual: 

The context menus remains until I manually deleted all references to FastCopy from the Windows registry using the search function. It was a tedious and risky process.

## Command line options and various settings

No command line options were applied. FastCopy was directly launched from the Windows UI, running as Administrator.

## Version/Environment
 - FastCopy ver (principle, latest ver) : 5.05 64 bit
 - OS ver: Windows 11 Pro 22H2 22621.1555 (latest)

## Screenshots

The settings I used 
![Untitled](https://user-images.githubusercontent.com/125230892/235339808-f050a312-bc4f-47a5-af82-6a3db823ab45.png)

**Comment by shirouzu** [comment]
> I get both right click menus and drag drop menus.
> The context menus remains

I confirmed it. It will fix in the next version.

> The drag drop menus do nothing when clicked. No file was copied or moved.

I coudn't confirm it.

**Comment by feng-yu-healthbank** [comment]
Perhaps I had some other issue with the drag drop menu. Anyways, I'm glad you could reproduce and fix the dangling context menus.

**Comment by shirouzu** [comment]
Ok.
Please wait for next version.
