### ISSUE TITLE
Request to add experimental LTFS file copy support

### ISSUE THREAD

**Issue by tommaso82** [FastCopyLab/FastCopy#186]
I'm writing to inquire about the possibility of implementing "experimental" LTFS file copy support in your software. 
Currently, your product is one of the few that works well with LTFS file transfers. It is important to note that for this to work optimally, the copy must be done in sequential mode rather than parallel mode to avoid multiple access to the tape drive. This is particularly an issue with recent versions of Windows and other copy tools. 
By using "overlap I/O num=1", I was able to achieve maximum transfer speeds supported by my LTO 5 tape drive, which is 140 MB/s.

However, one thing that needs improvement is the calculation of the transfer speed. The current calculation starts from the moment the command is given, but the tape needs to position itself first before it starts copying. Therefore, the current calculation doesn't account for this time delay.

LTFS is a transparent layer that works seamlessly in Windows, so supporting file transfers to LTFS units is already achievable with some minor adjustments. All that is required is to fine-tune some details.

Thank you for considering my request. I look forward to hearing from you soon.

**Comment by shirouzu** [comment]
Thank you for your request.
If the file system type is "LTFS", we would like to consider automatically setting overlap I/O num to 1.

Could you answer the file system name of "fsutil fsinfo volumeinfo X:" command result in cmd.exe with admin.
(X: ... LTFS drive letter)

**Comment by tommaso82** [comment]
C:\WINDOWS\system32>fsutil fsinfo volumeinfo t:
Nome volume: LTFS VOLUME
Numero di serie volume: 0x7af3
Lunghezza massima componente: 255
Nome file system: LTFS
È di lettura/scrittura
Senza thin provisioning
Supporta i collegamenti reali

**Comment by shirouzu** [comment]
Thank you for your report.

Using the latest version of LTFS(2.4) at hand, it seems to work fine even with overlap I/O num = 8.
What is the behavior with overlap I/O = 8 in your environment?
Also, what version of LTFS do you have?
