### ISSUE TITLE
CreateFile(ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。123) : 

### ISSUE THREAD

**Issue by XERE** [FastCopyLab/FastCopy#187]
QNAP社のNASを、ネットワークドライブとしてマウントしてあるZ:\ドライブ、（NTFSではなくext4）なドライブに
250文字以上？の長いファイル名のファイルを置こうとすると
CreateFile(ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。123) : Z: ~ファイル名
というエラーが出ます。
その際、ログファイルには、正常に「問題があるファイル名」が書き込まれているので問題ありません。
ただ、エラーが出ている最中にメインのウインドウのボックスは豆腐（文字化け）になってしまう場合がありました。
単に長いファイル名なのでCreateFileエラーが出る場合があるわけではなく、
豆腐状態になるファイルは、文字に絵文字などのUnicode文字が含まれているのが怪しいと踏んでいます。
また、ファイル名の途中から豆腐になっている場合もありました。

具体的なファイル名の全体を提示したいのですが、
性的な意味が含まれ、ファイル名を公にするのに問題がありますので、上記のような報告にとどめます。

例えばこのような感じです
![image](https://github.com/FastCopyLab/FastCopy/assets/1268711/e99434c6-78be-4cd3-819e-bca27fd1007d)

**Comment by shirouzu** [comment]
□は（文字化けではなく）表示フォントに該当グリフ（字形）が無い、という意味になります。
（文字化けの場合、? と変換されます）
今時のOSだとフォント・フォールバックして、当該グリフを持つフォントで表示される場合が多いため、□になってしまうのが良く判りませんが、文字種によっては、そういうこともあると思ってください。

**Comment by XERE** [comment]
わかりました。
いずれにせよログファイルにはきちんと記録されているので、それほど困らないです。

しかしハートマーク以降、明らかにグリフがあるだろうという部分□になってしまってるのはよくわからない気がしますが
きっとOSの内部のファイル名の処理では何かあるのだろうと思っておきます。

なお、
FastCopyの「メインフォント変更」でフォントを変更したときには
ログのフォントは変わらない気がするのですが、ログ部分のフォントを変える方法はあるんでしょうか。

**Comment by shirouzu** [comment]
その部分のフォントを設定する方法はいまのところありません。
その部分は RichEditコントロールなのですが、デフォルトフォントで表示できない文字に出くわすと、自動的に表示可能なフォントにフォールバックするまでは良いものの、その後はそのフォールバックしたフォントから抜け出せない、みたいな挙動をする印象がありますね。

**Comment by XERE** [comment]
お答え下さりありがとうございます。
F状ログファイルでなんとかなっているため、
先度の低い}ですし、ここはBめることにします。
ありがとうございました。

Outlook for Android<https://aka.ms/AAb9ysg>を取得
________________________________
