### ISSUE TITLE
A large source input box will become the original size after I paste a path in it？

### ISSUE THREAD

**Issue by Huaweidev** [FastCopyLab/FastCopy#188]
**Question**
A large source input box will become the original size after I paste a path in it.
It is not convenient for me because I want to paste many source paths into it.

**Operation**
1. Drag a large source input box;
2. Paste a path in it.
3. It will become small again.
---
**質問**
大きな入力ボックスにパスを貼り付けると、元のサイズに戻ってしまいます。
私は多くのソースパスを貼り付けたいので、不便です。

**操作**
1. 大きなソース入力ボックスをドラッグします。
2. パスを貼り付けます。
3. それは再び小さくなります。
---

**Remarks**
before:
![05-17_19-40-52](https://github.com/FastCopyLab/FastCopy/assets/10258421/1f295acb-0260-47d1-baea-c7096bb386b1)
after:
![05-17_19-41-04](https://github.com/FastCopyLab/FastCopy/assets/10258421/1acc31c3-6a92-4645-b2b9-76754c98d7d0)

**Comment by shirouzu** [comment]
It is a specification.
If you press the return key on the last line, it will spread out the space by one line.

**Comment by Huaweidev** [comment]
> It is a specification. If you press the return key on the last line, it will spread out the space by one line.

I've dragged it to size and don't want to change it back. Even if I press enter, it still affects my efficient pasting.
