### ISSUE TITLE
How to copy the C:\test folder not only files to D:\test? I can't find the parameters.

### ISSUE THREAD

**Issue by Huaweidev** [FastCopyLab/FastCopy#189]
**Question**
Source path: C:\test
Destination path: D:\test

How to copy the C:\test folder not only files to D:\test? I can't find the parameters.

**Remarks**
None.

**Comment by shirouzu** [comment]
I do not understand what you mean.

**Comment by Huaweidev** [comment]
For example：
```
C:\test
 - 1.txt
 - 2.txt
```
I paste `C:\test` into the source path and execute move mode, but it will only move `1.txt` and `2.txt`, I want to move the `C:\test` folder and `1.txt` and `2.txt`, is it possible?

**Comment by Huaweidev** [comment]
> I do not understand what you mean.

For example：
```
C:\test
 - 1.txt
 - 2.txt
```
I paste `C:\test` into the source path and execute move mode, but it will only move `1.txt` and `2.txt`, I want to move the `C:\test` folder and `1.txt` and `2.txt`, is it possible?

**Comment by shirouzu** [comment]
Please try Destination path: D:\
