### ISSUE TITLE
FcHash 4.0.2 --xxh3

### ISSUE THREAD

**Issue by therube** [FastCopyLab/FastCopy#19]
Not a bug, per se, but confusing terminology.

FcHash 4.0.2 --xxh3

What you are calling "--xxh3" is not what xxHash calls "-H3" (aka XXH3), but is in fact what xxHash calls -H2 (aka -H128)

They are different hash algorithms.

```
FcHash --xxh  = xxHash  -H1 = xxHash -H64
FcHash --xxh3 = xxhHash -H2 = xxHash -H128
```
xxHash -H3 (aka XXH3) is different.

**Comment by therube** [comment]
I think what I said above is correct, but then I too am confused ;-).

"Question: Is XXH3 supported in the Executable?"
https://github.com/Cyan4973/xxHash/issues/592
"Does xxhsum utility support xxh3 (64bit)?"
https://github.com/Cyan4973/xxHash/issues/447

**Comment by shirouzu** [comment]
If --xxh3 is selected, fastcopy will switch to the source code of xxh3.
In other words, "FcHash --xxh3" is considered to be using xxH3.

We want to know why you think it is xxH 128bit.

**Comment by shirouzu** [comment]
This is xxh and xxh3 init routines of FastCopy v4.
You can confirm that FastCopy uses xxh and xxh3 are different routine. (not only bit size)
![image](https://user-images.githubusercontent.com/1759911/151652101-63cc3ba4-c1a8-451a-ab43-0c9726161103.png)

**Comment by shirouzu** [comment]
Fact is this.
FcHash --xxh means XXH-alg 64bit
FcHash --xxh3 means XXH3-alg 128bit
OK?
