### ISSUE TITLE
How to add a Queue task to Fastcopy?

### ISSUE THREAD

**Issue by Huaweidev** [FastCopyLab/FastCopy#190]
**Question**
How to add a Queue task to Fastcopy?
1. I press the Ctrl key and the "list" button becomes "List+V".
2. I press the button.
3. But it will only list not move files at last.

**Remarks**
None

**Comment by shirouzu** [comment]
I do not understand what you mean.

**Comment by Huaweidev** [comment]
> I do not understand what you mean.

Does FastCopy have an automatic queue copy function? How to?

**Comment by shirouzu** [comment]
What is "an automatic queue copy function"?
