### ISSUE TITLE
Request: Sparse File Support (Synthetic)

### ISSUE THREAD

**Issue by a-raccoon** [FastCopyLab/FastCopy#193]
I would really really (REALLY) ((extremely)) like the ability to copy files such that the destination file is a Sparse File when the destination volume is NTFS.  This is very easy to achieve, but often overlooked by normal people, so its implementation would be novel and help bolster use of FastCopy the same way that preserving Creation Date made FastCopy famous 20 years ago.

HOW:  When FastCopy detects an entire Buffer filled with NULs (0x00) bytes, instead of writing those bites, simply issue a SEEK forward.  Again, this is only if the destination file system is NTFS.  Doing this will make the file Sparse, and those NUL bytes won't occupy any real disk space, but instead will contain SEEK pointers/instructions about the NUL gaps.

That's all I am asking for.  Please and thank you!

WHY?  I have a 1 TB drive with a bunch of sparse files, ie, incomplete bittorrent data (media).  Those files would occupy 4 TB of space if their null portions were realized and written.  I cannot migrate the contents of this drive to a new drive without realizing 4 TB of used disk space when it should only consume 300 GB of real estate in sparsity.

WHY2? Other users can benefit from this space-saving ability, since many files are composed of large pockets of NUL bytes, and making those files contain pointers instead of NUL bytes will save space for any casual user, thus increasing their disk capacity with no loss to performance.  It's a built-in low-level feature of NTFS since 1993, and very standardized.

**Comment by shirouzu** [comment]
I will consider it.
P.S to create sparse file, it is required to use FSCTL_SET_SPARSE/FSCTL_SET_ZERO_DATA ioctl.
