### ISSUE TITLE
Suggestion on how to improve new Perfect Verify feature

### ISSUE THREAD

**Issue by a-raccoon** [FastCopyLab/FastCopy#194]
FastCopy 5 adds a new Pro feature Perfect Verify, which in addition to re-reading the destination copy, the source file is also re-read in order to detect bit rot.  There is also a feature to check for pre-existing :fc_verify ADS data containing a hash digest from a previous FastCopy copy.

I would like to suggest that FastCopy also check to see if the source file has any sidecar hash digest files that accompany it, and calculate whether the source file still matches the recorded hash.  Eg, *.sfv, *.md5, *.sha256, *.sha512.  These files are typically created at the file's very creation or original publication, and will provide the best pre-bit-rot calculation of the file's integrity.

I don't suggest FastCopy create these sidecar hash digests during routine copying, as it does with alt-streams, as these files should be truly authentic and correct, generated at the time of authorship not duplication.

**Comment by shirouzu** [comment]
Thank you for your suggestion.
I will consider it.
