### ISSUE TITLE
[Problem] The program crashes

### ISSUE THREAD

**Issue by HunterSakura1911** [FastCopyLab/FastCopy#196]
**Describe the bug**
Connect an external NVMe SSD ( ADATA EC700G + KIOXIA Exceria G2 SSD M.2 2280 PCIe NVMe 2TB Gen3x4；Both are new) USB 3.2 Gen 1x1 interface, use FastCopy 5.1.1 to copy or move files to the hard disk of the desktop computer.
When moving files halfway, the FastCopy program disappears automatically.

**To Reproduce**
When moving large files (>20GB).

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.
All default values.

**Version/Environment**
  - FastCopy ver (principle, latest ver) : 5.1.1
  - OS ver: Windows 10 x64 Enterprise LTSC 1809
  - HW ver: i5-6500 + 16 GB DDR4-2400 DDR4 SDRAM + KINGSTON SUV500240G  (240 GB, SATA-III, OS) + TOSHIBA DT01ACA100  (1 TB, 7200 RPM, SATA-III, The target hard disk has a lot of free space)

**Screenshots**

C:\Users\windows user\AppData\Roaming\FastCopy\fastcopy_exception.log
------ FastCopy (64bit) ver5.1.1 -----
  Date : 2023/06/13 08:50:06
  Start : 2023/06/13 08:18:37
  OS Infos: 0a/00/4563/00/00/100
  Mod Addr : 0000000140000000
  Mod Date: 2023/05/30 12:02:05
  Mod Size : 1102584
  Build Date: 2023/05/30 10:47:06
  Hash : cc8db16261fa431b6c813f85f8d6d978
  Code/Adr/DC : 80000003 / 000000014002C4A8 / 000000000000001E
  AX/BX/CX/DX : 00000000112EF000 / 0000000000000000 / 0000000000000043 / 00000000112EF000
  SI/DI/BP/SP : 000000000051DD48 / 0000000000000000 / 0000000000000000 / 000000005B41FAE0
  08/09/10/11 : 000000005B41F948 / 0000000000000001 / 0000000000000000 / 000000005B41FAC0
  12/13/14/15 : 000000001B700000 / 0000000000700000 / 000000000051EF30 / 0000000026DB705C
  BT/BF/ET/EF : 0000000000000000 / 0000000000000000 / 0000000000000000 / 0000000000000000
------- pre stack info -----
0000000000000000 00000000000001F4 000000000463EEF4 000000000463EEE0
000000000051DD48 000000014001B930 0000000000000000 0000000000000001
0000000000000000 00000000000003F4 000000000051EF18 00000000000000000
000000005B41FB38 000000014001B9DA 000000005B41FB28 000000000463EEE0
0000000000000000 000000000051EF30 000000000051DD48 000000014002C9B5
000000000463EEE0 000000000463EE98 000000000051EF30 000000000051DD48
000000005B41FB40 0000000100000000 0000000026DB705C 000000000051EF30
0000000026DB705C 000000000051EF30 0000000000000000 000000014002C3C4
------- stack info -----
0000000000000000 0000000000000001 000000000051DD48 0000000000800000
0000000000000000 000000005B41FB38 000000005B41FB40 000000005B41FB28
0000000000000000 00007FFF00000001 0000000000000450 000000001B700000
0000000000700000 0000000000000008 000000005B41FCF0 00000000000000001
000000005B41FD00 0000000000000450 0000000000000001 0000000000000001
00000000000004D0 000000014002C8A9 000000000051DD48 0000000000000450
00000000000004D0 000000005B41FD00 0000000000000043 000000014A000000
0000000000000000 000000000051F228 0000000000000000 0000000000180000
0000000000000001 0000000040000000 000000005B41FCE8 0000000000000001
0000000000000450 000000006A000000 000000005B41FCF0 000000014002B9CA
000000000051DD48 0000000000000450 000000005B41FD00 00000000000000000
000016DE40000000 000000016A000000 000000006A000000 0000000100000100
FFFFFFFFFFFFFFFF 0000000000000000 0000000000001400 0000000000000003
0000000000000000 000000014002BC85 000000000051DD48 000000005B41FD90
000000005B41FD00 000000005B41FD00 0000000000000002 0000000000000000
000000000051EE68 000000014002D212 000000000000000E 00000000000000000
0000000026DB705C 0000000000000450 0000000026DB705C 0100000000000003
0000000000000003 00000000000004E0 0000000000000000 01D99DA007F6517C
01D99DA00A3E7BB2 01D99DA00A3E7BB2 0000000026DB705C 0000000000000020
0000000000000000 0000000000000002 000000E8000000E8 0000000000000000
00000000000004E0 0000000000000000 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000050
00001FF8BE651A8D 000000000051DD48 0000000000000000 00000000000014D4
0000000140000000 000000000000005C 0000000000000001 000000000051DD48
0000000000000007 000000014002A2E9 000000000051DD48 00000000000000007
0000000000000000 0000000000000000 0000000000000000 00000000000000000
00000000047A7790 000000014009D483 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 0000000140029EB6
000000000051DD48 000000000051DD48 0000000000000000 0000000000000000
000000000051DD48 000000014009D601 0000000000000000 00000000000000000
0000000000000F01 0000000000000005 0000000000000000 00000001400956C2
000000000051DD48 000000000464EB10 0000000000000000 0000000000000000
0000000000000000 00007FFF5FE07AC4 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 00007FFF6190A351
0000000000000000 0000000000000000 0000000000000000 00000000000000000
0000000000000000 0000000000000000 080F939F00000000 0000000000000000
00007FFF5D9C6EC0 000000005B41EBA0 AB27FABE0000FFFE 00007FFF5593FD5F
00007FFF5D9C6EC0 000000005B41EBA0 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000000
0000000000000000 0000000000000000 0000000000000000 00000000000000000

May I ask what is the problem ?

**Comment by shirouzu** [comment]
That log indicates the use of a cracked version.
Please use the official version.
