### ISSUE TITLE
Change from GPLv3 to closed source

### ISSUE THREAD

**Issue by teknowledgist** [FastCopyLab/FastCopy#197]
Hi.

I didn't look at too many releases, but [as of version 3.5](https://web.archive.org/web/20180529085916/https://fastcopy.jp/help/fastcopy_eng.htm#license), FastCopy was open source under the GPLv3 and source code was available (as is required).

Even as of version 4.2.2, the readme document included with the software stated `FastCopy is GPLv3 license, you can modify and use under GPLv3` with the "disclaimer" that access to the source code is "temporarily suspended".

I am not a lawyer, but as I understand section 5.c. of the GPLv3, any modifications you have made to the source code must also fall under the GPLv3 license.  That would mean while you can separately license applications that accompany or enhance FastCopy, unless you have re-written the source code in its entirety for v5, I think you have to provide access to the source code for the application itself and include the GPLv3 license with it.  While I think you can sell the compiled binaries of your source code, I don't believe you can prevent distribution of those either.  You might be able to legally prevent distribution of the installer, but not the binaries created from the source code.

I'm confused with the move to GitHub to distribute binaries of what you are claiming is your licensed software.  That seems a bit like thumbing your nose at the open source community.

**Comment by shirouzu** [comment]
I am the complete owner of the source code.

FastCopy has no third party contributors who have committed source code to date. (except for xxHash/Zlib/OpenSSL).

Therefore, I reserve the right to change from one particular subsequent version to another license.

Also, as the full owner, I may grant me a closed license separate from the GPL for any previous version, even if it is a newer version (dual license)
