### ISSUE TITLE
タイムスタンプが更新されてしまいます

### ISSUE THREAD

**Issue by Coopii** [FastCopyLab/FastCopy#198]
**質問**
2018～2019年頃に公開されているいくつかのブログでは、
『fastcopy』はタイムスタンプを維持したままデータをコピーできます！
というように紹介されていました。
しかし私が試したところ、階層の一番上…例えば以下のような構成だったとします。
[C:]-[ユーザー]-[YAMADA]-[デスクトップ]-[フォルダA]
　　　　　　　　　　　　　　　　　　  -[フォルダB]
すると、フォルダAやBの日付が今日のものに変わってしまいました。
「デスクトップ」はもとの日付のままです。
どなたか解決方法をご存知ありませんか？Pro版を購入すればいいのでしょうか？

**Comment by shirouzu** [comment]
具体的には Source と DestDir をどういう指定にしていますか？

**Comment by Coopii** [comment]
コメントありがとうございます。
Source   C:\Useres\YAMADA\Videos\
DestDir  D:\Video\　　←SSD内に作成したVideoというフォルダ
に設定しています。よろしくお願いいたします。

**Comment by shirouzu** [comment]
この場合、D:\Video\ の下に Videos というフォルダが作成されて、そのフォルダのタイムスタンプは C:\Useres\YAMADA\Videos と同じとなるはずですが、そうなっていない、ということでしょうか？
もう少し具体的に教えて頂けると助かります。

**Comment by Coopii** [comment]
失礼しました。
その通りです。D:\Videosがすでに変わってしまっていて、その下のフォルダA、フォルダB\なども
FastCopyを利用した時間のものに変わってしまいます 。

心当たりとして、フォルダをいくつかGoogleドライブと同期しているのですが、
それが悪さをしているのでしょうか…。
試しに同期を停止し、時間を置いてFastCopyを使用したところ、
コピー後は同期していたすべてのフォルダの更新日付が、最後に同期した時間になっていました。
エクスプローラでもとのフォルダを見ると、正しい日付のままでした。

**Comment by shirouzu** [comment]
> 心当たりとして、フォルダをいくつかGoogleドライブと同期しているのですが、
> それが悪さをしているのでしょうか…。

それはありそうに思います。
Googleドライブに裏で操作される場合、FastCopy側では如何ともしがたいですね…

**Comment by Coopii** [comment]
そうですよね…わかりました。
ご回答いただき、ありがとうございました。
