### ISSUE TITLE
what happens if you execute a job before automatic update completes?

### ISSUE THREAD

**Issue by zxcvb3** [FastCopyLab/FastCopy#199]
On my computer, it takes awhile to update maybe 30 seconds.
I haven't had this happen yet, but I wondered what would happen if I executed a job before the update completed.
Would it interrupt the job or would it wait for the job to complete before updating?
I am wondering if I should turn off automatic updates to avoid this from happening.

**Comment by shirouzu** [comment]
If a copy(move/sync/delete or etc) operation is in progress, the update operation is canceled.
