### ISSUE TITLE
大容量ファイルのコピーが「継続できません」となります。

### ISSUE THREAD

**Issue by yenpower** [FastCopyLab/FastCopy#20]
**質問**
大容量のファイル（１つ）をコピーしようとすると、
メモリ使用量が増加し続け、搭載メモリ容量（6GB）へ達してしまい、
「継続できません」と表示され、コピーができない状況です。

表示メッセージ：
「継続できません」
　Can't alloc memory(fileStatBuf) : 

使用環境
・OS：Windows 10 Pro　
・メモリ：6GB
・コピー元：ASUSクラウド Remote-Drive（ネットワークドライブ）
・コピー先：ローカルハードディスク
・ファイル容量：2.89 GB（iso形式）
・FastCopy設定：デフォルト

**備考**
補足やスクリーンショットがあれば追加してください。
![継続できません2022-01-29](https://user-images.githubusercontent.com/23088523/151644026-dc14d35e-9aa8-4d11-8d74-99fce71a3ab6.png)
![メモリ使用量2022-01-29](https://user-images.githubusercontent.com/23088523/151644056-55440181-c7f7-4741-bc06-5993705a1eb9.png)

**Comment by shirouzu** [comment]
おそらくですが、I:\xxxx\s\ の直下に、膨大なファイル/ディレクトリが存在しませんか？
（もしそうであれば、その読み取り用のバッファが不足したということになります）

コピーモードを「差分（サイズ・日付）」ではなく「コピー（全上書き）」で試してみて下さい。

**Comment by yenpower** [comment]
コピーモードを「コピー（全上書き）」で試してみました、が、
事象はかわりませんでした。

コピー先の状況は、下記のようになっています。
（コピーが成功した暁には、膨大になる予定ですが、いまのところはそれ程でもないかと）
場所：　I:\
サイズ：　224 GB (241,178,617,856 バイト)
ディスク上のサイズ：　224 GB (241,178,656,768 バイト)
内容：ファイル数: 45、フォルダー数: 1

**Comment by shirouzu** [comment]
失礼、このメッセージは source側のファイル数の問題ですね。
Win32API（FindFirstFile等）で見た場合に、1ファイルのISOではなく、中身の大量ファイルが見える、というモノではありませんか？
（だとすると、それに耐えうる statBuf 確保が必要になります）

**Comment by yenpower** [comment]
source側のファイル数の問題ということなんですね。

先ほどはDestDir側の状況でしたが、他の状況は下記のようになっています。

・source側
場所：　X:\DVD\x\s
サイズ：　109 GB (118,004,322,304 バイト)
ディスク上のサイズ：　109 GB (118,004,322,304 バイト)
内容：ファイル数: ファイル数: 28、フォルダー数: 0

・ISOファイルの中身
サイズ：　2.89 GB (3,112,790,016 バイト)
ディスク上のサイズ：　2.89 GB (3,112,790,016 バイト)
内容：ファイル数: ファイル数: 9、フォルダー数: 2

**Comment by shirouzu** [comment]
調査ありがとうございます。
ただ、Source側の読み取りが限界になっているということは、少なくとも50～100万ファイル、といったオーダーのファイルが存在、と見えているはずなんですよね。
（もしくは何らかの理由で、FindFirstFile/FindNextFile API が終わらなくなっているか）

Explorerでコピーできるようなら、それでローカルにコピーして、それをFastCopyでコピーするとどうなるか教えて頂けますか？

**Comment by yenpower** [comment]
ただいま、
Explorerで、クラウドからローカルにコピー中です。（1.73MB/s程度なので時間がかかっています）

**Comment by shirouzu** [comment]
参考までに一部のネットワークドライブでは、下記のチェックを外さないと、正常なディレクトリエントリを返さないNASがありました。
ただし Windows7時代の話ですが。

![image](https://user-images.githubusercontent.com/1759911/151654865-47788406-5cfd-40c1-80a7-c58b9a0e4e2f.png)

**Comment by yenpower** [comment]
検証結果です。
Explorerでコピーできるようなら　→　できました。
ローカルにコピーしたものをFastCopyでコピーするとどうなるか　→　期待通り正常にコピー完了しました。
![ローカル別HDD2022-01-29](https://user-images.githubusercontent.com/23088523/151656998-2c38089b-91f5-430e-81fa-3f1ae09a5b30.png)

ご指摘いただいた、ディレクトリ読み取りのチェックについては、
チェックを外して、クラウドからローカルへのコピーを試しましたが、
事象に変化はありませんでした。

また、当該ファイルのローカルからASUSクラウドへのコピー（アップロード）は、正常にコピーが進捗しています（検証中）

**Comment by shirouzu** [comment]
調査ありがとうございました。
手元でも ASUS WebStorage を入れて試してみましたが再現しないですね。
ASUSクラウド Remote-Drive＋環境依存の特殊な問題に見えるので、とりあえずペンディングという形にさせてください。

**Comment by yenpower** [comment]
再現しないのですね。
ある意味よかったです。
私の環境による特殊な問題であるなら、通常であれば発生しない事象ということですね。
他の方々には、これからも安心して推奨できます！
この度は、貴重なお時間をさいてしまい、申し訳ありませんでした。
また、迅速丁寧にご対応いただき、ありがとうございました。

もしまた、「ここの設定をこうしてみて」「〇〇〇のログを採取してみて」などございましたら、
できる限り協力させていただきますので、なんなりとお申し付けください。
