### ISSUE TITLE
"Size is changed(ddigest)"

### ISSUE THREAD

**Issue by QUAKEULUS** [FastCopyLab/FastCopy#200]
I'm not sure what this error message means.

**Comment by shirouzu** [comment]
Sorry for the confusing wording.

It means that since the size of the dst file was different from the original, the digest calculation is useless and will be skipped.

**Comment by artie-finkelstein** [comment]
So far I have only seen this "Size is changed" error message issued when there is an 8.3 style file name in the source folder (e.g., _filena~1.ext_) that collides with the generated 8.3 name for a long file name (e.g., _filename.ext_).  Win7 will let both _filena~1.ext_ and _filename.ext_ coexist as different files in the source folder. This 8.3 name "generation" seems to happen when FastCopy writes into the destination folder so when a second file gets copied that has the same 8.3 name as the first file copied FastCopy can't rename the target file, and issues this error message.

My workaround is to examine the target/destination file, find it's 8.3 name equivalent in the source folder, rename the source file as _filena_1.ext_ and manually copy it to the target folder.  This prevents future occurrences when later copying either folder.

I view this issue as unexpected fallout from the Microsoft's 8.3 naming algorithm and people copying LFNs on older OS versions.

**Comment by shirouzu** [comment]
Yes, it is one scenario.
Disabling short file names on the dest side drive is a possible solution.
(fsutil behavior query disable8dot3)

Otherwise, it can also be caused by data being rewritten in the gap between the end of the copy and the verify.

**Comment by artie-finkelstein** [comment]
Thank you for the fsutil suggestion.
