### ISSUE TITLE
The font of the software Home screen is different from the official website

### ISSUE THREAD

**Issue by lzw99733080** [FastCopyLab/FastCopy#201]
The font of the Home screen of the software is different from that of the official website. What font do I lack? I am using Windows 10 22H2
<a href="https://smms.app/image/zUs27By9u4xDdpj" target="_blank"><img src="https://s2.loli.net/2023/07/05/zUs27By9u4xDdpj.png" /></a>

**Comment by shirouzu** [comment]
The main dialog of Chinese version is "Microsoft YaHei".

**Comment by lzw99733080** [comment]
Thank you for your reply. I will test it.
