### ISSUE TITLE
CRASH!!!

### ISSUE THREAD

**Issue by WF3W** [FastCopyLab/FastCopy#204]
All of a sudden, my entire system CRASHES! I mean everything: the entire system is frozen, I have to hold-down the power-on button, to power-down and then REboot. I have the latest version.

Crashes have ocurred simply trying to open a file or opening FireFox or, what I would call, CPU-intense tasks, like moving files around. Today, I didnt do anything other than copy: walked-out of the room and when I came back, ZIP, no system - even the touch-screen would not function, let alone mouse & KB.

I am running the most basic set-up, i.e., copying from 1 directory to another [acutally a back-up]

Your help is solicited! This is/was a fabulous program!

Phil
WF3W@JUNO.COM

**Comment by oscarsun72** [comment]
We are all fine, it should not be this program that caused your system to crash, Good luck. Praise the Lord! 感恩感恩　南無阿彌陀佛

**Comment by shirouzu** [comment]
I suspect a problem with your PC itself and recommend that you perform a health check of your PC.
(chkdsk, memtest, CrystalDiskInfo, or etc.)

Anyway, FastCopy uses only standard Windows APIs, so it does not have the ability to crash or freeze your system.

**Comment by WF3W** [comment]
Good morning, LOL &mdash; I knew you were going to say that I always suspect MS/WIN first. How long after an "upgrade" would this happen? Immediately or time for MS to louse-up the system? Phil

**Comment by WF3W** [comment]
I REGRET TO INFORM YOU, PRAYER IS IMPOTENT IN CONFRONTING MICRO-SHIT
