### ISSUE TITLE
Cracked version (about exception)

### ISSUE THREAD

**Issue by ThemanRonin** [FastCopyLab/FastCopy#205]
[exception-report.zip](https://github.com/FastCopyLab/FastCopy/files/12101534/exception-report.zip)

Hello, while running FastCopy (x64) ver5.2.4. After clicking 'Execute', it will flash back directly. And it will open the FastCopy root directory to generate fastcopy_ Exception.log

&Fastcopy_ Exception.dmp 2 files. What is the problem? Is it because my file path contains illegal characters

The fault report file has been packaged in zip. Help me analyze it. Thank you

**Comment by shirouzu** [comment]
That log indicates the use of a cracked version.
Please use the official version.

Modifying FastCopy is a violation of the license.
FastCopy has a self-modification checker and will crash if it detects modifications.

----
该日志显示使用的是破解版。
请使用正式版本。

修改 FastCopy 是违反许可证的行为。
FastCopy 有一个自我修改检查器，如果检测到修改会崩溃。

https://github.com/FastCopyLab/FastCopy/issues/196
