### ISSUE TITLE
Application verifier reports memory leak

### ISSUE THREAD

**Issue by ghost** [FastCopyLab/FastCopy#208]
**Describe the bug**
I was debugging my own application. In my application there is a File Open dialog. Opening this dialog will cause Fastcopy shell extension (FastEx64.dll) to be loaded.

Upon closing my application, Application Verifier warned me that there was a memory leak coming from FastEx64.dll. After disabling Fastcopy shell extension (and delete FastEx64.dll) the problem will go away.

I was using Fastcopy version 4.2.0, however, after uninstalling that version and updating to latest 5.2.4 the error is still there.

Other DLL and shell extensions do not produce this error. Since I do not have pdb or source code, I will not debug it by myself.

**To Reproduce**

1. Install the application verifier from Microsoft
2. Enable application verifier for application with a File Open dialog (e.g. Notepad.exe) and enable Basic->Leaks check
3. Use debugger to run application (e.g. Notepad)
4. Ctrl+O to open file dialog
5. Right click on a .txt file to cause FastEx64.dll loaded
6. Close the dialog and the Notepad application
7. Memory leak warning will appear

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.2.4.0 official free version from fastcopy.jp
 - OS ver: Windows 7 SP1

**Comment by shirouzu** [comment]
Thank you for your report.
I will look into this when we have time.
If you are concerned, we recommend that you do not use the shell extensions.
