### ISSUE TITLE
The transmission speed of the two servers in the local area network is very low

### ISSUE THREAD

**Issue by zenlee123** [FastCopyLab/FastCopy#209]
**Question**
May I ask why the speed is 4.75MB/s? I am transferring files through the LAN 10Gbps network card？
Version：FastCopy Pro ver5.2.4
Network card： 10Gbps
Windows version：Windows Server 2019 Datacenter,64 bit  
Transfer file size：6.5T

**Remarks**
![image](https://github.com/FastCopyLab/FastCopy/assets/84231984/642a87bd-8ef4-4bc3-bb1b-8a9094ab7532)

**Comment by shirouzu** [comment]
Check the copy speed in Explorer as well as FastCopy.
If it is also slow in Explorer, the cause is more likely to be something other than the copy software.

**Comment by zenlee123** [comment]
What I copied was a large file from another computer in the local area network. I couldn’t set it through the Windows’ built-in permission sharing method, so I didn’t test it like this, as shown in the figure below:
![image](https://github.com/FastCopyLab/FastCopy/assets/84231984/35f4cd2e-d8d6-4764-9b21-e1711ddc058f)

**Comment by shirouzu** [comment]
??
Files that can be copied with FastCopy can also be copied with Explorer.

**Comment by zenlee123** [comment]
May I ask how to transfer files in  the local area network, how to operate through the Explorer?

**Comment by shirouzu** [comment]
If you put the path name("\\\\192.168.1.101\\I$\\...") in the address bar of the Explorer, it will open that folder.

P.S the Explorer means "Windows File Explorer", not "Internet Explorer". (just to be sure)
https://en.wikipedia.org/wiki/File_Explorer

**Comment by zenlee123** [comment]
Thank you for your reply.
Using this method（If you put the path name("\\192.168.1.101\I$\...") in the address bar of the Explorer, it will open that folder）, the test speed is similar to FastCopy about 4MB/s.
May I ask how to increase the copy speed or what causes the copy speed to be slow?

**Comment by shirouzu** [comment]
To find out, you need to do a lot of research.
 - Local storage speed
 - Effective network speed
 - Influence of anti-virus and firewall software
 - etc

In addition, it may be necessary to investigate with Task Manager, Resource Monitor, and possibly Performance Monitor.
