### ISSUE TITLE
FcHash.exeに機能追加して欲しい

### ISSUE THREAD

**Issue by polycanmei** [FastCopyLab/FastCopy#21]
FcHash.exe便利でいいです
今までは電卓でハッシュ値を計算していたので、、

惜しいです。。以下の機能を追加できますか？

＜例＞
FcHash.exe --a　副次ストリームへハッシュ値の追加（既にある場合は無視）
FcHash.exe --c　ファイルの破損チェック
　　　　　　　　副次ストリーム内のハッシュ値と、そのファイルのハッシュ値を計算して比較
　　　　　　　　（副次ストリームがない場合は無視）

C:\> fchash --c C:\

a.txt OK
b.txt NG
　・
　・

**Comment by shirouzu** [comment]
あるといいですね。

**Comment by kyunjingan** [comment]
こんなのあったらいいですね。。。
fastcopyで作っておいた副次ストリーム内のハッシュ値と
現在のハッシュ値を比較できます
破損ファイルがあるか、使ってみてください

まずは
☑ベリファイ情報を付与（副次ストリームへのハッシュ情報等付与）
で、全ファイルを空のHDDにベリファイコピーして下さい
a.txt
a.txt:fc_verify:$DATA
がペアでないとつまらないです

https://1drv.ms/u/s!An5FOcISHAY8luZYb8xnHmT65Mtc5A?e=Sf0Q0y
fccheck.zip ダウンロード！
