### ISSUE TITLE
How to schedule a task with fastcopy?

### ISSUE THREAD

**Issue by will9311** [FastCopyLab/FastCopy#210]
I have run fastcopy manually with success.  It was a great experience.

However, when I tried to schedule a task with Windows Task Scheduler, I couldn't figure out where to set 'source/desDir' or 'copy ACL'.

Not sure if it is possible to do that kind of settings because it says, "FastCopy doesn't have any function for Windows Task Scheduler"?

If that is the case, is there any way to use CLI to schedule fastcopy tasks?  And how to do that?  Please show me some clue, and I will be able to figure it out.

Thanks a lot!

Will9311

**Comment by shirouzu** [comment]
The command line format is as follows.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by will9311** [comment]
Received with thanks.  Will give it a try.
