### ISSUE TITLE
FC as default of XYplorer and user account control permission

### ISSUE THREAD

**Issue by H5820121** [FastCopyLab/FastCopy#211]
I made FC the default of XYplorer, but the problem is that now I cannot copy files to folders where user account control permission is required, such as system folders, in the standard Windows copy application it gives the user the option to grant such permission, is there any option for this in FC In a way that FC will still be used as XYplorer's default?
Thanks!

**Comment by shirouzu** [comment]
I don't know about XYplorer, but if you want to perform an operation that requires privileges, please press the "Elevate" menu item in the upper right corner.

**Comment by H5820121** [comment]
Thanks, working!
On this occasion I mention the request of the many, to give an option for this great copier to be the default Windows Explorer's copier, and as there is such an option in TeraCopy as well as in ExtremeCopy. Maybe in the meantime you know how I can do it myself? Maybe through some settings in the registers?

**Comment by lgander** [comment]
@H5820121 I´m trying to make FC the default copier for XYplorer. 
Could you please let me know how you accomplished that?

**Comment by H5820121** [comment]
[image: image.png]
[image: image.png]

‫בתאריך יום ג׳, 9 בינו׳ 2024 ב-13:51 מאת ‪lgander‬‏ <‪
***@***.***‬‏>:‬

**Comment by lgander** [comment]
@H5820121 the images haven't arrived, just some text indicating you sent an image.
could you please try again?

Thanks!!

**Comment by H5820121** [comment]
‫בתאריך יום ג׳, 9 בינו׳ 2024 ב-22:09 מאת ‪lgander‬‏ <‪
***@***.***‬‏>:‬

**Comment by lgander** [comment]
@H5820121 
The last one was just an empty message quoting my last post.
Thanks

**Comment by H5820121** [comment]
Type 'External Copy Handlers' in XYplorer HELP.

‫בתאריך יום ג׳, 9 בינו׳ 2024 ב-22:26 מאת ‪lgander‬‏ <‪
***@***.***‬‏>:‬

**Comment by lgander** [comment]
Great, thanks!!

**Comment by H5820121** [comment]
FastCopy (open window & auto
close)|C:\Users\%UserName%\FastCopy\FastCopy.exe|/open_window /auto_close
FastCopy (auto close)|C:\Users\%UserName%\FastCopy\FastCopy.exe|/auto_close

‫בתאריך יום ד׳, 10 בינו׳ 2024 ב-23:30 מאת ‪lgander‬‏ <‪
***@***.***‬‏>:‬

**Comment by shirouzu** [comment]
https://github.com/FastCopyLab/FastCopy/issues/192#issuecomment-5339064796
