### ISSUE TITLE
How can I myself make FC the default Windows Explorer's copier?

### ISSUE THREAD

**Issue by H5820121** [FastCopyLab/FastCopy#212]
In the past I mentioned the request of the many, to give an option for this great copier to be the default Windows Explorer's copier, and as there is such an option in TeraCopy as well as in ExtremeCopy. 
In the past I mentioned the request of the many
**Can you guide me in the meantime how I can do it myself?** Maybe through some settings in the WIN registers?
Thanks for everything!

**Comment by shirouzu** [comment]
Please do not post the same content.
