### ISSUE TITLE
Exception occured latest version 5.2.6

### ISSUE THREAD

**Issue by PegHorse** [FastCopyLab/FastCopy#213]
Hi,

I don't know how to explain that, i was copying a file of 6 GB from a Network HDD to my local HDD and an exception occured during the copy.

[FastCopy error.zip](https://github.com/FastCopyLab/FastCopy/files/12311571/FastCopy.error.zip)

**Comment by PegHorse** [comment]
I have re-downloaded latest version and re-installed the application and it's working again.

**Comment by shirouzu** [comment]
That log indicates the use of a cracked version.
Please use the official version.
https://github.com/FastCopyLab/FastCopy/issues/205

**Comment by PegHorse** [comment]
I made a donation of 10€ a while ago, you didn't provide any licence but since latest version, you ask for registration.
