### ISSUE TITLE
how to exclude folders from the copy

### ISSUE THREAD

**Issue by elduvelle** [FastCopyLab/FastCopy#214]
**Question**
Hi, what is the correct syntax in the 'Exclude' field to exclude any folder with a specific name? 
for example if the folder to exclude is called "my_folder" I tried:
my_folder
my_folder\\
my_folder\\*
\my_folder
\*\my_folder
\my_folder\\ 
\*\my_folder\\*

but in all cases, folders named 'my_folder' in the source directory are still copied to the destination directory.

Thanks for a great program!

**Comment by shirouzu** [comment]
The correct format is as follows.
 my_folder\\
If you do not write well, try pasting a screen capture.

**Comment by elduvelle** [comment]
Dear @shirouzu , thank you for the fast answer!
I did try that syntax and it doesn't seem to work. See for example these two screenshots, the first one is without excluding the folder 'more_stuff', the second one does attempt to exclude it, but it is still listed in the copy list:

![image](https://github.com/FastCopyLab/FastCopy/assets/64431932/4de8b41a-4e5b-4077-ba7e-b29d999e2702)

![image](https://github.com/FastCopyLab/FastCopy/assets/64431932/84a2aa96-4cf0-4690-8beb-54d8bed5980d)

**Comment by elduvelle** [comment]
@shirouzu never mind! I had a typo (of course) - if I use your syntax it does work.
Sorry about the trouble and thank you again!

![image](https://github.com/FastCopyLab/FastCopy/assets/64431932/42c5a313-98a0-4a42-9853-0b753c991e41)
