### ISSUE TITLE
Seems to be an icon bug.

### ISSUE THREAD

**Issue by 111alan** [FastCopyLab/FastCopy#216]
**Describe the bug**
There seems to be an icon bug when the access of some of the files was denied. Both the icons on taskbar and title bar are incorrect.

**To Reproduce**

Steps to reproduce the behavior: Copying one partition with $recycle.bin or System Volume Information to another drive is one way to reveal this bug.

**Command line options and various settings**
GUI, sync, verify

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.3.0
 - OS ver: Win10 21H2

**Screenshots**
![fastcopy](https://github.com/FastCopyLab/FastCopy/assets/30613544/f1350d67-c3b6-4eae-b240-2196a9588a2d)

**Comment by shirouzu** [comment]
The red bar is an intentional sign, indicating that an error has occurred.
