### ISSUE TITLE
Missing "Close to Systray" and "Exit" in SysTray menu (only)

### ISSUE THREAD

**Issue by pstein** [FastCopyLab/FastCopy#219]
I miss an option to let FastCopy minimize to SysTray even if I click on "x" close window.

The only way to full Exit FasctCopy should be in future to select "Exit" from new Fastcopy context menu in SysTray.
Or via new "Exit" menu in FastCopy window.

Oftentimes I click on "x" and want to minimize only. This would abort pending operations.
Bad.

Furthermore:

If I minimize FastCopy window the "normal way" it is minimized to SysTray AND (!) TaskBar.
I want to minimize to SysTray ONLY

**Comment by shirouzu** [comment]
I don't understand what you are writing.
But please see and play the movie.
![image](https://github.com/FastCopyLab/FastCopy/assets/1759911/27f735ea-b9a7-400a-a233-7a76c9a95870)

**Comment by pstein** [comment]
What is so difficult to understand?

Have a look at the attached snapshot.

When I minimize FastCopy then it appears in TaskBar AND SysTray.
I want minimization in SysTray ONLY

![minimizing to TaskBar AND SysTray](https://github.com/FastCopyLab/FastCopy/assets/2775875/755ae40d-591a-4bba-b7b6-c5f76ac4ab03)

**Comment by oscarsun72** [comment]
> 

That happened to me too.

**Comment by shirouzu** [comment]
Sorry, it is current specification.
![image](https://github.com/FastCopyLab/FastCopy/assets/1759911/9c31694b-96e0-42f0-bfa2-77857b4cd80c)

If you want the icon to show only in the task tray, it must be taken out of the display area at all times.
![image](https://github.com/FastCopyLab/FastCopy/assets/1759911/b0c769a8-75af-4097-b87b-039f036aa972)

**Comment by oscarsun72** [comment]
> Sorry, it is current specification. ![image](https://user-images.githubusercontent.com/1759911/265872501-9c31694b-96e0-42f0-bfa2-77857b4cd80c.png)
> 
> If you want the icon to show only in the task tray, it must be taken out of the display area at all times. ![image](https://user-images.githubusercontent.com/1759911/265873214-b0c769a8-75af-4097-b87b-039f036aa972.png)
Does that mean we can't hide the icon in the **taskbar** in Windows now unless we show it on the **task tray**?
