### ISSUE TITLE
更新日付が現在になるバグが、直っていません

### ISSUE THREAD

**Issue by lyanmeng** [FastCopyLab/FastCopy#22]
>DestDirがNASの場合に、ベリファイ情報付与を有効にすると、更新日付が現在になる問題の修正
に限らず、
☑副次Streamの場合に、ベリファイ情報付与を有効にすると、
更新日付が現在になるバグが、直っていません

以前バグ報告したので、ver4.0.2で直っていると思ったんですが、、

**Comment by shirouzu** [comment]
下記の v4.0.2d2 で修正されているはずなので、確認してみてください。
https://github.com/FastCopyLab/FastCopy/issues/17#issuecomment-1024247313
（なお、こういう苛立たしい言い方は、フリーソフト作者のモチベーションを下げこそすれ上げないので、ご一考下さると助かります）
