### ISSUE TITLE
endpoint error

### ISSUE THREAD

**Issue by decrok** [FastCopyLab/FastCopy#220]
**Describe the bug**
When running the program, the error message "There are no more endpoints available from the endpoint mapper" is displayed and the program does not run.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.3.0
 - OS ver: Winodws 11 PE

-----------------------------------------------------------------------------------------------------------------
First of all, I would like to thank you for developing a great program.

I often use the fastcopy program in Windows PE for PC maintenance.

The problem did not occur in factcpoy 4.x version.
A problem occurred starting from version 5.x.
It appears to be related to the RPC service, but I'm not sure.

This is not a typical Windows environment, but can you help me fix it?

best regards,

**Comment by shirouzu** [comment]
I'm not sure of the cause, but please use in a supported environment.

**Comment by YuangeW** [comment]
He meant that version 4.xx were able to run under windows PE, but the latest version 5.xx are unable to run under windows PE. Indeed.

**Comment by shirouzu** [comment]
The manifest was modified in v5.4.2, so it may work in PE environment.
Please check.
