### ISSUE TITLE
Moving license to new HD

### ISSUE THREAD

**Issue by mikesclemons** [FastCopyLab/FastCopy#221]
I bought a pro license in June.  This weekend I replaced the hard drive in the machine and did a fresh install.  Did I need to uninstall FAstCopy on the old drive before I reinstalled it?  When I try to use my pro license number it tells met that the number of licenses has been exceeded.  The only change was a new hard drive.

**Comment by shirouzu** [comment]
Basically, the license must be released before reinstalling. (Migration/Release)
https://fastcopy.jp/help/fastcopy_eng.htm#license_manager

Please contact FastCopy Pro support by replying to the license notification email.
