### ISSUE TITLE
How to backup several drives on one drive?

### ISSUE THREAD

**Issue by domyslny** [FastCopyLab/FastCopy#222]
Hello,
I have a question that I can't find the answer to.
I am a new user of FastCopy and would like to use it to back up files on my drives. Unfortunately, if I select several source drives (e.g. "C:\, E:\, H:\, I:\") and one destination folder ("D:\FastCopy\"), all files from each source go to subfolders of the same D:\FastCopy folder. It is impossible to distinguish which folder was originally on which drive.
I would like the data from each source disk to go to a different subfolder (i.e. "C:\\\*" to the "D:\FastCopy\DriveC\\\*" folder, "E:\\\*" to the "D:\FastCopy\DriveE\\\*" folder, "H:\\\*" to the folder "D:\FastCopy\DriveH\\\*" and "I:\\\*" to the folder "D:\FastCopy\DriveI\\\*"). Is it possible? Perhaps this is provided somewhere in the documentation, but unfortunately I can't find it anywhere (maybe I'm just too stupid), so I decided to ask on the local forum.
Can you help me?

**Comment by a-raccoon** [comment]
It doesn't seem possible and would appear to be an oversight (bug) in the software in accordance with the `The last character of DestDir is '\'` documentation. [[link]](https://fastcopy.jp/help/fastcopy_eng.htm#source_dst)

I recommend the software should create a Dest folder for root directories that appear in the SrcDir following the backslash and multi-Src rules, and that they're simply named `\C\` and `\D\` and `\E\` etc to remain below the 260 character limit on some systems.

**Comment by shirouzu** [comment]
domyslny-san,
Under those conditions, it must be done more than once.

 Source: C:\\
 DestDir: D:\\FastCopy\\DriveC\\

 Source: E\\
 DestDir: D:\\FastCopy\\DriveE\\

 or etc.

a-raccoon-san,
> It doesn't seem possible and would appear to be an oversight (bug) in the software in accordance with the The last character of DestDir is '\' documentation.

Sorry, I did not understand what you wrote.

**Comment by domyslny** [comment]
Thank you for your answer. I would like it to be possible to set different target directories when copying several drives, but I understand that you are the author of the program and you decide what functions it will have. Anyway, thank you for clarifying my question and I wish you a lot of fun developing your software.
