### ISSUE TITLE
About /verifyinfo when executing in command line mode

### ISSUE THREAD

**Issue by ghost** [FastCopyLab/FastCopy#224]
Hi, By default settings, /verifyinfo is not enabled when specified on the command line.
Must be enabled in the main settings with Add verifyinfo. checked.
Is it a specification?

p.s.
sorry, issued below URL by mistake.
https://github.com/shirouzu/FastCopy/issues/7

**Comment by shirouzu** [comment]
Thank you for your report.
I will fix it in the next version.
