### ISSUE TITLE
NW越しに副次ストリーム付きでコピーすると遅い

### ISSUE THREAD

**Issue by hatachu-jp** [FastCopyLab/FastCopy#226]
**エラー内容**
問題の内容を記述
エクスプローラーでコピーしたときの２倍時間がかかる。

**再現方法**
再現手順を列挙
Source は UNC パス。
Dest はローカルPCのデスクトップ上のフォルダーを指定。
「副次Stream」にチェックを入れて、実行。

**コマンドライン・オプションや各種設定**
コマンドライン・オプションや標準から変更している設定項目などを記述
Source の UNC パス先には、ブラウザーでダウンロードした際に付く Zone.Identifier の副次ストリームが付いたファイルなどが六千個。合計数ギガバイト。

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : 5.3.1
OS ver: Windows 11 Pro 22H2　2023年9月のWindowsUpdate適用済み。

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット

**Comment by shirouzu** [comment]
現象を確認しました。
複数の要因があるようで、
・Win10以降の Microsoft Defender が速度低下の原因（Defender OFF or Win7では遅くならない）
　ただし、Explorer がその悪さから逃れている要因は不明（調査中）
・FastCopy側の実装制約から、副次ストリームONの場合のみ、マルチスレッド並列Openを無効化している。
の２つが効いているようですね。

常に前者が足枷になっているのですが、副次ストリームOFFの場合はマルチスレッド並列Openによって足枷を事実上隠蔽できていた、という状態のようです。
次のバージョンで解決できるかどうかはわかりませんが、ともあれ何らかの対策を考えてみます。

**Comment by shirouzu** [comment]
v5.4.0以降である程度、改善しておきました。
（副次ストリーム有効時もマルチスレッド並列openを有効化）

**Comment by hatachu-jp** [comment]
v5.4.1 で改善したことを確認しました。
ありがとうございます！
