### ISSUE TITLE
Delete excluded files/folders from destination directory

### ISSUE THREAD

**Issue by venusz** [FastCopyLab/FastCopy#227]
**Describe the solution you'd like**
In sync mode, if the excluded files or folders exist on the destination, they will not be deleted. If the exclusions could be treated as if they did not exist in the source directory, they would be automatically deleted from the destination. So it would be nice to have an option to delete existing exclusions from destination.

**Additional context**

**Comment by shirouzu** [comment]
It is consistent behavior to exclude Exclude-specified files and directories both as targets for copying and for deletion.
Deleting it at the destination, even though it is Exclude-specified, would appear to be unexpected behavior.

**Comment by Jerryzhao83** [comment]
> **Describe the solution you'd like** In sync mode, if the excluded files or folders exist on the destination, they will not be deleted. If the exclusions could be treated as if they did not exist in the source directory, they would be automatically deleted from the destination. So it would be nice to have an option to delete existing exclusions from destination.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

if you want this sync function，maybe you can try freefilesync or goodsync , they are good at sync area.

**Comment by venusz** [comment]
@Jerryzhao83 thank you for the advice but I chose rclone.
