### ISSUE TITLE
a new copy mode demand, "rename mode" or “version mode”

### ISSUE THREAD

**Issue by Jerryzhao83** [FastCopyLab/FastCopy#228]
**Describe the solution you'd like**
Fastcopy is the best copy software，I have used。
I use it to copy a mount of files。
There is  a function could you consider it。
I call it “rename mode” or "version mode" .
if a file both in the source dir and the target dir , they have the same file name , but different content 、time mark etc.
I  want to keep both version，and add a datetime behind the file name  in the target dir.

The process is 
1. check if the target dir have same name file .
2. rename the target file name as " filename-datetime" , the "datetime" may be the target file's time mark or the copy action datetime.
3. copy the source file to the target dir.

thank you for your considering  .
best wishes for you.

**Additional context**

**Comment by shirouzu** [comment]
Thank you for your request.
I will consider it.
