### ISSUE TITLE
ログファイルの文字コードに関して

### ISSUE THREAD

**Issue by shiba3901** [FastCopyLab/FastCopy#23]
**質問**
新しいバージョンのログ設定に於いて、今まであった

□ログはUTF-8を利用

のCheckをOff/Onの選択するオプションがありません。

新しいバージョンには、ログファイルをSJISなどに設定する機能はないのでしょう？

**備考**
以前のバージョン
![image](https://user-images.githubusercontent.com/98793563/151909597-25c4d6d9-bc56-4f58-87c2-110764860c04.png)

**Comment by shirouzu** [comment]
UTF-8のみに統一しました。
SJISが必要な場合、ご自分で変換して頂ければと思います。

**Comment by shiba3901** [comment]
回答ありがとうございます。

＞UTF-8のみに統一しました。
＞SJISが必要な場合、ご自分で変換して頂ければと思います。

了解しました。
