### ISSUE TITLE
移動モードでエラーが発生した場合に続行できない問題

### ISSUE THREAD

**Issue by Honoka55** [FastCopyLab/FastCopy#230]
**エラー内容**
ファイルを`移動（全上書き）`モードで移動中に、巡回冗長検査 (CRC) エラーが発生した場合、エラーを無視しても残りのファイルが正しく移動できない問題が発生しています。`移動（全上書き）`モードで`エラー時継続`をオンにしても、複数のファイルを選択し、移動中にCRCエラーが含まれるファイルが処理される際に、エラーログが表示されるものの、その後の移動が中断され、エラーのあるファイルで進行が停止します。しかし、動作モードを`差分（サイズ・日付）`に変更すると、エラーを無視して残りのファイルのコピーを続けることができます。

**再現方法**
1. FastCopyを起動します。
2. `移動（全上書き）`モードを選択します。
3. CRCエラーのあるファイルを含む、複数のファイルを指定します。
4. 移動中に、CRCエラーのあるファイルが処理される際、作業の進行が停止します。

**コマンドライン・オプションや各種設定**
特別な設定は行っていません。

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : 5.4.1
OS ver: Windows 11 22H2

**スクリーンショット**
下記をご覧ください。

![QQ截图20231001161051](https://github.com/FastCopyLab/FastCopy/assets/71088406/8541ff72-38f0-42d7-aad0-846544b86993)
![QQ截图20231001161944](https://github.com/FastCopyLab/FastCopy/assets/71088406/833a9687-b49e-4329-b71a-6edcad566ce1)

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
現象を確認できたので、次のバージョンで修正する予定です。

**Comment by shirouzu** [comment]
v5.4.2 で修正しておきました。
