### ISSUE TITLE
Animation restarting instead of unpausing, animation button in the wrong state when changing settings group (trivial)

### ISSUE THREAD

**Issue by neube3** [FastCopyLab/FastCopy#231]
**Describe the bug**
Animation playback in the "At minimised" - for lack of a better term - settings group in Main Settings (e.g. "Defaults", "I/O Settings", (...), "At minimized").

**To Reproduce**
Steps to reproduce the behaviou1r:
1. Open Main Settings/At minimized
2. Click on the green "Play" arrow under the animation.
3. Before the animation finishes, click on any other settings group in the left pane, e.g. "Disp Customize".
4. Click on "At minimized" settings group again.

Result: 
• Animation playback is paused without the button changing back to "play" state (it is in "pause" state)
• Animation playback is restarted from the beginning when pressing the "pause" button in this pause-by-changing-settings-group state
• Bug does not persist between animation cycles - occurs only one time for each completed animation

**Version/Environment**
 - FastCopy Pro 5.3.1
 - W10 Pro x64, 21H2 (19044.3086)

**Comment by shirouzu** [comment]
We have checked and it is a minor issue and will fix it when we get a chance.
