### ISSUE TITLE
Allow modifier+click on filter for opening extended filters just one time

### ISSUE THREAD

**Issue by neube3** [FastCopyLab/FastCopy#232]
**Describe the solution you'd like**
In Main Settings/Defaults, there is option "Always show extended filter. (timestamp/size filter)". 

This option is currently the only way to display the extended filters [for the first time in current job; if a job is saved with an extended filter used, loading such job will display the extended filters even if the option is unchecked in the menu - which is both brilliant and the only proper way to do it :)].

I propose allowing ctrl+click or shift+click (whichever you think is more consistent with the rest of the modifier+click behaviours in the program) on the filter tickbox for opening the extended filter just once, without having ticked the option in settings.

**Comment by shirouzu** [comment]
Thank you for your suggestion.
I will consider it.
