### ISSUE TITLE
Start backup/sync job automatically upon program launch

### ISSUE THREAD

**Issue by dhsewell** [FastCopyLab/FastCopy#234]
**Question**
Describe your question.
(Please do not ask anything that you can figure out by experimenting at hand).
I have tried experimenting to figure this out. I feel the answer must be obvious but I am just not getting there. Using the Windows task scheduler, I can launch the FastCopy program on schedule, but the backup/sync job never launches unless I go ahead and launch it manually. I need the program to be able to launch automatically every day at a set time.

**Remarks**
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
Please describe the task scheduler settings.
Also, if an fastcopy error log is recorded, please describe its contents.

**Comment by dhsewell** [comment]
You closed this ticket before I had a chance to respond. I launch the
program from task scheduler. I launch the fastcopy executable with no
command switches. It launches the program successfully but the sync job
does not start automatically like I need it to. Can you help me with this
please?

**Comment by shirouzu** [comment]
Please describe the exact steps and parameters that I can reproduce.

**Comment by dhsewell** [comment]
I will do that later today when I get back to my computer. I don't think
their is anything wrong with your product but rather I don't have the
knowledge to create a batch file to launch the sync job. I can launch the
fastcopy program but it just sits there until I manually execute the sync
job. I will take screenshots and send them to you.

**Comment by dhsewell** [comment]
This is what I have set up in task scheduler to start the FastCopy sync job
automatically. What am I doing wrong?

[image: image.png]
David Sewell

“A kind gesture can reach a wound that only compassion can heal.”
― Steve Maraboli
<http://www.goodreads.com/author/show/4491185.Steve_Maraboli>, Life, the
Truth, and Being Free <http://www.goodreads.com/work/quotes/14708444>

**Comment by shirouzu** [comment]
The image is not showing.
It seems that github does not reflect image attachments by email on the board.

**Comment by dhsewell** [comment]
How do I add a command to automatically launch the sync job and what
command do I use?

**Comment by shirouzu** [comment]
I do not know what procedures and details you have done.
Please describe it in detail.
If I don't know how to reproduce it, I can't advise you.

**Comment by dhsewell** [comment]
Then please simply tell me how to automatically launch a sync job. I will
uninstall and reinstall the program. I want to have one hard drive mirror
another hard drive once a day overnight when the computer is not being used
and the computer is unattended. Thank you

**Comment by shirouzu** [comment]
Please see.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

and please search "task scheduler usage"
