### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by eagleman** [FastCopyLab/FastCopy#237]
### Discussed in https://github.com/FastCopyLab/FastCopy/discussions/229

<div type='discussions-op-text'>

<sup>Originally posted by **eagleman** September 28, 2023</sup>
Hello
I would like to add the italian language to Fastcopy.
What I have to do to add the new strings?
Let me know</div>

**Comment by shirouzu** [comment]
Thank you for your suggestion.
We will consider it.
(As a rule, FastCopyLab, LLC. is responsible for adding languages.)
