### ISSUE TITLE
FastCopy in Polish.

### ISSUE THREAD

**Issue by piotrtrkostrzewski94** [FastCopyLab/FastCopy#239]
Good evening / Good morning.
I would like to translate FastCopy into Polish.
Here is my portfolio:
https://www.artstation.com/piotrkostrzewski4/profile
Thank you very much for hour time.
Regards,
Piotr Kostrzewski

**Comment by oscarsun72** [comment]
Thank you very much. What a World like this, not only wars on our planet. 感恩感恩　讚歎讚歎　南無阿彌陀佛

**Comment by shirouzu** [comment]
Thank you. I will consider it.
https://github.com/FastCopyLab/FastCopy/issues/237

Please do not post anything irrelevant to FastCopy. > oscarsun72-san
(No need to reply)

**Comment by piotrtrkostrzewski94** [comment]
Thank you very much.  If necessary, I will be happy to translate.
