### ISSUE TITLE
Why Fastcopy does not move files on the destination?

### ISSUE THREAD

**Issue by auanasgheps** [FastCopyLab/FastCopy#24]
**Question**
Hello, I have a question regarding moving files

When I move a file/folder on a source and attempt to sync to a destination, my FastCopy does not detect the file has been moved. Instead, it deletes the file from the old destination and copies it to the new one.

This is a waste of resources in my opinion, especially if we consider that many times (not always) move operations are "free" for the file system.

I have observed this behaviour when moving big files.
Example of a test file which has been moved.
![immagine](https://user-images.githubusercontent.com/20586878/152041916-e7e02889-f344-43b8-8de2-b52b8e17554c.png)

I am running Windows 10 and FastCopy 4.0.3

**Remarks**
Am I doing anything wrong or FastCopy does not have this feature?

**Comment by shirouzu** [comment]
Yes.
I recommend to use to move in same drive with explorer :-)

**Comment by auanasgheps** [comment]
This can be done with one file, but not with many changes. 
Thanks for the answer.
