### ISSUE TITLE
Use fastcopy as default copy handler

### ISSUE THREAD

**Issue by nOrphf** [FastCopyLab/FastCopy#240]
**Describe the bug**
As I understand https://github.com/FastCopyLab/FastCopy/issues/114 then replace of windows explorer has been implemented.
When pressing ctrl+c and then ctrl+v or doing drag and drop fastcopy dosn't replace windows explorer

**To Reproduce**
Do a ctrl+c and ctrl+v or drag and drop

**Command line options and various settings**
none

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.4.2
 - OS ver: Windows 11 23H02

**Screenshots**
![image](https://github.com/FastCopyLab/FastCopy/assets/54571822/cfe9d433-2db2-4803-8360-4b2c1faf3f9d)

**Comment by shirouzu** [comment]
Sorry, this function has not been implemented.
https://github.com/FastCopyLab/FastCopy/issues/203

**Comment by shirouzu** [comment]
https://github.com/FastCopyLab/FastCopy/issues/192#issuecomment-5339064796
