### ISSUE TITLE
FastCopy in "Send to"

### ISSUE THREAD

**Issue by nOrphf** [FastCopyLab/FastCopy#241]
Hi

At the moment I have a shortcut to a folder in "Send to" right-click menu (shell:sendto).
To easily copy files to a that specific folder.

Is it possible to create a shortcut to FastCopy in "Send to" so fastcopy copies the selected file(s)/folder(s) to a predefined folder?

Hope it makes sense :)

Regards Lars

**Comment by shirouzu** [comment]
It's a little trick using "job", and it's possible.

1. Run FastCopy for registering a "job"
1.1 Empty "Source" field.
1.2 Specify the appropriate folder for "DestDir".
1.3 Select "Add/...Job" of "JobMng" in the Menu, and register it with an appropriate name such as "sendto_job".

2. In the properties of the FastCopy shortcut placed in sendto, write <path>fastcopy.exe /auto_close /job=sendto_job.

**Comment by nOrphf** [comment]
Works like a charm! - Thanks!

**Comment by mesteele** [comment]
I have no problem doing  1 but 2 when I do a shell:sendto there is no fast copy shortcut in there?
