### ISSUE TITLE
Adding Send To option

### ISSUE THREAD

**Issue by mesteele** [FastCopyLab/FastCopy#243]
**Describe the solution you'd like**
Please add the ability to "Send To" in the context menu options.  

**Additional context**
![2023-11-27_19-42-10](https://github.com/FastCopyLab/FastCopy/assets/12111398/3d428587-699e-4d5c-b9f4-5af43e61ece1)
****

**Comment by shirouzu** [comment]
This can be done by creating a shortcut to FastCopy. (open shell:sendto in explorer)
See also, https://github.com/FastCopyLab/FastCopy/issues/241

**Comment by shirouzu** [comment]
> I have no problem doing 1 but 2 when I do a shell:sendto there is no fast copy shortcut in there?

You will need to create your own shortcut.
Search for "How to create a shortcut file" on Google or other search engines.
