### ISSUE TITLE
Difficulty copying from remote USB 3 drive to PC

### ISSUE THREAD

**Issue by BlueGunk** [FastCopyLab/FastCopy#244]
My copy process (copy overwrite) is giving me this

ReadFile(The semaphore timeout period has expired.121) : N:\Videos\Lively Wallpaper MP4s\Live Wallpaper and Screensavers\0951p.mp4

I had no problem copying from PC to the external drive.  Is there any way I can prevent this error?  Both drives are SSD.

Thank you.

**Comment by shirouzu** [comment]
This error occurs when either the storage itself or its communication (e.g. USB) has a problem.
Therefore, there is not much that can be done on the FastCopy side. The only symptomatic remedy is to use a slower speed setting.

You can search for something like "Semaphore timeout USB Windows".
You will find many similar cases.

**Comment by BlueGunk** [comment]
Thank you for your quick reply. I have been looking into it further myself and appreciate your reply! As you say, it's not a FastCopy problem. Thank you for your suggestion; I shall try that among other things.
