### ISSUE TITLE
"Daylight Saving Time DST" problem (= "1 hour exact difference" problem)

### ISSUE THREAD

**Issue by MM-John** [FastCopyLab/FastCopy#25]
Following up on these google groups issues:

https://groups.google.com/g/fastcopy-bb-eng/c/0ovpgsRc66E/m/ItX7q7-yAQAJ

and

Is the DST problem fixed in FastCopy v. 3.40? (answer: yes)
https://groups.google.com/g/fastcopy-bb-eng/c/IAitTRfFojY/m/woRXcWvgCAAJ

What is the new option. I can't seem to find it in the Option -> Main Settings nor the `FastCopy2.ini` file.

**Comment by shirouzu** [comment]
The option is below.
![image](https://user-images.githubusercontent.com/1759911/152084866-dd5576d4-7989-4262-9e0e-f39f82f3ad55.png)
