### ISSUE TITLE
Softlink Replication Support

### ISSUE THREAD

**Issue by taozhiyu** [FastCopyLab/FastCopy#250]
**Describe the solution you'd like**

The software works great, using the copy that comes with windows I waited half an hour and was still stuck calculating the size, whereas with FastCopy it took almost 2 minutes!

But it seems that all the softlinks can't be copied, so I need to create them manually one by one. I sincerely hope that automatic softlink creation is supported!

**Additional context**

More info about softlink can be found [HERE](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links)

Anyway, thanks a lot!

**Comment by shirouzu** [comment]
??
FastCopy supports symbolic links.

However, the standard Windows environment requires administrator privileges for symlink creation.
To perform symlink creation without administrative privileges, Windows settings must be changed.

Please see. (use gpedit or use fsutil behavior set symlinkevaluation)
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links#group-policy

**Comment by taozhiyu** [comment]
Thanks, I'll try using UAC next time.
