### ISSUE TITLE
ディレクトリデフラグ

### ISSUE THREAD

**Issue by SysVR** [FastCopyLab/FastCopy#251]
**機能リクエスト内容**
機能が機能なので要望というより提案に近いです。

簡易・全領域事前確保
コピー先のコピーサイズを全領域分事前割り当てしてからファイルを書き込みます。
NTFSでは現状の事前割り当て方式を利用して一気に生成します。
※空ディレクトリを一度に作成後、事前割り当て用のファイルをすべて作成してから書き込みます。
これにより断片化を防げます。
キャンセルを行った場合は事前書き込みデータを削除するか保持するか確認できます。

詳細・コピー後デフラグ
コピー完了後にディレクトリをデフラグして全ファイルを連続化させます。

完全・モニタリングを開始、終了までの間にデータが読み込まれた順にファイルを配置しなおします。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
検討しておきます。
