### ISSUE TITLE
詳細フィルタ

### ISSUE THREAD

**Issue by SysVR** [FastCopyLab/FastCopy#252]
**機能リクエスト内容**
ACL属性やATTRIB属性を指定可能にする。

ATTRIB属性(Microsoft Windows [Version 10.0.22631.2861] cmdより)
  R   読み取り専用ファイル属性。
  A   アーカイブ ファイル属性。
  S   システム ファイル属性。
  H   隠しファイル属性。
  O   オフライン属性。
  I   非インデックス対象ファイル属性。
  X   スクラブ ファイルなし属性。
  V   整合性属性。
  P   固定属性。
  U   固定解除属性。
  B   SMR BLOB 属性。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
ACLをチェックすると、BackupRead/Write で再現可能な属性とACLが再現されるようになっています。
個別指定は、今後検討します。
