### ISSUE TITLE
同期（ベリファイ比較）の追加希望

### ISSUE THREAD

**Issue by walterkammi** [FastCopyLab/FastCopy#253]
**機能リクエスト内容**
linuxのrsyncのような、「同期（ベリファイ比較）」の機能を希望します。FastCopy以外でコピーを仕損じた場合、日付とサイズは同一だけれどファイルの中身が違うということに遭遇したりです。速度の問題があるのであれば、日付とサイズが同じときのみベリファイ比較コピーで日付とサイズが異なっていればそのまま既存のベリファイコピーも一案です。期待しております。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
うーん、ちょっと大変そうですねぇ。
検討しておきます。

**Comment by walterkammi** [comment]
shirouzuさま、
walterkammiです。 お世話になります。
実は、大昔、別のアカウントより、verifyコピーの追加をお願いしました。今だ、便利に使わせていただいております。それもあって、Proライセンスも自分が使っているwin機の分オーダーさせていただきました。
いままではファイル数が少ないときはcygwin+rsyncでしのいだこともあったのですが、複数win機の同期をかけるようになって、やはり、追加の機能があればと思うようになりました。
もし、ベータ版ができましたら、ぜひテストさせてください。
よろしくご検討のほど、お願いします。
