### ISSUE TITLE
ログファイル内容とACLについて

### ISSUE THREAD

**Issue by Kobayasi3** [FastCopyLab/FastCopy#255]
**質問**
実機操作：
Ver.5.2.4を使用、ドメイン環境でACLを含むコピーを実施しました。
ログを精査する必要があります。
確認したい事項：
1. ログ内容に、ACLの付与に関連するエラーは存在しますか
2. ログに記録されたTotalDel、DelFiles の意味をご教示ください。

また、ログファイルの出力内容についての説明がありましたら、
入手方法をご教示ください。

どうぞ宜しくお願いします。

**備考**
ログサンプル：
=================================================
FastCopy(ver5.2.4 (NoUI)) start at 2023/08/11 04:06:00
<Source>  \\10.***.***.5\AAAAAAA\
<DestDir> \\10.***.***.5\vol2A$\AAAAAA
<Command> 同期（サイズ・日付） (with Verify ACL AltStream)
-------------------------------------------------
CreateFile(ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。123) : \\10.***.***.5\vol2A$\[パス省略]\LC-Dispenser\DEMO\2011-06-08\BBB򎑗110526.pdf

TotalRead  = 8,153 MiB
TotalWrite = 8,153 MiB
TotalFiles = 4,617 (364)
TotalSkip  = 10,052,248 MiB
SkipFiles  = 17,325,973 (0)
TotalDel   = 1,511 MiB
DelFiles   = 594 (109)
TotalTime  = 02:43:06
TransRate  = 1.38 MB/s
FileRate   = 0.75 files/s
VerifyRead = 8,153 MiB
VerifyFiles= 4,617

Result : (ErrFiles : 1 / ErrDirs : 0) at 2023/08/11 06:49:07

**Comment by shirouzu** [comment]
基本的にご質問は最新版のみ受け付けます。
下記は最新版についてと思ってください。

> ログ内容に、ACLの付与に関連するエラーは存在しますか

設定のログ設定に依存します。
詳しくはヘルプを参照してください。
https://fastcopy.jp/help/fastcopy.htm#setting_log

> ログに記録されたTotalDel、DelFiles の意味をご教示ください。

そのままの意味です。
またカッコの意味はこちらを参照のこと。
https://fastcopy.jp/help/fastcopy.htm#usage

> ログを精査する必要があります。

業務でお使いと思いますが、すみませんが、手取り足取りの高額有料サポートは提供しておりません。
可能な限り、調査＆推測した上で、なお不明な点があれば（調査結果を明示の上）ご質問ください。

**Comment by Kobayasi3** [comment]
早急なご教示有難うございます。
基本的な質問で、ご迷惑かけました。
今後とも、宜しくお願いします。
