### ISSUE TITLE
Copy corrupted file and preserver

### ISSUE THREAD

**Issue by Alexandre-MTNogueira** [FastCopyLab/FastCopy#256]
**Question**
Describe your question.
I need you to copy the file from the source to the destination, if the file on the destination has the same date it must be overwritten on the destination, if it is newer it must not change. You must do this for the subdirectories, but if you have a subdirectory with files in the source and empty in the destination, it should not copy.This is because files were corrupted during copying, but they are ok at the source and over time some documents are being edited and updated and I cannot overwrite edited documents that have the same name.

**Comment by shirouzu** [comment]
This looks like a special use just for you.
Please read the FastCopy manual carefully and consider coming up with your own method or using another tool.

> You must do this...

Sorry, but this is your problem. We are unrelated.
