### ISSUE TITLE
Unable to run FastCopy Pro, tried many different ways

### ISSUE THREAD

**Issue by jvpulver** [FastCopyLab/FastCopy#257]
Dear Technical Support-san,

I have two external 14 TB USB drives. The Source has 7.52 TB of data on it and the DestDir is new and has no data on it.

I want to back up the Source. Below is a screen shot showing the two USB drives. I installed FastCopy on a stand-alone system. How do I tell FastCopy how to copy all of the files from the Source. Below is one of the ways I tried. In addition, what other options can I use to make to make FastCopy run faster. Nothing else would be running on that system. The system is an Intel i5-9400 with 32 GB of RAM.

![2024-01-18 01a How do I run FastCopy](https://github.com/FastCopyLab/FastCopy/assets/56042944/1e846177-1982-42c3-8732-4f2f33f00a08)

**Comment by shirouzu** [comment]
If you want to do a full back up of H drive, do this.
```
Source  is H:\
DestDir is F:\ (or F:\a\)
```
You can leave the other options at their default values.

**Comment by jvpulver** [comment]
Dear Hiroaki SHIROUZU-san,

That is the first thing I tried. I thought it was not working as I saw no files copied. I then realized it was working. I have so many files it was taking a long time to copy them. I ran it again and it took 7 hours to run. However, only a portion of the files were copied. I deleted some of the files in the source folder and are re-running FastCopy. I have 7.48 TB of data. How long do you think it will take to copy all of it. 

 This is how I am running FastCopy.

Would it help if I increase Buffer(MB)?

ありがとうございま.

 Sincerely,

 Jeff
~~~~~~~~~~~~~~~~~ 
Jeff V. Pulver
IT Consultant

**Comment by shirouzu** [comment]
> However, only a portion of the files were copied.

Was there an error?
It is difficult to imagine that the copy is not being copied even though there is no error, so if this is the case, please provide a specific example.

> How long do you think it will take to copy all of it.

It depends on the file size (larger is faster), hardware performance (NVMe is faster, HDD is slower), and the total number of files and total file size.

> Would it help if I increase Buffer(MB)?

Not having enough buffers will slow things down, but increasing them more than necessary won't make things faster.
I think 512MB is usually enough.

P.S. I would like it if you could post via web/URL instead of using email for replies. This is because the format is easily distorted. https://github.com/FastCopyLab/FastCopy/issues/257

**Comment by jvpulver** [comment]
The copy which failed gave no error message. To speed up the copying I deleted some files from the source and restarted FastCopy Pro. Attached are some statistics while FastCopy Pro is running. Where is the Source file size shown? Also where is the size of the files copied to the DestDir shown? The size of the Source is 7.48 TB. The Source and DestDir are external HDDs connected to a USB 3.0 port. They are running on a system with no other tasks running. The specifications on that system are attached. Do you have enough information to give an approximate time for all of the files to be copied? Thank you.
![2024-01-21 After 27 hours w-system specs](https://github.com/FastCopyLab/FastCopy/assets/56042944/ab1323dc-6910-4735-9627-da4a675513d2) Thank you. Jeff V. Pulver

**Comment by shirouzu** [comment]
If you want to record each copied file, please check the item "Write to File Log" in the log settings.
This file can be opened from the "File" menu item -> "Open LastFileLog".

![image](https://github.com/FastCopyLab/FastCopy/assets/1759911/c31090ec-66c8-4d56-9f42-364ff5a70e8f)
