### ISSUE TITLE
FastCopy do not respect path selection 

### ISSUE THREAD

**Issue by Dodutils** [FastCopyLab/FastCopy#259]
**Describe the bug**

If I select a source for example G:\DCIM\ and destination like F:\RX10Pics\DCIM\ FastCopy will try to find some  F:\RX10Pics\DCIM\DCIM\ to compare to and if I start synch it will create a DCIM subfolder inside the DCIM and push all files inside it, this is unexpected behavior, "G:\DCIM\\" with a backslash at the end means "content of DCIM", not DCIM folder itself.

To fix that I set F:\RX10Pics\ as destination so Fastcopy will find the DCIM inside RX10Pics but this is not the way it should work.

**To Reproduce**

All info needed in description to reproduce

**Command line options and various settings**

Standard options.

**Version/Environment**

 - FastCopy ver (principle, latest ver) : 5.5 but I also tested with older versions down to 3.9.3 so I guess this is a very old behavior
 - OS ver: Win 10

**Screenshots**

 No screenshot needed

**Comment by shirouzu** [comment]
This is specification.
You can set DestDir to F:\RX10Pics\ or F:\RX10Pics\DCIM (Do not add a trailing \) .
Please check this out for details.
https://fastcopy.jp/help/fastcopy_eng.htm#backslash_behavior
