### ISSUE TITLE
意図せず、Ver.4.2.2⇒Ver.5.5.0に替わってしまう。職場使用は？

### ISSUE THREAD

**Issue by anaaki88** [FastCopyLab/FastCopy#260]
**エラー内容**
職場で使用するPCに、Ver.4.2.2 をインストールし、
初日(1/17)の数回は、Ver.4.2.2 で動作しましたが、
数日後(1/23)に、（Ver.が変わっていないのを確認した上で）
FastCopy.exe をダブルクリックすると、
一旦、Ver.4.2.2 で起動した後、直ぐに終了してしまい、
直後に自動で起動したものの、Ver.5.5.0に替わってしまっていました。

**再現方法**
・fastcopy-4-2-2.exe を実行し、インストール
・インストール先の FastCopy.exe を実行
・数日後に、同様に FastCopy.exe を実行

（たぶんですが、２回発生していると思います。
　1/17 の１～２週間前に fastcopy-4-2-2.exe を実行、
　その時は、「展開のみ」だったかと思うのですが、
　後日、Ver.5.4.x に替わってしまっていました。

　間違えて、個人用の Ver.5.4.3 を実行した可能性も
　否定し切れなかったので、一旦アンインストール、
　そして、間違いなく、astcopy-4-2-2.exe を実行して
　FastCopy.exe 実行の都度、タイムスタンプを確認
　1/17 及び、1/23 の実行前は、2023/02/07 13:40
　1/23 の実行後は、2024/01/14 16:39 ）

**コマンドライン・オプションや各種設定**
インストール先：C:\FreeSoft\Sys_Free\fastcopy-4-2-2

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :Ver.4.2.2/Ver.5.5.0
OS ver:Win10Home 22H2 x64

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット

![FastCopy_log](https://github.com/FastCopyLab/FastCopy/assets/157566483/a0493b2c-b906-4fc7-b297-10c28e3b722d)

**Comment by shirouzu** [comment]
v4.x は既にサポートされておらず、ご使用はお勧めできませんが、設定→その他にある「起動時に自動アップデート」をOFFにすれば自動アップデートされることはありません。

**Comment by anaaki88** [comment]
「バグ」では無く、「仕様」（初期設定は自動アップデートON）だったのですね。ラベルを「質問」にするべきでした。失礼致しました。

回答をありがとうございました。
