### ISSUE TITLE
ライセンスキー認証の件

### ISSUE THREAD

**Issue by cynbinytt** [FastCopyLab/FastCopy#263]
ライセンスキー認証の件

>v5.5.0以降、OS再インストールでもマシンIDが変化しない、
>新しいライセンス認証形式に移行しました。
>従来型式の認証のままでもお使いいただけますが、
>万一のOS再インストールに備えて、新形式に移行することをお勧めします。

PCは自作です
OS再インストールは山の様にします（年間数十回？）

CPUを変えても「マシンID」は変化しませんか？
メモリ換装は？
SSD換装は？

何を変えると「マシンID」が変化してしまうのか、、心配です

**Comment by shirouzu** [comment]
再インストール前やマシン移行前には、ライセンスを開放しておくのが基本です。
https://fastcopy.jp/help/fastcopy.htm#license_manager
その場合は、マシンIDが変化しても何の問題もありません。
今回の変更は万一のクラッシュ等で、事前のライセンス開放ができなかった際の救済用と思ってください。
