### ISSUE TITLE
スキップエラー？ご愛敬程度です

### ISSUE THREAD

**Issue by cynbinytt** [FastCopyLab/FastCopy#264]
スキップエラー？
Fastcopy ver5.5.0 64bit
Windows10

ご愛敬程度です
2回実行したら、1回目に追加されたはずのファイル２つが、再度追加されたと表示されました
ちなみに「D:」はSSDで、コピー直前にフォーマットしたので100%空です
「ベリファイ情報を付与」はチェック☑しています

■1回目Adminでやらなかったので、６つアクセスできずエラー
=================================================
FastCopy(ver5.5.0) start at 2024/01/24 06:27:31
<Source>  G:\new.txt; G:\vi.txt; G:\メンテ2; G:\back; G:\A; G:\test; G:\eos; G:\New; G:\temp; ....中略.......
<DestDir> D:\
<Command> 差分（サイズ・日付） (with Verify)
-------------------------------------------------
 中略
+ D:\メンテナンスソフト2\Driver\プリンター\G1310\CD\win\QUICK\Res\String\EC_Bulgarian.ini   <20170705-134344 268 xxh3=844f39aeb4bb86959f4eb5b5166df7e5>
+ D:\メンテナンスソフト2\ユーティリティ\ファイル操作\使える〇〇〇〇〇〇\〇〇〇〇〇〇〇〇\〇〇〇〇リーム\〇〇〇〇〇〇〇\Ver1\OLD\〇〇〇ash-devv2\.gitattributes   <20220119-101919 167 xxh3=7162d9b41ebdf74d0d18309566470dea>
 中略
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20231211copilot30Win11-23H2PT3Work-kb5032190.〇〇〇x
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20231209copilot30Win11-23H2PT3Work-kb5032190.〇〇〇x
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20231127Win11-23H2nodriversvcSFCrepair.〇〇〇x
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20231115Bing30Win10-22H2PT3Work-KB5032189.〇〇〇x
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20231104Win11-23H2nodriversvcSFC.〇〇〇x
OpenFile(アクセスが拒否されました。5) : G:\WD〇〇〇〇20230628-2Bing5Win10-22H2PT3Work-KB5027215.〇〇〇x

TotalRead  = 359,770 MiB
TotalWrite = 359,770 MiB
TotalFiles = 189,577 (34,376)
TotalTime  = 53:53
TransRate  = 116.8 MB/s
FileRate   = 58.7 files/s
VerifyRead = 359,770 MiB
VerifyFiles= 189,577

Result : (ErrFiles : 6 / ErrDirs : 0) at 2024/01/24 07:21:24

-----------------------------------------------------------------------------
　↓ 仕方ないので、3分後 Adminに変えて再度「実行」
-----------------------------------------------------------------------------

■2回目Adminにして再度実行、エラーになった６つにアクセスできてOK完了
ところが、ご愛敬？で、上段２つのファイルを再度追加したとでた！
（1回目でちゃんと追加済だったのに）

=================================================
FastCopy(ver5.5.0 (Admin)) start at 2024/01/24 07:24:34
<Source>  G:\new.txt; G:\vi.txt; G:\メンテ2; G:\back; G:\A; G:\test; G:\eos; G:\New; G:\temp; ....中略.......
<DestDir> D:\
<Command> 差分（サイズ・日付） (with Verify)
-------------------------------------------------
+ D:\メンテナンスソフト2\Driver\プリンター\G1310\CD\win\QUICK\Res\String\EC_Bulgarian.ini   <20170705-134344 268 xxh3=844f39aeb4bb86959f4eb5b5166df7e5>
+ D:\メンテナンスソフト2\ユーティリティ\ファイル操作\使える〇〇〇〇〇〇\〇〇〇〇〇〇〇〇\〇〇〇〇リーム\〇〇〇〇〇〇〇\Ver1\OLD\〇〇〇ash-devv2\.gitattributes   <20220119-101919 167 xxh3=7162d9b41ebdf74d0d18309566470dea>
+ D:\WD〇〇〇〇20231211copilot30Win11-23H2PT3Work-kb5032190.〇〇〇x   <20231211-194316 17,586,470,912 xxh3=cbf6bd17cf1f5136a7c43a981f166191>
+ D:\WD〇〇〇〇20231209copilot30Win11-23H2PT3Work-kb5032190.〇〇〇x   <20231209-202441 15,724,236,800 xxh3=b79df430f24d3d4532c9c707db8ef9cd>
+ D:\WD〇〇〇〇20231127Win11-23H2nodriversvcSFCrepair.〇〇〇x   <20231127-164646 6,172,565,504 xxh3=b957275258a4e740401a7b8326433a90>
+ D:\WD〇〇〇〇20231115Bing30Win10-22H2PT3Work-KB5032189.〇〇〇x   <20231115-151143 19,706,515,456 xxh3=eec18fd40c67835c69744685ce960d74>
+ D:\WD〇〇〇〇20231104Win11-23H2nodriversvcSFC.〇〇〇x   <20231104-200504 6,137,913,344 xxh3=64324acd9176e82eea2b3bc44f247ada>
+ D:\WD〇〇〇〇20230628-2Bing5Win10-22H2PT3Work-KB5027215.〇〇〇x   <20231102-170339 16,253,468,672 xxh3=d3e77ca429cc5e00b1651b26db5fb0b0>

TotalRead  = 77,801 MiB
TotalWrite = 77,801 MiB
TotalFiles = 8 (0)　←「6」の予想だったが、ふたつ増えていた？？
TotalSkip  = 359,770 MiB
SkipFiles  = 189,575 (0)　←1回目「189,577」ベリファイしたのに、▼2つ減った？？
TotalTime  = 08:28
TransRate  = 160.9 MB/s
FileRate   = 0.02 files/s
VerifyRead = 77,801 MiB
VerifyFiles= 8　←「6」の予想だったが、ふたつ増えていた？？

Result : (ErrFiles : 0 / ErrDirs : 0) at 2024/01/24 07:33:03

**Comment by shirouzu** [comment]
そうですか。
何か詳細の事情が分かりましたら、別途ご報告ください。
