### ISSUE TITLE
壊れているファイルをコピー元の対象から除外したいです！

### ISSUE THREAD

**Issue by cynbinytt** [FastCopyLab/FastCopy#265]
壊れているファイルをコピー元の対象から除外したいです！
できますか？

以下詳細
-----------------------------------
Sourceのa.txtについて
事前にサイレントデータ破壊（ファイル破損）チェックはできますか？

Source  a.txt
DestDir a.txt

Source  a.txtの現在のハッシュ値計算：例えば 1
Source  a.txtの副次ストリーム内のハッシュ値取得：例えば 1

この場合にはハッシュ値が一致した（a.txtに破損なし）ので

　DestDir a.txt
　との「更新（同期）」処理の開始

仮に一致しなければ、

　Source  a.txtのファイルは●スキップ
　（サイレントデータ破壊（ファイル破損）しているので）

つまり、壊れているファイルをコピー元の対象から除外したいです！
壊れているファイルをコピーするバカはいませんからね

これができるようなったなら、、、、、pro版買います！宣言

**Comment by shirouzu** [comment]
Pro版の「ベリファイ情報検証」という動作モードでサイレント破壊検証は可能ですが、あくまで動作モードの一つです。
コピー動作と組み合わせたモードはありません。
