### ISSUE TITLE
更新日時「1980/01/01」のままですね

### ISSUE THREAD

**Issue by cynbinytt** [FastCopyLab/FastCopy#266]
更新日時「1980/01/01」のままですね
アンチウィルスソフト（AVAST使用中）が、食い付いていたので仕方ありませんが

https://www.avast.co.jp/installation-files
オフライン インストーラー
avast_free_antivirus_setup_offline.exe　←ダウンロード

avast_free_antivirus_setup_offline23.12.exe　←名前変更
　↓　fastcopyの右ボタンで「貼り付け」コピー
G:\    \AVAST

avast_free_antivirus_setup_offline23.12.exe　←1980/01/01 のままで直らない！！●

=================================================
FastCopy(ver5.5.0) start at 2024/02/03 09:09:54
<Source>  C:\Users\　　\Downloads\avast_free_antivirus_setup_offline23.12.exe
<DestDir> G:\　　\AVAST\
<Command> 差分（サイズ・日付） (with Verify)
-------------------------------------------------
Failed to restore timestamp1(プロセスはファイルにアクセスできません。別のプロセスが使用中です。32) : G:\　　\AVAST\avast_free_antivirus_setup_offline23.12.exe
+ G:\　　\AVAST\avast_free_antivirus_setup_offline23.12.exe   <20240203-090828 648,918,640 xxh3=9e9669b9633f496d18f361fccf1e3c79>

TotalRead  = 618 MiB
TotalWrite = 618 MiB
TotalFiles = 1 (0)
TotalTime  = 2.9 sec
TransRate  = 226.9 MB/s
FileRate   = 0.35 files/s
VerifyRead = 618 MiB
VerifyFiles= 1

Result : (ErrFiles : 0 / ErrDirs : 0) at 2024/02/03 09:09:57

![AVAST](https://github.com/FastCopyLab/FastCopy/assets/157763037/594c4938-a429-4813-9c58-655d76cd99ea)

![FSERR](https://github.com/FastCopyLab/FastCopy/assets/157763037/9ca294ef-2d1b-4d3a-aaa5-656128d660de)

**Comment by shirouzu** [comment]
当たり前の報告は不要です。

**Comment by cynbinytt** [comment]
このままでいいのかな、、？アイコンは青のままで赤にならないし、ようく見ないとエラーがでたかわからなかったけど、、、

**Comment by shirouzu** [comment]
失礼しました。
それは良くないです。次のバージョン出直しておきます。

**Comment by cynbinytt** [comment]
はい　お役に立ててよかったです
