### ISSUE TITLE
FastCopy.logに記録したデータは、いつまで保存されますか？ ログファイルを放っておくと肥大化したりしますか？

### ISSUE THREAD

**Issue by e1blue** [FastCopyLab/FastCopy#268]
**質問**
FastCopy.logに記録したデータは、いつまで保存されますか？
ログファイルを放っておくと肥大化したりしますか？

**備考**
FastCopy.logを確認したら一番古い記録が 2020 年でした。
それ以前から使用していたのですが、以前のログが記録されていないのは、FastCopyのログ設定なのか(一定期間したら自動削除されたりするようなことはありませんか？)、それとも自分のパソコン履歴の問題なのか原因を切り分けたかったので質問しました。

**Comment by shirouzu** [comment]
自動削除等されることはありません。
（手元で実験すればわかるようなことは聞かないでください）
