### ISSUE TITLE
FastCopyでエラーが発生した場合のログだけを出力する方法はありますか？

### ISSUE THREAD

**Issue by e1blue** [FastCopyLab/FastCopy#269]
**質問**
FastCopyでエラーが発生した場合のログだけを出力する方法はありますか？

**備考**
FastCopyのlog設定で「エラーログを記録」にチェックを入れているのですが、FastCopy.logを見たら、エラーが発生していない「Result : (ErrFiles : 0 / ErrDirs : 0)」のログも出力されていました。

**環境**
FastCopy(ver5.5.0)

**Comment by shirouzu** [comment]
（手元で実験すればわかるようなことは聞かないでください）
