### ISSUE TITLE
内部リトライ回数の表示は？

### ISSUE THREAD

**Issue by lyanmeng** [FastCopyLab/FastCopy#27]
FastCopyの内部エラー回避処理でNTFS（ハード）がおかしいなどは検知できているのでしょうか？

もしできましたら、
（内部）読み込みリトライ回数：
（内部）書き込みリトライ回数：

の様にログファイルに掃き出しは可能ですか？
（本来は表にでない数値ですが）

内部的にどの程度「リトライ」しているのか、事前に把握して
致命的なエラーが出る前に、修理・交換等準備しておきたいです

**Comment by shirouzu** [comment]
read/write のリトライは OS側で勝手に行っているだけで、FastCopy側は行っていません。
