### ISSUE TITLE
FastCopyの「移動（全上書き）」で「SetEndOfFile(ディスクに十分な空き領域がありません。112)」と表示されたファイルは、壊れることなく元ディレクトリにありますか？

### ISSUE THREAD

**Issue by e1blue** [FastCopyLab/FastCopy#270]
**質問**
FastCopyの「移動（全上書き） (with Verify ACL)」実行中に「SetEndOfFile(ディスクに十分な空き領域がありません。112)」と表示されたファイルは、壊れることなく元ディレクトリにありますか？

**備考**
「移動設定」に色々な設定項目がありますが、いずれを選んだとしても「SetEndOfFile」で表示されたファイルは、壊れることなく元ディレクトリにありますか？

**環境**
FastCopy(ver5.4.3)

**Comment by shirouzu** [comment]
（手元で実験すればわかるようなことは聞かないでください）
