### ISSUE TITLE
FastCopy 5.6.0 does not support copying from a USB-connected smartphone.

### ISSUE THREAD

**Issue by piotrtrkostrzewski94** [FastCopyLab/FastCopy#273]
Good morning.
I connected the smartphone to USB and turned on file transfer via USB.  I launched FastCopy and selected the file from my smartphone to be copied to the external drive.  Unfortunately, FastCopy does not respond to clicks.  Thank you very much for your time.  Have a nice day.

**Comment by shirouzu** [comment]
Connections between PCs and smartphones often use a proprietary protocol called PTP/MTP, which cannot be accessed via the Win32 file system API, so unfortunately, it cannot be used with FastCopy.

**Comment by piotrtrkostrzewski94** [comment]
Too bad, thank you very much for the information.  Have a nice day.
