### ISSUE TITLE
Don't save history option

### ISSUE THREAD

**Issue by pcdeem** [FastCopyLab/FastCopy#274]
A don't save history option is needed so items that were copied or deleted aren't saved into the ini file.
This options could be put in the Log settings dialog.
It's a little pointless having an NSA delete option that renames files and overwrites them if the file that you originally deleted is in the history list for anybody to see.

**Comment by shirouzu** [comment]
If you do not want to leave log records, you can turn off log records in the log settings.

**Comment by pcdeem** [comment]
Actually this has nothing to do with logging.
Perhaps I wasn't clear enough.
An option to not add items to [src_history], [del_history] and any other history is what I should have said.
So that we don't get any previous file(s) showing in the Source/Dest boxes when the app starts.
![Fastcopy](https://github.com/FastCopyLab/FastCopy/assets/19802617/a47a7879-bea4-4110-9bf2-5b6cc9759c42)

Especially so deleted filenames can't be read from the [del_history] in fastcopy2.ini.
The ability to disable logging is great.
The ability to not save history would be good as well.

**Comment by shirouzu** [comment]
It can be changed from the log settings.
If "Number of history items for Src/DestDir" to 0, and restart, the history will disappear.

**Comment by pcdeem** [comment]
Okay. Thanks.
This is definitely closed now then. :-)
