### ISSUE TITLE
32ビット版 fcp.exe が起動できない

### ISSUE THREAD

**Issue by riku22** [FastCopyLab/FastCopy#275]
**エラー内容**

下記のエラーが表示され、32ビット版の `fcp.exe` が起動できません。

なお、64ビット版は問題なく起動できるようです。

```
E:\programs\FastCopy5.6.0\fcp.exe

このアプリケーションのサイド バイ サイド構成が正しくないため、アプリケーションを開始できませんでした。詳細については、アプリケーションのイベント ログを参照するか、コマンド ライン ツール sxstrace.exe を使用してください。
```

**再現方法**

1. <https://fastcopy.jp> から `FastCopy5.6.0_installer.exe` をダウンロードする。
2. `FastCopy5.6.0_installer.exe /extract32` を実行して32ビット用ファイルを抽出する。
3. 作成された `FastCopy5.6.0` ディレクトリ内の `fcp.exe` をダブルクリックして実行すると、上記のエラーが発生する。

**コマンドライン・オプションや各種設定**
コマンドラインオプションは指定していません。
また、設定も初期設定から変更していません。

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : 5.6.0
OS ver: Windows 23H2 64ビット

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
ただ原則として、64bit版OSでは64bit版バイナリをお使いください。
