### ISSUE TITLE
Microsoft Defender除外設定に FastCopy を追加はだめです

### ISSUE THREAD

**Issue by cynbinytt** [FastCopyLab/FastCopy#276]
>Microsoft Defender除外設定に FastCopy を追加します。
>zip、exe、dll等のコピーが大幅に高速化＆CPU使用率が下がります。
>(セキュリティに問題あるファイルをコピーする場合は、追加しないでください）

今回は失敗しましたね

これだと
仮に、ウィルスファイルでもコピーできてしまいます
だって、アンチウィルスソフトでファイルのチェックをしないので

コピー先にウィルスファイルが蔓延します

こんなことをしていいのですか？

↓いや良くない

ウィルスのコピーが速くできて喜ぶばかはいません

この機能は、即中止すべきです

ファイルは「ウィルススキャン」にかけなければだめです
コピーのスピードは二の次です

安全こそ命です

(セキュリティに問題あるファイルをコピーする場合は、追加しないでください）

なんて一般ユーザがわかるわけがありませんよ

ので即廃止してくださいね
一般ユーザを守るとために、みんなが自分と同じマニアではありませんよ

**Comment by shirouzu** [comment]
これは使う側のポリシーの問題であり、あなたの個人的見解の押しつけは余計なお世話です。
（それと今後、貴方は FastCopy github issue 自体への書き込みを二度としないてください）

**Comment by cynbinytt** [comment]
やだ！

**Comment by shirouzu** [comment]
お子様ですか？
はた迷惑ですので、この issue 自体を削除します。
（また今後、貴方が issue を立てた場合、即座に削除します）
