### ISSUE TITLE
Data To be Copied only When Hash is different

### ISSUE THREAD

**Issue by LobevaMD** [FastCopyLab/FastCopy#277]
**Question**
Describe your question.
I am currently transferring Dozens of TB of Data. One of the Commom erros I have is "Size is changed(dst_digest)" Verify DST read error. I then noticied that the size and dates of the files I copied are the same but the hashes are different,

Is there a way to verify xxh3 for the source and target as quickly as possible, and only copy (overwrite) the ones that dont match?

**Comment by shirouzu** [comment]
> the same but the hashes are different,

That's strange.
Please paste all log data for that file.
If it is displayed an "Size is changed(dst_digest)", the file will then be renamed/dated to 1980/deleted, etc., depending on your verification settings. (unless you have selected "No action" in the settings)

For example, "rename to .fc_verify_err" is selected in the settings, it should be display a log like the one below.

```
Size is changed(dst_digest) : <file name>
Verify dst read error in and it was renamed (.fc_verify_err) : <file name>
```
