### ISSUE TITLE
プルダウンのメニューの並び替え

### ISSUE THREAD

**Issue by tail09099** [FastCopyLab/FastCopy#278]
**機能リクエスト内容**
いつもありがたく使わせて貰っています。
私は「コピー」よりも「移動」でFastCopyを使うことが多いのですが、デフォルトが移動になっていてくれたらなぁと思っています。
プルダウンのオンオフの設定だけではなく、並び替えも出来ると大変助かります。

**Comment by shirouzu** [comment]
ご提案ありがとうございます。
検討しておきます。
