### ISSUE TITLE
Major issue - copies wrong files

### ISSUE THREAD

**Issue by VeganPete** [FastCopyLab/FastCopy#279]
Right click "Copy with FC"
Right click "Paste with FC"
copies random files to destination folder.

**Comment by shirouzu** [comment]
I think that is likely a misunderstanding.
Right click "Copy with FC" means to open FastCopy Window and its source field is selected files.
Right click "Paste with FC" means to copy Clipboard files to selected directory by FastCopy.
The two functions do not work together.
