### ISSUE TITLE
Are there plans and possibilities to upload the installer to github for distribution?

### ISSUE THREAD

**Issue by VAllens** [FastCopyLab/FastCopy#28]
**Are there plans and possibilities to upload the installer to `GitHub` for distribution?**
here: https://github.com/FastCopyLab/FastCopy/releases

Because I am using `winget-cli` tool management software.

When I install an older version using `winget`, it throws a `HTTP 404`.
For example when installing version `4.0.4`, it request `https://fastcopy.jp/archive/FastCopy4.0.4_installer.exe`.
But the current site has already released version 4.0.5 and removed the download link for version `4.0.4`.

**Comment by a-raccoon** [comment]
It would make monitoring for new releases a lot easier through Github watch notifications.

**Comment by shirouzu** [comment]
Do you know how to open to public the installer without dummy source code archives(zip/tgz)?
[https://github.com/FastCopyLab/FastCopy/releases](https://github.com/FastCopyLab/FastCopy/releases)

**Comment by VAllens** [comment]
Hi, @shirouzu 
I'm not sure, I'd like to know too.

**Comment by shirouzu** [comment]
I will use the following URL to keep past installers.
https://github.com/FastCopyLab/FastCopyDist

**Comment by VAllens** [comment]
good job. 👍
