### ISSUE TITLE
fastcopy crashes when copying files and folders with hardlink to a USB harddisk drive.

### ISSUE THREAD

**Issue by 265785** [FastCopyLab/FastCopy#281]
**Describe the bug**

fastcopy crashes when copying files and folders with hardlink to a USB harddisk drive.
Here are the crash files:

[fastcopy_exception.dmp](https://github.com/FastCopyLab/FastCopy/files/14544960/fastcopy_exception.dmp)

[fastcopy_exception.log](https://github.com/FastCopyLab/FastCopy/files/14544961/fastcopy_exception.log)

I afraid this error will destroy my USB harddisk drive.  So I sincerely hope you can fix this problem. Thank you! 

**To Reproduce**
1. Open the option "Copy Junction/Symlink as Junction/Symlink (not target)"
2. copy mutiple files to another USB drive.
3. FastCopy Crashes

**Command line options and various settings**
The "Copy Junction/Symlink as Junction/Symlink (not target)" option is opened

**Version/Environment**
 - FastCopy ver : 5.6.0
 - OS ver:Windows 11 x64

**Comment by shirouzu** [comment]
That log indicates the use of a cracked version.
Please use the official version.

Modifying FastCopy is a violation of the license.
FastCopy has a self-modification checker and will crash if it detects modifications.

https://github.com/FastCopyLab/FastCopy/issues/205
