### ISSUE TITLE
v5.70及びv5.60では管理者権限での削除が機能しません

### ISSUE THREAD

**Issue by beehiveharvest** [FastCopyLab/FastCopy#282]
v5.70（確かv5.60も）もシェル拡張をONにしコンテキストメニューから管理者権限のボタンをクリックして削除しようとすると、クリックした後削除のダイアログが消えてしまいます。
つまり、管理者権限では削除出来ません。

v5.50のインストールファイルも残しておいたので、v5.70をアンインストールしv5.50で管理者権限をクリックし削除というケースでは問題なく機能します。

環境は
Windows10 Pro(64bit)
22H2
です。

**Comment by beehiveharvest** [comment]
スクリーンショットのグリーンの円の箇所です（管理者権限のボタン）。
※スクリーンショットではユーザ名や具体的なファイル名等はモザイクを入れさせていただきました。
![ｖ5 50](https://github.com/FastCopyLab/FastCopy/assets/82905681/bc9fb5f6-f5dc-4698-8a02-a1ddc5f22cba)

**Comment by shirouzu** [comment]
ご報告ありがとうございます。確認しました。
次のバージョンで修正しておきます。
