### ISSUE TITLE
ヘルプの誤記（日本語版のコマンドライン一覧表）及び記載漏れ（動作モード「同期（最新日付）」の説明が無い）

### ISSUE THREAD

**Issue by ebakoJP** [FastCopyLab/FastCopy#284]
**エラー内容**
ヘルプ（ヘルプファイルおよび公式サイトのオンラインヘルプ）において、誤記と記載漏れがありましたので報告いたします。
（気付いたのは、Ver5.5.0 時点）

**再現方法**
- 誤記:
1. ヘルプを開く。
2. Japanese > コマンドライン と辿る。
3. 「指定可能なオプションは、以下の通りです。～」の表において、以下の項目の「GUIでの表記」が同じになっている。

|cmdline|GUIでの表記|  
|---|---|  
|exist_diff|既存（サイズ・日付）|  
|exist_update|既存（サイズ・日付）|   

（参考）English > CommandLine の表では、「exist_update | Exist（Newer）」。
　  
- 記載漏れ:
1. ヘルプを開く。
2. Japanese > 使用法・画面 > 2）動作モード と辿る。
3. モードと動作内容の表に、設定画面にある『動作モード同期（最新日付）」』の説明が記載されていない。  
（設定画面のスクリーンショットを添付）
 
（備考）English > Usage/MainWindow > 2) Operation mode も同じく記載がない。

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :5.7.2 通常版
OS ver: Windows10 Pro 22H2

**スクリーンショット**
- 「設定>一般設定>動作モード設定」>「表示する動作項目」
（「同期（サイズ・日付）」と「移動（サイズ・日付）」の間にある「同期（最新日付）」の説明がヘルプに記載されていない）

![20240311_FastCopy一般設定＞動作モード設定](https://github.com/FastCopyLab/FastCopy/assets/25903138/e862e5bf-c467-459c-a388-7fcd17fe6ba9)

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
次のリリースで修正しておきます。
