### ISSUE TITLE
ホームページへのアクセスについて

### ISSUE THREAD

**Issue by s1k1t1** [FastCopyLab/FastCopy#285]
自宅からはFastCopyのホームページ（https://fastcopy.jp/）にアクセスできるのですが、
職場からアクセスしようとすると、
『接続がプライベートではありません　NET::ERR_CERT_AUTHORITY_INVALID』
とのエラーが出てしまいます。Edgeでもchromeでも出てしまいます。
詳細設定から無理やり入ろうとしても、
『マルウェアに感染している可能性あり』というように表示され、やはりアクセスできません。

当方の職場の情報セキュリティー担当者にも問い合わせ中ですが、
可能でしたら、そちらでも今一度ルート証明書等をご確認頂けますと幸いです。
お手数おかけしますが、よろしくお願い申し上げます。

**Comment by shirouzu** [comment]
こちらでも確認してみましたが、問題なさそうですね。
ありそうなシナリオとしては、「FW/ProxyによるHTTPS内容監視」を行っているLAN環境で、オレオレ証明書（＝FW/Proxyに内蔵の証明書）の各PCへのインストールが原因で起きたトラブル、とかでしょうか。
（昔は HTTPS通信の内容監視として Bluecoat が有名でした。ブラウザで接続の証明書を表示すると、URLの証明書ではなく、Bluecoat等の証明書が表示されるため、識別可能です）
