### ISSUE TITLE
Want to fork from FastCopy 4, where is the source ? 

### ISSUE THREAD

**Issue by jljovano** [FastCopyLab/FastCopy#286]
Hello, I'd like to try to fork Fastcopy from the last open source version (4.xx), but this repository do not seem to have the source code. Where can I find it please ? 
malikovuko(at)yahoo.fr
Thank you.

**Comment by shirouzu** [comment]
Sorry, 5 years ago v3.63 was the last open source version.
Ref) https://github.com/FastCopyLab/FastCopy/issues/197#issuecomment-1595561320
