### ISSUE TITLE
Advice on I/O Settings

### ISSUE THREAD

**Issue by MrGreg1** [FastCopyLab/FastCopy#288]
Thanks for your help resolving my last issue regarding Sync. I have a question about the I/O Settings. I am currently using the defaults. My Sync job source and destination are both local 29 TB Raid 0 arrays with 256KB stripe size. They are formatted NTFS 64KB block size .

These arrays/drives are used exclusively for Veeam Backups. I have configured the arrays and drives per Veeam's recommendation using this page.

[https://bp.veeam.com/vbr/3_Build_structures/B_Veeam_Components/B_backup_repositories/block.html](url)

Veeam reads and writes backups using 512KB blocks. I am wondering if should make any adjustments to FC I/O settings considering my setup per the Veeam document.

Thanks

**Comment by shirouzu** [comment]
I think it would be better to actually test the performance of various parameters.
The issue below may be helpful.
https://github.com/FastCopyLab/FastCopy/issues/134

**Comment by MrGreg1** [comment]
Thanks for sharing the issue. Great job working with claaaaash!

I am familiar with diskspd. I used it when testing the best Raid Stripe size for Veeam. Here is the document I used.

[https://www.veeam.com/kb2014](url)

I understand that I will need to test with various parameters. But first need to know if I should be using "Drives that are always run in parallel (e.g. SSD-RAID) under Drive Settings. As previously stated my source and destination are Raid arrays. However my backup sync job is only running one instance of FC. I am not using parallel processing. At least that is my understanding.

**Comment by shirouzu** [comment]
Yes, it seems better to enable that option.
However, this is not a magical feature;
- Read and write at the same time, even when copying within the same drive, as when copying to another drive.
- Even if another FastCopy is using the drive, FastCopy will run at the same time without waiting for it to finish.
That's what it means.

In any case, speed performance (along with reliability) is an important factor for FastCopy.
Try running various tests,
- Measurement result
- Elements that can be improved
- Unknown behavior
Please let me know if you have any.

**Comment by MrGreg1** [comment]
Sounds good. I will enable it using "DE" since those are my Raid logical drives. What about Parallel Running check box (Ignore the above settings,) Don't wait for other running FastCopy to finish. Again, I am running one instance of FC in my script.
