### ISSUE TITLE
FastCopy Does not migrate owners or grant them access

### ISSUE THREAD

**Issue by laplace** [FastCopyLab/FastCopy#289]
When migrating folders with ACL to non-windows (i.e. Synology NAS), FastCopy uses the connection user as owner for all folders/subfolders/files, and there is no ACL entry for the original owner, so the creator/owner does not have access to the folder/file.

**To Reproduce**
Migrate a folder created with a domain user with ACL to destination on the network with different user for the connection.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.4.2
 - OS ver: Windows Server 2016, Synology DSM 7.2

**Comment by shirouzu** [comment]
Sorry, I couldn't understand the explanation well.
Please explain the current state and desired state in detail, using screen captures of file properties, etc.

The current FastCopy ACL copy uses the Windows official APIs BackupRead and BackupWrite, so I believe it is the "best-effort ACL information copy".
