### ISSUE TITLE
FastCopy perfect verify in CLI (fcp)

### ISSUE THREAD

**Issue by tukanos** [FastCopyLab/FastCopy#290]
Hello,

I would like to ask if the pro feature perfect verify is also available through fcp.exe?  I tried to search both GUI, CLI and the documentation, but could not find a definitive answer. 

If the feature is not available in CLI are you planning to include it there?

Thank you.

**Comment by shirouzu** [comment]
fcp settings follow the fastcopy2.ini settings.
In other words, if fastcopy is set to use Perfect verify, fcp will also use Perfect verify.

**Comment by tukanos** [comment]
> fcp settings follow the fastcopy2.ini settings. In other words, if fastcopy is set to use Perfect verify, fcp will also use Perfect verify.

I see, thank you for your answer.  Maybe it is an idea for documentation improvement.
