### ISSUE TITLE
GUI Suggestion: Apply the option to "Use MB/s instead of MiB/s notation" to all displayed information/logs

### ISSUE THREAD

**Issue by xEBFE** [FastCopyLab/FastCopy#291]
### In reference to version
FastCopy 5.7.3

### Describe the solution you'd like
When enabling the following option:
Options > Main Settings > Misc Settings > ☑ Use MB/s instead of MiB/s notation

Can you display all instances of MiB and MiB/s with MB and MB/s with the proper conversion of mebibytes (MiB) to megabytes (MB)?

If you decide to make this change, you may need to consider renaming the option to:
"Use MB instead of MiB notation"

The reason for this suggestion is to have consistency among displayed information. It should be applied to all instances displayed in the GUI as well as in the log files.

### Current Behavior:

TotalRead  = 111 MiB
TotalWrite = 111 MiB
TotalFiles = 1 (0)
TotalTime  = 1.1 sec
TransRate  = 11.1 MB/s <--- Changes the display of "TransRate" only
FileRate   = 0.10 files/s
VerifyRead = 111 MiB
VerifyFiles= 1

### Suggested Behavior:

TotalRead  = 111 MiB <--- Display as "116.39 MB"
TotalWrite = 111 MiB <--- Display as "116.39 MB"
TotalFiles = 1 (0)
TotalTime  = 1.1 sec
TransRate  = 11.1 MB/s
FileRate   = 0.10 files/s
VerifyRead = 111 MiB <--- Display as "116.39 MB"
VerifyFiles= 1

**Comment by shirouzu** [comment]
In the past, everything was expressed in MiB.
However, many software such as CrystalDiskInfo display speed in MB/s.
Therefore, the MB/s option is a safeguard against being mistaken for lower speeds.
However, no one will be happy if you display the size in MB.
