### ISSUE TITLE
Re-Open Advice on I/O Settings #288

### ISSUE THREAD

**Issue by MrGreg1** [FastCopyLab/FastCopy#293]
**Question**
Hi shirouzu. Please reopen my issue. I have not had a chance to make the changes you suggested and test. I have been swamped with my paying IT job. The project that involves FC and my questions is for a friend of mine. His setup is in his home and I am helping him dial in his backup process. Thanks

**Remarks**
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
You can add notes even if the status is closed.
(Please do not raise an issue for this use)
