### ISSUE TITLE
ファイルが見つからない

### ISSUE THREAD

**Issue by SysVR** [FastCopyLab/FastCopy#294]
**エラー内容**
ファイルの実体は存在するが、FastCopyから読み込めずにファイルが見つからないと言われる。

**再現方法**
以下のような名前のファイルを作成し、
コピーを行う。
D:\636182 %\ 適当な名前 .txt

**コマンドライン・オプションや各種設定**
コマンドライン・オプションや標準から変更している設定項目などを記述
なし

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :5.7.3
OS ver:

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット

**Comment by shirouzu** [comment]
正確なエラーメッセージを貼り付けてもらえますか？
Dドライブはローカルドライブですか？ネットワークドライブですか？
%をパス要素に使っているようですが、使わない場合にも発生しますか？

**Comment by SysVR** [comment]
ごめんなさい。
正確なエラーメッセージは直後にWindowsからWindowsのアップデートがあるから再起動する？
って聞かれたのでFastCopyを終了してOSの再起動を行ってしまったため正確なエラーメッセージはわからないですが、
エラーコードは2です。

その後こちらで調べたところ、

"G:/G-DATA/DataObject/-------------------------------- /-------------------------------- .7z"
FastCopy側で" /" **([半角スペース]/)** が" %/" **([半角スペース]%/)** に変換されてしまう。
そのためファイルが見つからないというエラーになっていました。

"G:/G-DATA/DataObject/--------------------------------/--------------------------------.7z"
この場合は問題なくコピーできました。

※ファイルのコピーはVmware仮想マシン上のWindowsで行っているため、
ホストディレクトリをネットワークドライブとしてマップしています。
コピー元のパスは"Z:/DataObject"でローカル側の実体は"G:/G-DATA/DataObject"です。

**Comment by shirouzu** [comment]
> FastCopy側で" /" ([半角スペース]/) が" %/" ([半角スペース]%/) に変換されてしまう。

FastCopyには、そういう変換機能はないので、パラメータを渡す側がそれを行っているのだと思います。

**Comment by SysVR** [comment]
Windows Explorer から確認したら同じく謎の%が付与されていました。
対応ありがとうございました。
