### ISSUE TITLE
Exclude filter editor button tool tip displays 'Include Filter Editor'

### ISSUE THREAD

**Issue by salemjo** [FastCopyLab/FastCopy#295]
**Describe the bug**
/*
Exclude filter editor button tool tip displays 'Include Filter Editor' instead of 'Exclude filter Editor'
Issue present since 5.1.0
*/

**To Reproduce**
1. Check filter 
2. Place mouse pointer over ... button at the right side of Exclude list box

**Version/Environment**
 - FastCopy ver : 5.1.0 / 5.7.3
 - OS ver: Windows 7 / AMD64

**Screenshots**
![2024-03-28_151922](https://github.com/FastCopyLab/FastCopy/assets/104968650/4f54c25f-909f-44e9-bfc3-09b1a6974a6f)

Thanks for your efficient program.

**Comment by shirouzu** [comment]
Thank you for your report.
I will fix in the next version.

**Comment by salemjo** [comment]
Thanks
