### ISSUE TITLE
サブフォルダ配下から指定フォルダを除外する。

### ISSUE THREAD

**Issue by HiroyaFukumura** [FastCopyLab/FastCopy#300]
FastCopyVer5.7.5を使用しています。
バックアップする際に特定のフォルダを取りたくないのですが、上手く設定出来ません。
例えばですが、部署毎のフォルダの配下に年度毎のフォルダが存在しているとします。
この年度毎のフォルダですが直近2年度分のフォルダのみ別ドライブにコピーしたいです。

<バックアップ元＞
C:\部署001\提案\2022年度	→　これは除外
C:\部署001\提案\2023年度
C:\部署001\提案\2024年度
C:\部署022\提案\2022年度	→　これは除外
C:\部署022\提案\2023年度
C:\部署022\提案\2024年度
　　　　↓
＜バックアップ先の結果＞
E:\部署001\提案\2023年度
E:\部署001\提案\2024年度
E:\部署022\提案\2023年度
E:\部署022\提案\2024年度

このような結果を望んでいるのですが、

Source：	C:\*
DestDir：	E:\
Exclude：	部署001\提案\2022年度; 部署022\提案\2022年度

或いは

Source：	C:\*
DestDir：	E:\
Exclude：	C:\部署001\提案\2022年度; C:部署022\提案\2022年度

或いは

Source：	C:\部署001
		C:\部署022
DestDir：	E:\
Exclude：	部署001\提案\2022年度; 部署022\提案\2022年度

としても上手く出来ません。
サブフォルダのサブフォルダを除外する設定はどのように行えばよいのでしょうか？
御教示頂ければ幸いです。

**Comment by shirouzu** [comment]
include/excludeでフォルダを指定するには、末尾に \\ を付ける必要があります。
全ての 2022年度 というサブフォルダを除外したい場合の指定は、下記の通りです。

Source : C:\\
DestDir : E:\\
Exclude : 2022年度\\

ついでの tips ですが、202[0-2]年度\\ とすれば、2020～2022年度がマッチします。

**Comment by HiroyaFukumura** [comment]
ご回答ありがとうございます。
確認した所、私の記載ミスで後ろの￥マークは付けていました。

今回実施したいのは以下のように　部署001\提案\2022年度　と　部署022\提案\2022年度　を除外したい形です。
（実際には部署の数が結構あります。）
また、Cの直下にある2022年度や2024年度の中に「2022年度」というフォルダが存在していた場合もコピーしたいです。

<バックアップ元＞
C:\2022年度
C:\部署001\提案\2022年度 →　これは除外
C:\部署001\提案\2023年度
C:\部署001\提案\2024年度
C:\部署022\提案\2022年度 →　これは除外
C:\部署022\提案\2023年度
C:\部署022\提案\2024年度→　もしかすると、この中にも「2022年度」というフォルダがあるかもしれない。
　　　　↓
＜バックアップ先の結果＞
E:\2022年度
E:\部署001\提案\2023年度
E:\部署001\提案\2024年度
E:\部署022\提案\2023年度
E:\部署022\提案\2024年度

のようにしたいです。
単純に　C:\部署001\提案\2022年度　は除外。C:\部署022\提案\2022年度　は除外。
というような事が出来れば有難いと考えています。
そのような事は出来ないのでしょうか？

**Comment by shirouzu** [comment]
（Github issue で \\ を記述するには、\\\\ と重ねて記述します）

特定フォルダ配下の 2022年度 を除外したい場合は、
exclude : C:\\部署001\\提案\\2022年度\\; C:\\部署022\\提案\\2022年度\\; 
exclude : \\部署001\\提案\\2022年度\\; \\部署022\\提案\\2022年度\\; 
exclude : 部署001\\提案\\2022年度\\; 部署022\\提案\\2022年度\\; 
のいずれもOKのはずですが、ダメでしたか？
（最後のexclude は相対指定なので、たとえば C:\\xxx\\部署001\\提案\\2022年度 なども除外される）

**Comment by HiroyaFukumura** [comment]
再度後程試してみます。
いろいろと試し打ちで記述した為、最初から指定しなおしでやり直してみます。
尚、exclude指定で最終レコードの後ろにも「;」は必要なのでしょうか？
記述していなかった為、そこも誤っているかもしれません。

**Comment by shirouzu** [comment]
末尾の ; は記述しても特に問題ありません。

**Comment by HiroyaFukumura** [comment]
最初から指定し直す事で無事動作致しました。
ありがとうございました。
