### ISSUE TITLE
end Fastcopy automatically

### ISSUE THREAD

**Issue by Guenther49** [FastCopyLab/FastCopy#301]
Hi,
how can I end Fastcopy automatically when the task (copy/move) is finished?
regard Günther

**Comment by a-raccoon** [comment]
By using FastCopy from the "Paste" shell menu after a Windows Explorer cut or copy of the files you want moved or copied.  The program will close automatically this way.
If you manually open FastCopy then it will stay open.
    On Thursday, April 11, 2024 at 01:19:58 AM MDT, Guenther49 ***@***.***> wrote:  
 
 


Hi,
how can I end Fastcopy automatically when the task (copy/move) is finished?
regard Günther

**Comment by shirouzu** [comment]
You can also use /auto_close or /force_close option.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by Guenther49** [comment]
@a-raccon and qshirouzu,
Many thanks for the prompt feedback. Closing after starting via the context menu works fine.
best Regards
Günther
