### ISSUE TITLE
Command line mode, status acquisition!

### ISSUE THREAD

**Issue by ghost** [FastCopyLab/FastCopy#302]
Hello, Does the factCopy command line mode support blocking or results? For example, if I use Python to call factCopy to complete the execution and return the status or end the blocking, it would be convenient for me to obtain the backup status.

**Comment by shirouzu** [comment]
Sorry, but you should research and try it yourself before asking others.
https://fastcopy.jp/help/fastcopy_eng.htm#cmdline:~:text=Exit%20status%20code)%20Command%20is%20succeeded%3A%200%2C%20or%20failed%3A%20%2D1
