### ISSUE TITLE
Error 127 when moving file

### ISSUE THREAD

**Issue by Atlantis1979** [FastCopyLab/FastCopy#303]
**Describe the bug**
Trying to move a file from one disc to another (with verify enabled), get this error at the end of the copy/verify procedure:
_DeleteFile(move)(The specified procedure could not be found.127) : Filename_

**To Reproduce**
Does not happen every time but can happen several times daily. Doing a file move from one disc to another triggers this issue.

**Command line options and various settings**
Move (Overwrite), Nonstop, Verify, Estimate all enabled.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : Happens from 5.5.0 until current 5.7.5. Have not tested on earlier versions.
 - OS ver: Windows 10 1909 x64

**Comment by shirouzu** [comment]
It seems that the error occurred because another process or antivirus software was opening the file at that time.
There is no solution other than to stop them.
