### ISSUE TITLE
Breakdown in Verification results in 100% verification failure

### ISSUE THREAD

**Issue by bryancpearson** [FastCopyLab/FastCopy#304]
**Describe the bug**
With version 5.7.7, suddenly all verify operations failed when Conventional Verify is selected.  Verify operations are successful when Perfect Verify is selected.  Clearly there is a specific problem preventing conventional verify and not the copy operation.  Use of Administrative privileges did not affect the outcome.

**Delete and re-install of FastCopy resolved the problem.**

While the problem is certainly system-specific, **a more specific error relating to the nature of the failure to verify would be helpful, with something like the following suggested:**

- Cannot create temp file on h:\systemtemp
- Cannot open file for write in C:\Users\localuser\FastCopy
- Cannot read (or write) AltStreamInfo on E:\temp\File1-2022-02-15\blkdev.list

FastCopy may not have caused the problem, which was almost certainly related to permission errors in the installation folder, C:\Users\localuser\FastCopy.  But **_a more specific error check for the verify option itself in advance of the main copy operation_** would be far more efficient than to complete a large copy operation with 100% verify failure. 

**To Reproduce**
turn on verify on copy operations
set any hash mode
set Add verifyinfo to checked or not
Suffer some sort of permissions problem with the temp folder or the program installation folder.

**Command line options and various settings**
No command line options used.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.7.7
 - OS ver: Windows 10

**Screenshots**
The error log reports many lines like this:

Verify Error src:0000000000000000000000000000000000000000000000000000000000000000 dst:a48faa3d6e1dfc0877cdd551747fb60f9fc30eeae1317aad8ac048ebb10bf7ab and it was deleted : E:\temp\File1-2022-02-15\blkdev.list

But then lines like this, with actual checksums:

Verify Error src:2b50f47988f4d6b52b22315c3053b8616d268062abf855381d7c68ce4a1b001a dst:a48faa3d6e1dfc0877cdd551747fb60f9fc30eeae1317aad8ac048ebb10bf7ab and it was deleted : E:\temp\File2-2022-02-15\blkdev.list

Thanks for a terrific product, which gets better all the time!

**Comment by shirouzu** [comment]
Thank you for your report.
Unfortunately, I cannot reproduce it at hand.
Could you please make a zip file of the last 1MB of the file log and the fastcopy2.ini file and send it to *****?

**Comment by shirouzu** [comment]
I found that the src hash value becomes 0 when the following three conditions are met.
 - "Files dated 1980-01-02 will be resumed from verification" is checked
 - Conventional verify is enabled.
 - 1980-01-02 files exist. ("Set timestamp to 1980-01-02 until verification completes" is enabled and interrupt the copy, then these files are generated)
 
Originally, "Files dated 1980-01-02 will be resumed from verification" should have been valid only for Perfect Verify.
I will fix it in the next version.

**Comment by salemjo** [comment]
Thanks for quick update

FastCopy ver 5.7.7 AND 5.7.8  - x64
OS ver: Windows 7 X64
Standard Version - NOT PRO  

src hash value becomes 0 
when  **acl="1" OR  stream="1"**

The verify finish successfully if   **acl="0" AND  stream="0"**

Thanks again for efficient program

**Comment by shirouzu** [comment]
Thank you for your report.
I fixed it in v5.7.9.
Thank you!
