### ISSUE TITLE
How to use in the way alike teracopy? i.e. when copying files/folders: no del on target, popup if conflict, verify if any copy/move. thx

### ISSUE THREAD

**Issue by ccchan234** [FastCopyLab/FastCopy#308]
**Question**
Describe your question.
(Please do not ask anything that you can figure out by experimenting at hand).

How to use in the way alike teracopy? i.e. no del on target, popup if conflict, verify if any copy/move. thx

i know the different modes are written in the manual, but it's TOO MUCH complicated and
indeep after analyzing /w AI, i still cant find way that i feel is SAFE to do so.
esp that teracopy will popup if there is confliect and let you choose to skip/rename/overwrite.

thank you.

**Remarks**
Please add any additional information or screenshots.

ps: the pro version of 48USD is too crazy, 
i respect everyone's work, but why dont you sell at 4.8USD so 10x more ppl will buy and use?

think of windows, for what it can do, it cost USD 100 or something like that when published.
fastcopy seems to handle files better than teracopy, but it's unreasonable to charge for 48USD,
unless alike winrar, you think that no ordinary user will purchase, thus you put all the penalty into the commercial license.

thank you.

**Comment by shirouzu** [comment]
There is no such function.
I highly recommend using Teracopy.
