### ISSUE TITLE
Flush Buffer once Saturated

### ISSUE THREAD

**Issue by DerekZiemba** [FastCopyLab/FastCopy#31]
## **Describe the solution you'd like**

I frequently am moving data between Microsoft StorageSpaces volumes that are backed by 8 SSDs and 3 HDDs.   The volumes are spread across multiple drives so when copying between volumes, on the hardware level, it's actually reading/writing from the same disks resulting in poor performance.   It's often faster to copy from a StoragePool volume to the C:\ drive then from the C:\ drive to the StoragePool volume. 
**This process can be significantly sped up if once the buffer is filled, it's flushed (so only writes are done).**
 
That would be the simple thing to do.  But better yet would be to detect StorageSpace volumes that utilize the same underlying disks, and when detected it would read until the buffer is full, then flush the buffer, then read until the buffer is full, flush the buffer, etc... 

## **Additional context**
For this scenario, it would increase the copy speed from about 250MB/s to 3TB/s when reading and 1TB/s when flushing for an average speed of around 2TB/s - an 8x increase.

**Comment by shirouzu** [comment]
There is two way solutions.

1. assign drive letter for StoragePool and specify drive group. [https://fastcopy.jp/help/fastcopy_eng.htm#setting_physical](https://fastcopy.jp/help/fastcopy_eng.htm#setting_physical)
2. use /disk_mode=same option. [https://fastcopy.jp/help/fastcopy_eng.htm#cmdline](https://fastcopy.jp/help/fastcopy_eng.htm#cmdline)

**Comment by DerekZiemba** [comment]
Ahh. Works like a charm.  Sorry for failing to check the documentation properly
