### ISSUE TITLE
Please adds viewing of hidden and system files and support for synchronized files contained in the Onedrive folder local offline

### ISSUE THREAD

**Issue by abecedad** [FastCopyLab/FastCopy#310]
Hello, I will gladly purchase the PRO license and recommend the product to all my colleagues, when it adds viewing of hidden and system files without having to change Windows preferences, and above all, when it allows copying the synchronized files contained in the Onedrive folder local offline (yes it is possible, I have to do it with Linuxreader). Thank you

**Comment by shirouzu** [comment]
Sorry, your purchase does not affect whether we add features to FastCopy.
