### ISSUE TITLE
Upgraded to Version 5.7.11.  Program "crashes"  after several minutes of use.  

### ISSUE THREAD

**Issue by HuggieB** [FastCopyLab/FastCopy#311]
**Describe the bug**
Unable to run program after several minutes of use.  Desktop shortcut shows error (see screenshot)
Shortcut then disappears.  Unable to start program directly from .exe file.  Deleted all related files, reinstalled several times.  Bug reoccuring.  Now using version 5.7.10.  No problems with the prior version.

**To Reproduce**
Unable to determine exact conditions prior to error, other than program can be used successfully several times.   FastCopy related files seem to exist where expected.  Log show no unusual errors.

**Command line options and various settings**
Added local drive group.  Move (overwrite) as startup setting.  Estimate, Verify, shell extension, Use taskbar when minimized

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.7.11
 - OS ver: Microsoft Windows 11 Pro Version, 10.0.22631

**Screenshots**
![Fastcopy Error](https://github.com/FastCopyLab/FastCopy/assets/170689798/71c99d35-5d24-4662-939f-c0c34e4c7d74)

**Comment by shirouzu** [comment]
That image is not a crash, but a message that the file the shortcut points to is being deleted.
(In case of crash, fastcopy_exception.log and fastcopy_exception.dmp will be generated)

There is a high possibility that this is a false detection by your antivirus software.
