### ISSUE TITLE
There apparently is an undocumented virus checker built in

### ISSUE THREAD

**Issue by Dan-Essin** [FastCopyLab/FastCopy#313]
**Question**
I'm getting messages like this:
OpenFile(Operation did not complete successfully because the file contains a virus or potentially unwanted software.225) : G:\Syncrify\area51\Area51\Area51\Mac\Paragon_APFS_to_HFS_Converter_1_0.dmg

I know these files do not have any viruses

Where did these messages come from?
Is there a way to override them or make it an option?

**Remarks**

![Screenshot from 2024-05-26 10-42-34](https://github.com/FastCopyLab/FastCopy/assets/1776053/f11966ee-4ae0-4e15-907c-c8e369e86469)

**Comment by shirouzu** [comment]
That message is being issued by the Windows OS (probably from Windows Defender).
Run Option → Exclution Windows Defender (Elevate) to prevent Windows Defender from intervening.
