### ISSUE TITLE
空フォルダーをコピーした際にエラーログを吐かない設定の追加

### ISSUE THREAD

**Issue by Htbrk1** [FastCopyLab/FastCopy#314]
**機能リクエスト内容**
お世話になっております。
Htbrk1と申します。

弊社は映像制作を行っている会社ですが、増大する撮影データのコピーにFastCopyProを愛用させて頂いております。
アップデートも多く、また、Pro版の完全ベリファイの実装など、映像制作の基盤となるソフトと思っております。

1点質問がございまして、私共の使用方法だとフォルダー階層(計50フォルダーほど)をテンプレ化し、そこにファイルを入れる形を取っております。
空フォルダーもコピーできるのは便利ですが、エラーログにFindFirstFileEx(指定されたファイルが見つかりません。2)
と表示されます。

空フォルダーをコピーした際にエラーを出さないような設定はございますでしょうか？
どうしてもエラーと表示されると心臓に悪いという身勝手な理由ですが、何卒ご享受、ご検討頂けましたら幸いです。

引き続きよろしくお願い致します。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
通常の使い方であれば、空フォルダも（エラーなしで）空フォルダとしてコピーされるはずですね。
どういった使い方をされているのか、（再現できるよう）具体的に教えて頂けますか？
