### ISSUE TITLE
CreateFile(The process cannot access the file because it is being used by another process.32) 

### ISSUE THREAD

**Issue by Dan-Essin** [FastCopyLab/FastCopy#315]
**Question**
I get this when running 2 instances from the command line but not If I start them from shortcuts on the desktop.

Why?

How to prevent this from happening?

What effect does this have on the backup? Does it or does it not copy files?

**Remarks**

=================================================
FastCopy(ver5.7.12 (Admin)) start at 2024/05/28 09:15:00
<Source>  G:\*
<DestDir> L:\
<Command> Sync (Size/Date)
-------------------------------------------------
CreateFile(The process cannot access the file because it is being used by another process.32) : L:\System Volume Information\$MRCBT

TotalRead  = 199 MiB
TotalWrite = 197 MiB
TotalFiles = 388 (4)
TotalSkip  = 8,260,371 MiB
SkipFiles  = 1,214,116 (0)
TotalTime  = 25:04
TransRate  = 0.14 MB/s
FileRate   = 0.26 files/s

Result : (ErrFiles : 1 / ErrDirs : 0) at 2024/05/28 09:40:05

**Comment by shirouzu** [comment]
Indicates that the file could not be opened because another process already has the file open.
However, since System Volume Information is an area for drive management, it is normally excluded from copy targets.

**Comment by Dan-Essin** [comment]
That's nice to know, so why the error message?

**Comment by shirouzu** [comment]
What does it mean?
