### ISSUE TITLE
About SmartPhone drive

### ISSUE THREAD

**Issue by bowknot** [FastCopyLab/FastCopy#317]
When I connect my phone to a computer, I can only transfer files through Windows copy and paste, but I cannot transfer files through fastcopy.

**Comment by shirouzu** [comment]
I will consider it.
But SmartPhone drive is not native drive in Windows(it uses MTP/PTP protocol), so it can't access via Win32 file API.
(It's just Explorer making it look like a file system)

https://github.com/FastCopyLab/FastCopy/issues/273
https://github.com/FastCopyLab/FastCopy/issues/49

**Comment by sdhsts** [comment]
Thank you.
I hope hardcopy  can connect to my smartphone as soon as possible.

**Comment by sdhsts** [comment]
Thank you.
I hope hardcopy can connect to my smartphone as soon as possible.
