### ISSUE TITLE
Notation preference honored only by "TransferRate"

### ISSUE THREAD

**Issue by x86Gr** [FastCopyLab/FastCopy#318]
**Describe the bug**
Toggling "Use MB/s instead of MiB/s notation" affects only TransferRate, the other values remain in MiB/s

**To Reproduce**
Toggle "Use MB/s instead of MiB/s notation" and observe the displayed notation

**Command line options and various settings**
Use MB/s instead of MiB/s notation under "Misc Settings"

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.7.12
 - OS ver: Windows 10 22H2 build 19045.4474

**Comment by shirouzu** [comment]
That setting is intended to affect the TransRate display.
However, I'm not sure which display you're talking about, so could you post a screenshot?

**Comment by x86Gr** [comment]
![fc_screen](https://github.com/FastCopyLab/FastCopy/assets/91365407/44edc05f-7e3e-4f8c-9924-27918c4b9364)
Ok, i understand, but since TotalRead, TotalWrite and VerifyRead are in MiB this is a bit odd.
Since we're using Windows the whole environment is using MB, for example: a right click on a folder to know its size would be in MB, therefore comparing it to the progress displayed by FC would be not straightforward.
I'd have the notation flag affect all the displayed units.

**Comment by shirouzu** [comment]
Thank you.
(The setting is "Use <MB/s> instead of ...", it is not "Use \<MB\> instead of...")

Although the size is displayed in MB in Windows properties, it is actually in MiB (1024 * 1024).
So you can directly compare it with FastCopy's MiB value.
