### ISSUE TITLE
Please recognize smartphone drive

### ISSUE THREAD

**Issue by sdhsts** [FastCopyLab/FastCopy#319]
Please recognize smartphone drive.
When copying files on my PC (documents, photos, videos, etc.) to my smartphone, if i connect my smartphone with a usb cable, the fastcopy does not recognize my smartphone's storage.

**Comment by FastCopyLab** [comment]
Please do not post the same question multiple times.
(I deleted the two posts)
Please check to see if the same question has been asked before posting again.
https://github.com/FastCopyLab/FastCopy/issues/317
https://github.com/FastCopyLab/FastCopy/issues/273
https://github.com/FastCopyLab/FastCopy/issues/49
