### ISSUE TITLE
C:\Program Files配下で、更新できない

### ISSUE THREAD

**Issue by EH1973** [FastCopyLab/FastCopy#322]
FsstCopy Pro ver5.4.3を使用しています。
インストール先は、「C:\Program Files\FastCopy」です。

ver5.7.12に更新しようとしているのですが、
「次へ」ボタンを押下しても、先に進めません。

インストール先を「デフォルト」にすると、「開始します」のダイアログが出ます。
インストール先を「C:\Program Files\FastCopy」のままの状態で更新したいのですが、
可能でしょうか。

また、「C:\Program Files\FastCopy」にインストールされている状態だと
アンインストールもできないみたいです。
![タイトルなし](https://github.com/FastCopyLab/FastCopy/assets/173021580/af4e300c-9872-4445-a279-184ef950733e)

**Comment by shirouzu** [comment]
Program Files配下の場合、インストールに管理者権限が必要となるため、「次へ」ボタンを押すと、UAC昇格管理画面が出るはずです…が、それが出ないという現象みたいですね。
考えられる原因としては、UAC設定が特殊だったり、アンチウイルスソフトが昇格をブロックしているなどでしょうか。

対処としては、
・インストーラを右クリックして「管理者として実行」を行う
・FastCopy自体を使って、メニュー→ヘルプ→アップデート確認、でアップデートする（FastCopy自体がAdminでない場合は、昇格を求められますので、事前にメニューの「特権」を実行しておいたほうが良いかもしれません）
あたりでしょうか。
