### ISSUE TITLE
Current version shows 5.7.14, WindowsForest is still serving 5.7.12

### ISSUE THREAD

**Issue by therube** [FastCopyLab/FastCopy#323]
Current version shows as, 5.7.14
https://fastcopy.jp/

The WindowsForest download link is still serving version 5.7.12 (at present).
https://forest.watch.impress.co.jp/library/software/fastcopy/download_11574.html

(Github link is correct, 5.7.14.)

**Comment by shirouzu** [comment]
Thank you for your report.
Since the Windows Forest requires manual updates, there is a time lag in release updates.
We have suppressed the display of the Windows Forest until the update is completed.
