### ISSUE TITLE
Should a Source: Volume that goes "offline" cause copy to Stop?

### ISSUE THREAD

**Issue by therube** [FastCopyLab/FastCopy#324]
say you drag some files into Source:
& you have files like

C:/COPYME/readme.txt
I:/TEST/red.cat.blue.cat
Z:/ZOO/zebra.jpg

now say that even though you dragged (or otherwise entered said file names into Source:)
that the I: volume is actually (or in the interim went) "offline"

FastCopy successfully copies C:/COPYME/readme.txt
but when it gets to I:/TEST/red.cat.blue.cat
it gives an

"GetVolumeInformation(The system cannot find the path specified.3) : I:\"
message & the only option available at that point is, Stop.

(Continue & Always Cont. are there too, but grayed out, so you're left with Stop.)

and with Stop, that's it, things, Stop.
and that is even with 'Nonstop' enabled.

so...

should Stop be the only available option?

similarly (as one possible work-around to above)...

say you had various absolute path file names in Source:, & the particular names (volume) were (again) "offline".
so if you had (among other things) in Source:

I:\TEST\red.cat.blue.cat
I:\cats\red.jpg
I:\blue cats\blue.png

if you wanted to set an Exclude filter for the I: volume, entirely, what would that filter be,
or are you even able to do that?

(as in, I: I:* I:\* I:\*\* & anything else I ;-) might have tried were ineffective)

(& so yes, i have Source: of I:/ & various paths there (/TEST/, I itself, /blue cats/)...,
so the Start point of filter check' kicks in, & I have I:/ as the start of the filter,
so 'Absolute path filter' kicks in, which makes it a 'Forward match filter'... (& my head
is spinning ;-))

(yes, i could remove all I: from Source:, but...)

<a href='https://postimg.cc/d7gGvpwh' target='_blank'><img src='https://i.postimg.cc/sXgmPCL4/Fast-Copy-STOPS-if-it-runs-into-an-offline-volume.png' border='0' alt='Fast-Copy-STOPS-if-it-runs-into-an-offline-volume'/></a>

**Comment by shirouzu** [comment]
Sorry, the FastCopy specification requires that the paths explicitly listed in Source must exist.
