### ISSUE TITLE
Ask for elevation instead of just erroring out

### ISSUE THREAD

**Issue by eugenesvk** [FastCopyLab/FastCopy#325]
**Describe the solution you'd like**
If the app isn't elevated, but requires it for ACL copying, it just does the copy but logs `BackupWrite(DIRACL)(Access is denied.5)`
I'd like to have an option instead to **NOT** do the copy, but instead request elevation with an explanation of why it's needed

**Additional context**
At the very least you could not do the copy and show a warning that elevation is needed so I could click on the "elevate" button

**Comment by shirouzu** [comment]
A limitation of BackupWrite is that even if it can be set the ACL, an error message will appear if it doesn't have permission to set the file Owner.
To solve this, it will need to use a different API, but this is something we will consider for the future.
