### ISSUE TITLE
Add a keyboard shortcut for Execute

### ISSUE THREAD

**Issue by eugenesvk** [FastCopyLab/FastCopy#326]
**Describe the solution you'd like**
I've paasted Source path, added `*`, and now the focus of the "Execute" button is lost, so I can't have quickly launch my operation 

**Additional context**
It should be configurable as I'd prefer this to be bound to `E` instead of the `Elevate` button

**Comment by shirouzu** [comment]
I'll consider it.

**Comment by eugenesvk** [comment]
Could you keep the issue open then until it's added so I could track it?

Or do you have another mechanism I could be notified of a feature addition without having to read the changelog on every new version?

**Comment by shirouzu** [comment]
Sorry, but in cases like this, our policy is to close the issue.

**Comment by eugenesvk** [comment]
So what's your policy on how your users can track status update on bugs/features?
