### ISSUE TITLE
Version 5.7.14 with slow transfer rate 

### ISSUE THREAD

**Issue by Rickmn06** [FastCopyLab/FastCopy#327]
**Describe the bug**
Tried to copy some files from an internal hdd to an internal ssd, elevated the fastcopy, and with version 5.7.14 the transfer rate was 0.50Mb/s, then i installed version 5.7.5 (the version i had before) and the transfer rate was 9Mb/s (Windows copy was around 8Mb/s, so i guess the limit is about it, but in latest version was almost 5-10% of it)
Tried with the same files in two computers (both chipset B85) 

**To Reproduce**
Copy files with GUI elevated

**Command line options and various settings**
Default options in GUI

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.7.14 slow / 5.7.5 faster
 - OS ver: Windows 10 Pro

**Comment by shirouzu** [comment]
I was unable to reproduce this issue locally.
(HDD -> SSD, Admin, verify-off)
I would like to know the detailed conditions required to reproduce this issue.

Also, the transfer speed depends heavily on the I/O settings.
Could you please paste the [main] section of fastcopy2.ini from v5.7.14 and v5.7.5?
(It can be found in the File menu → Open FastCopy Dir)
