### ISSUE TITLE
How to replace built-in Windows copy handler by FastCopy?

### ISSUE THREAD

**Issue by tobwz** [FastCopyLab/FastCopy#328]
is there a way to replace the built-in Windows copy handler (for File manager) by (portable) FastCopy?

.....and disable it later again (=revert to built-in if necessary)

I found no option for this

**Comment by shirouzu** [comment]
Please see.
https://github.com/FastCopyLab/FastCopy/issues?q=is%3Aissue+handler

**Comment by shirouzu** [comment]
https://github.com/FastCopyLab/FastCopy/issues/192#issuecomment-5339064796
