### ISSUE TITLE
Auto-removal of already (successfully) transferred files from source list?

### ISSUE THREAD

**Issue by tobwz** [FastCopyLab/FastCopy#329]
Assume I want to copy/move 10 (large) files from src to dest.

The transfer of each file lasts between 5 minutes and 15 minutes.

Unfortunately when a file is already completely transferred it remains on the source list.

Can I somehow let FastCopy remove it from src list automatically?

I want to see only remaining files.

This auto-removal should at least be an user-option.

An even better alternative would be to colorize already completely transferred files in green font in the src list
and with red font the currently transferred file.
Remaining files are shown in normal black

Thank you

**Comment by shirouzu** [comment]
If you use "Diff" copy mode, files that have already been copied will be skipped quickly, so in most cases there will be no problem if you simply re-run the command.
