### ISSUE TITLE
not overwrite, save copy (n)

### ISSUE THREAD

**Issue by Anjade** [FastCopyLab/FastCopy#331]
People send me rars, the names have no system.
It is possible to get 

backup.rar one time a week;

I would like to have:

move!
dont overwrite same name, time, size, do nothing!
change name to name (n), when same name, but differ time/size

Result 
backup.rar
backup.rar (1)
backup.rar (2)

Now I have to write a script, checking if file is there, if same, if only same name, rename to name (n);
start fastcopy

**Comment by shirouzu** [comment]
I will consider it.

**Comment by Anjade** [comment]
Thank you very much; i have searched like crazy for such a function, wondering why it does not exist.
It seems there is also no rar, zip, 7z or other programs that can do that.

**Comment by vanowm** [comment]
> I will consider it.

Closed issue suggests that it won't be considered though..
I mean the way issue tracking (github) normally work is the issues stays opened until it fixed/finished or denied, that's the whole point of tracking - keep them open as reminder until it's done...
and the labels would help identify why they are still opened.
