### ISSUE TITLE
Just one window!

### ISSUE THREAD

**Issue by Anjade** [FastCopyLab/FastCopy#332]
I have
backup mondy.rar
backup tuesday.rar
...
backup sunday.rar

I want to save them on hard disks with names Monday to Sunday.
I have to open seven windows and tell which file to which hard disk.

I would like to do:

Mark files > move with mouse to source
Choose destination
Send the job!

And again
Mark files > move with mouse to source
Choose destination
Send the job!

All in the same window, while there is second window with all my jobs.

And best would be to strg+c, strg+v with fastcopy instead of explorer copy

**Comment by shirouzu** [comment]
I recommend creating a batch file and calling it from the task scheduler.

**Comment by Anjade** [comment]
Yes, you are right, for the example above, i can do it. But there are so many more situations, where it is not to backup the same files every day done by a backup script.

It is also about downloads that happen all the time.

Example: I am working with a forum software with thousands of add-ons; sometimes i look daily, weekly, monthly for new updates and download them. Later i have to move and/or copy them to different webs for the next step uploading to the public webs and updating.

It is never the same thing that i do, there is no need of scripts; or if so i have to add some douzends scripts and one script  that starts them all.

But I like to see, what i do. With Terra Copy, i can do what I need. Mark files, copy, choose destination, insert. I can do this ten times and the jobs are done in a row.

I do this for smaller files. But for larger files I prefer your Fastcopy, but then i have to open many new instances ... what needs so many clicks.

Maybe I am one from tenthousands, but maybe there are much more people using your tool for things like that.

Maybe my point of view is wrong: Your software is done for a special purpose and not to save the whole world. But hey, you have done the fastest one; maybe you want to do also the best one of all of them?

:-)

**Comment by shirouzu** [comment]
Sorry, I can't imagine the details of your operations or situation. (I'm not good at English)

If FastCopy shell extension is enabled, selecting target files in Source in Explorer -> right-clicking and dragging the files to the Dest directory in Explorer, then the files can be copied/moved the files with FastCopy of context menu in Explorer.

If you could show us a video of your operations, I might be able to understand what you mean.
