### ISSUE TITLE
Application Data フォルダ無限ループ対応について

### ISSUE THREAD

**Issue by mateUbuntu** [FastCopyLab/FastCopy#333]
**質問**
自宅でver 5.6.14を使っていますが、2台のパソコンともに以下のエラーが出て困っております。（USERNAMEはマスキングしてます）

FindFirstFileEx(ファイル名を解決できません。1921) : C:\Users\USERNAME\Local Settings\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\　の下の
＊
History\*
Temporary Internet Files\*

の３つのフォルダです。これ以外のフォルダーは非常に長く時間がかかりますが、コピーをしているようです。

Excludeのところに、絶対パスで
C:\Users\USERNAME\Local Settings\Application Data\

相対パスで
*\Application Data\　
または
*\AppData\Local\Application Data\

などいろいろ試しましたが、いつもエラーになって、長時間Application Data\Application Data\.....の無限ループフォルダをFINDしているようです。Excludeでエラー回避できるいい手はないでしょうか？

よろしくお願いします。
<img width="547" alt="2024-08-03_13h21_29" src="https://github.com/user-attachments/assets/3e618277-cc74-4076-894c-86b8b06c440d">

**Comment by shirouzu** [comment]
基本的には、Application Data等が、自分自身を指す symlink で循環参照となっているためで、素のrobocopy/xcopy等でも発生するはずです。
ただ FastCopy では、コピー設定で「Junction/Symlink は（実体/配下ではなく）それ自体をコピー」がデフォルト有効のため、その現象は起きないはずですが、この設定を変更していますでしょうか？

実体をコピーしたい場合は、exclude で外すしかありませんね。
絶対パスでも相対パス（Application Data\\ だけでも可）でも大丈夫のはずですが、お使いの環境で効いていないように見えるのか謎なので、実行画面(FastCopy)全体のキャプチャと、ファイルログのヘッダを載せてもらえますか？

**Comment by mateUbuntu** [comment]
コメントありがとうございます。設定は特に変更したつもりないのですが、
<img width="352" alt="image" src="https://github.com/user-attachments/assets/4fd0f524-52fd-4548-84dc-4d186bc4a844">

ファイルログはこちら（↓）で良いでしょうか？

また、Application\でExcludeした際の実行画面のキャプチャもお送りします。

よろしくお願いします。

[FastCopy(抜粋）.log](https://github.com/user-attachments/files/16486414/FastCopy.log)


Result : (ErrFiles : 96 / ErrDirs : 3) at 2024/08/04 14:10:56
![FINDエラー](https://github.com/user-attachments/assets/1e128734-9e25-42bb-aa18-cb182ecac2a9)

**Comment by shirouzu** [comment]
Application\\ ではなく Application Data\\ を指定してみてください。
それにしても、「それ自体をコピー」有効でも symlink内を辿っているように見えるのは謎ですね…
dir C:\\Users\\<USER>\\AppData\\Local\\ /r /a で表示される  Application Data の行も教えて頂けますか？

**Comment by mateUbuntu** [comment]
ご指摘ありがとうございます。

FASTCOPYのフィルタで「Application Data\」として、「Exclude」すると、Application Data 無限ループのエラー回避ができました！

問題が発生する<USER>\AppData\フォルダのバックアップはできないのですが、(kindleなどの電子書籍情報などもあるのですが）、「Exclude」対応で良しとします。

dir コマンドのApplication Dataの行はこちら（↓）です。
![Dir 情報](https://github.com/user-attachments/assets/ed07b6fd-00e1-4965-9bd5-bc91acc96c0f)

もう一台のWindowsマシンも同じシンボリックリンクのApplication Data無限ループ症状なので、同じ「Exclude」対応をするようにいたします。

いろいろご指導いただき、ありがとうございました。

**Comment by shirouzu** [comment]
解決したようでなによりです。
余談ですが、Application Data が symlinkになっておらず、実際に際限なく子フォルダが存在してますね。
（過去に（symlinkを削除した上で）再帰的なコピーを実施した等の出来事があった気がします）
