### ISSUE TITLE
Specify timestamp AND relative age in /from_date and /to_date?

### ISSUE THREAD

**Issue by appyface** [FastCopyLab/FastCopy#334]
**Describe the solution you'd like**
Example, /to_date="2016/09/26 12:30:56 -10m" 
Meaning, use 12:20:56 as the time

**Additional context**
Referring to above example timestamp with relative age also specified.

My situation is this. The timestamp is generated by another process, that calls my cmd batch files for FastCopy and passes the timestamp in to those as a command line variable. Each execution of FastCopy may be delayed by some minutes, I need to ensure they don't select files any newer than the timestamp. Of course that part already works perfectly. But, I also have the need to only select files that are some minutes older than the timestamp, so using only the relative age won't do that.

Is this easy to add to FastCopy? I am not expert with cmd batch files, but I can try to parse that original timestamp variable and replace it with my desired value, if this enhancement request has no merit.

Thank you for consideration.

**Comment by appyface** [comment]
Also, just to mention, the help webpage documentation needs an update? The syntax should be /from_date="..." and /to_date="..." syntax. They are shown now without any means to pass the values. This section here: https://fastcopy.jp/help/fastcopy_eng.htm#cmdline

**Comment by shirouzu** [comment]
Sorry, I suggest you calculate the required timestamps within cmd.
