### ISSUE TITLE
[Bug] There are some Chinese garbled in the log

### ISSUE THREAD

**Issue by zuilintan** [FastCopyLab/FastCopy#335]
**Describe the bug**
There are some Chinese garbled in the log, 
I have tried to modify the encoding to:
UTF-8
GB2312
GBK
GB18030
Nothing can not let the garbled in the log disappear,
Either Chinese garbled in the file path,
Either the program's own classical Chinese characteristics (e.g. 总读取, 总写入)

**To Reproduce**
Copy, 100% Reproduce

**Command line options and various settings**
No additional settings are required to reproduce

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 5.7.12
 - OS ver: Win11

**Screenshots**
![QQ_1726190238828](https://github.com/user-attachments/assets/53d3a9c5-5f61-4974-9376-6bb21ffe5827)

**Comment by shirouzu** [comment]
It is a cracked version.
Please use the official version.
