### ISSUE TITLE
Unable copy when "Use a modified name" is disabled

### ISSUE THREAD

**Issue by vanowm** [FastCopyLab/FastCopy#337]
When `Use a modified name, if destdir same as src's parent` is disabled, attempting use drag'n drop of a file/folder with right mouse button in explorer into the same folder and selecting in popup menu "Copy", shows:

> Can not continue
> Source and DestDir are identical.

![image](https://github.com/user-attachments/assets/e6c02582-2963-434b-ab00-983abd5ec8f1)

The problem with this message is upon closing it closes whole FC, instead of letting user change parameters.

The expected behavior would be either automatically rename destination with a suffix (just like Windows does), or return to FC main screen where user may change the destination path

Windows 10 x64, FC 5.8.0

**Comment by shirouzu** [comment]
Sorry, that's by design, not a bug.
I recommend to enable "Use a modified name" option, and if you want to rename it to a different name, please do so after copying is complete.

**Comment by vanowm** [comment]
I understand it's "by design", but wouldn't you agree, it's a "bad" design? It doesn't give user any options but close it.

This error also doesn't explain what causing it, I literally had to go through each setting one-by-one to find it, because on my other computer it didn't give this error, and I could hit `cancel` in confirmation dialog and rename destination manually. This doesn't give me this option - that's a bad design.
Maybe we could re-open this issue as "feature request"?
Thank you for this must-have tool!

**Comment by shirouzu** [comment]
> This error also doesn't explain what causing it,

??
The cause is "Source and DestDir are identical".

**Comment by vanowm** [comment]
Sorry, I meant to say the relationship between the setting and error message.

Perhaps in addition to just a `stop` button, there could "rename" button, which would temporary activate the `Use a modified name, if destdir same as src's parent` setting just for this single action...

Anyway, please don't dismiss this and hopefully it will be considered in the future.

Thank you.
