### ISSUE TITLE
質問：メール以外で自分が購入したライセンスキーを知る方法

### ISSUE THREAD

**Issue by mbook0319** [FastCopyLab/FastCopy#338]
**質問**

FastCopyProを使用するPCを変更するにあたり、ライセンスキーが必要となりました。
しかし購入完了メールを紛失してしまいライセンスキーがわからなくなってしまいました。
購入完了メール以外でライセンスキーを知る方法を教えていただけないでしょうか

**備考**
FastCopyにはライセンスキーは表示されていません
以下は私のFastCopyのライセンス画面のキャプチャです
![image](https://github.com/user-attachments/assets/d8887a1c-e1d3-4b09-a4c6-09a1d762c274)

どうぞよろしくお願いします。

**Comment by shirouzu** [comment]
（ライセンスメール以外からはライセンスキーを知る方法はないため）後ほど、ご購入頂いたメールアドレス宛に、ライセンスメールを再送いたします。
少々お待ちください。

**Comment by mbook0319** [comment]
早速の対応ありがとうございます。
メール確認いたしました。
