### ISSUE TITLE
ファイルログ内容の追加・更新・削除フィルタ

### ISSUE THREAD

**Issue by SysVR** [FastCopyLab/FastCopy#339]
**機能リクエスト内容**
リストアップ時に追加、更新、削除と表示内容をフィルタリングできるようにしてほしいです。
例えば、削除の場合に削除のみチェックを入れると削除されたファイルのみがリストに表示されます。

**補足**
機能リクエストに関する補足やスクリーンショットがあれば、ここに追加します。

**Comment by shirouzu** [comment]
ちょっとニッチっぽい感じがしますけど、一応、検討しておきます。
