### ISSUE TITLE
skip destination folder

### ISSUE THREAD

**Issue by janus-c** [FastCopyLab/FastCopy#34]
We use fastcopy sync from windows to NAS, 
when set NAS snapshot function on, logged access denied with snapshot folder.
Is there any way to skip specific destination folder ?

**Comment by shirouzu** [comment]
Please paste source/dest dir and error-log

**Comment by janus-c** [comment]
batch file：
D:\FastCopy\FastCopy.exe /cmd=sync /estimate /bufsize=256 /speed=full /Logfile="D:\FClog\cfgbak.log" /Force_Close "D:\ConfigBackup" /to="\\192.168.6.24\ConfigBackup"

log file：
RemoveDirectory(存取被拒。5) : \\192.168.6.24\ConfigBackup\#snapshot\GMT+08-2022.02.12-21.00.03\ApSrv
DeleteFile(存取被拒。5) : \\192.168.6.24\ConfigBackup\#snapshot\GMT+08-2022.02.12-21.00.03\Client\CDivStatic.cfg
 Too Many Errors...

存取被拒=access denied

**Comment by shirouzu** [comment]
Please try exclude="\\#snapshot\\"

**Comment by janus-c** [comment]
batch file：
D:\FastCopy\FastCopy.exe /cmd=sync /estimate /bufsize=256 /speed=full /Logfile="D:\FClog\cfgbak.log" /Force_Close exclude="\#snapshot\" "D:\ConfigBackup" /to="\\192.168.6.24\ConfigBackup"

got pop-error with "Can not Continue：The specified path could not be found"

![2022-02-17_101604](https://user-images.githubusercontent.com/72491726/154391740-f1490379-fc90-44ce-8668-3cfd07f7ae4d.png)

**Comment by shirouzu** [comment]
Sorry / is required.
/exclude="\\#snapshot\\"

**Comment by janus-c** [comment]
thank you, it works!!
and THANK YOU again for this tool!! It's really helpful!
