### ISSUE TITLE
ファイルおよびフォルダの更新日時が「コピーした時間」になることがあります(回避方法あり)

### ISSUE THREAD

**Issue by nonakatatsuya** [FastCopyLab/FastCopy#340]
**エラー内容**
ファイルおよびフォルダの更新日時が「コピーした時間」になることがあります。

古いバージョンでは発生していなかったため、投稿をいたしました。
Logファイルを確認すると、5.7.12までは発生せず、5.7.14, 5.7.15, 5.8.0で発生しています。
(記載のない途中バージョンはアップデートを飛び越えています)

下記の投稿と状況が似ております。
ファイルおよびフォルダの更新日時が「コピーした時間」になることがある
https://groups.google.com/g/fastcopy/c/ryNuQceyBEQ?pli=1

但し、特殊な条件と思われる部分があるので、調査が困難な場合スルーしていただいても問題ありません。

- Synology社のNas(こちらは DiskStation DS923+)に接続している外付けHDDがコピー先
  - コピー元は外付けHDDを接続しているNasです
  - 外付けHDDフォーマットがNTFS(ext4でフォーマットされた外付けHDDでは発生しません)

＜回避方法＞
- srcにファイルを指定
- コピーする階層を2層以下にする
- Synology社のNasの外付けHDDのフォーマットをNTFS以外にする(ext4等)
- ベリファイ(従来/完全)チェック＆「ベリファイが完了するまで、タイムスタンプを1980-01-02に」チェック

**再現方法**
FastCopyにてコピーした際、ファイルおよびフォルダの更新日時が「コピーした時間」なります。

エクスプローラーでファイルをコピーした際には発生しません。
発生しないフォルダ・ファイルもあります。
作成日時は元ファイルと同じになります。
動作モードで、差分3種、コピー、同期を試しましたがすべてで発生します。
既にファイルがある場合は更新日時が最新の「コピーした時間」になります。
srcに問題となるファイルを指定すると発生しません。
srcに問題となるファイルのパス及びその親パスを指定すると発生しません。

＜試したこと＞
- ベリファイ(従来/完全)チェック → 効果なし
- ベリファイ(従来/完全)チェック＆副次Streamチェック → 効果なし
- ベリファイ(従来/完全)チェック＆副次Streamチェック&ベリファイ情報を付与チェック → 効果なし
- ベリファイ(従来/完全)チェック＆「ベリファイが完了するまで、タイムスタンプを1980-01-02に」チェック → 効果あり

**コマンドライン・オプションや各種設定**
FastCopy2.iniを削除して設定をリセットした状態です。
(GUI及びコマンドラインの両方とも発生)

**バージョン・環境**
FastCopy ver（原則として最新版のみ） : 5.8.0(Pro版)
OS ver: Windows 11 Pro 23H2

**Comment by shirouzu** [comment]
手元に Synology NAS が無いため、Linux 6.10 + Samba 4.17.12 + NTFSフォーマットしたUSBメモリで試して見ましたが、残念ながら再現できないですね。
あと不思議なのは、5.7.12 → 5.7.14 では速度統計とCtrlキーの扱い以外は変更がないため、タイムスタンプ系の動作に違いが出ると考えづらいことです。

**Comment by nonakatatsuya** [comment]
検証ありがとうございます。
また、5.7.12 → 5.7.14では当該の現象を発生させる要因でないこともご確認ありがとうございました。

Windows UpdateかNasのファームウェア更新が原因になりそうですね。
数ヶ月前のことなので、どの変更によるかの特定は難しいのでクローズしたいと思います。

この現象を期にFastCopyの新機能等を改めて知り、色々試すことができ、勉強になりました。
あらためて、検証及び確認ありがとうございました。
