### ISSUE TITLE
デフォルトの移動方法について

### ISSUE THREAD

**Issue by copyfast64** [FastCopyLab/FastCopy#341]
**質問**
お世話になります。

Pro版のラインセンスを購入しました。

誤って同名ファイルを上書きしないため、移動時のデフォルトで「移動（上書きなし）」に設定したいと考えています。

設定を確認したのですが、【「移動（全上書き）」を「移動（日付・サイズ）」 に変更】しか見つけることが出来ませんでした。
今はファイルの移動開始前に、毎回「移動（上書きなし）」に変更しています。

移動時のデフォルトを「移動（上書きなし）」に変更する方法はないでしょうか。
お手数ですがよろしくお願いします。

**備考**
補足やスクリーンショットがあれば追加してください。

**Comment by shirouzu** [comment]
確かにあると良いですね。
（他の動作との悪い副作用がなければ）前向きに検討してみます。
