### ISSUE TITLE
同期（サイズ・日付）のチェックが間違っていませんか？

### ISSUE THREAD

**Issue by polycanmei** [FastCopyLab/FastCopy#342]
「症状」
定期的に
「G:\」　←480GB-2.5インチSSD
　↓ 同期（サイズ・日付）
「D:\」　←480GB-2.5インチSSD
をしています

毎日確実に発生するわけではありませんが、
同期した一週間後などに同期すると、同じ（サイズ・日付）のファイルがあるにも関わらず

[＋] D:\....\（見本）.doc   <20010611-113746 26,112>　
　　←「リストアップ」の表示
と追加しようとしています

　　　D:\....\（見本）.doc   <20010611-113746 26,112>
　　　23年前の、更新日時「20010611-113746」のファイルなんか、間違っても
　　　中身を更新などしているはずはありません
　　　なお「ー」D:\....\（見本）.doc 　というの行はなく、削除自体はされていません
　　　つまり、D:\....\（見本）.doc　はないと誤判断されているので追加！となっています
　　　無論実際は、D:\....\（見本）.doc　はちゃんと存在しています
　　　■正論では、D:\....\（見本）.doc　は何もしないでスキップすればいいだけです

　　　「可能性」
　　　D:\....\（見本）.doc　はなぜないと誤判断されているのか？あるいは
　　　あるけども、更新日時が違うと判断されているのか？
　　　ここを確かめるべきと思います

「検証済」
以下の通り2つのファイル

G:\.....\(見本).doc
D:\.....\(見本).doc

の「サイズ・日付」は100%一致しています（無論中身も）

■ふたつのソフトで検証済なので、人間の見間違いなどはありません
---------------------------------------
●WinMerge ファイル比較「更新日時とサイズ」
G:\.....\(見本).doc
D:\.....\(見本).doc

●FreeFileSync フォルダ比較「ファイル時刻とサイズ」
G:\.....\
D:\.....\

----------
Windows10 22H2 pro 64bit
FastCopy Ver5.8.0 64bit
----------

特に実害がないようなのでいままで黙っていました。。。
相当前から発生して気づいていました

「Gのファイルの更新日時」
![Gの日時](https://github.com/user-attachments/assets/d38ae2f7-0de3-444a-bffb-77429daa54a2)

「Dのファイルの更新日時」
![Dの日時](https://github.com/user-attachments/assets/7ac98a33-3512-452d-acf0-7f9b132a3e4c)

![更新日時とサイズ](https://github.com/user-attachments/assets/27c2e5ed-2eb0-4c27-9196-1e593a42bc95)

![同一](https://github.com/user-attachments/assets/49b82e80-39a3-4b5f-a9d4-3f193aa9d6ca)

**Comment by shirouzu** [comment]
聞いたことが無い現象ですねぇ…

Source / DestDir ともに内蔵ドライブですか？（それともNAS等ですか？）
時折、発生するとの話ですが、
・リストアップで更新予定と表示された場合、何度リストアップしても同じファイルが更新予定となりましたか？
・今現在も、リストアップで更新予定のファイルが発生していますか？
・I/O設定で、ディレクトリ読み取りの「一括読み取りを有効にする」を外しても再現しますか？

再現性ある場合は、fastcopy2.ini の [main] セクションに debug_flags="1" を追加して、リストアップした結果（下記のような表示が出ます）を貼り付けてください。
DBG(compare): mode:2 flag=262000110 fs=f21/f21 grace=0/0 mtime=1dac9452dee1ae8/1dac9452dee1ae8 ctime=1dac9452b80d5b0/1dac9452b80d5b0 attr=20/20 resv=7ff7/50 size=484074/484074 fname=xxx.pdf

**Comment by polycanmei** [comment]
>Source / DestDir ともに内蔵ドライブですか？（それともNAS等ですか？）

普通のディスクでNAS等ではありません
G:\　←SATA接続(内蔵)
D:\　←USB接続(外付け)


>時折、発生するとの話ですが、
>・リストアップで更新予定と表示された場合、
>何度リストアップしても同じファイルが更新予定となりましたか？

確かに本当は毎日発生して欲しかったですが、それはありませんでした
一週間程度開けるとでます

■いまも試して、ちゃんと連続ででました　以下の通り

２回目
[＋] D:....\（見本）.doc <20010611-113746 26,112>　
３回目
[＋] D:....\（見本）.doc <20010611-113746 26,112>　


・今現在も、リストアップで更新予定のファイルが発生していますか？

はい
３回目まででました（上記）


・I/O設定で、ディレクトリ読み取りの「一括読み取りを有効にする」を外しても再現しますか？
はい　でました
４回目
[＋] D:....\（見本）.doc <20010611-113746 26,112>


>再現性ある場合は、fastcopy2.ini の [main] セクションに debug_flags="1" を追加して、
>リストアップした結果（下記のような表示が出ます）を貼り付けてください。
>DBG(compare): mode:2 flag=262000110 fs=f21/f21 grace=0/0 mtime=1dac9452dee1ae8/1dac9452dee1ae8 ctime=1dac9452b80d5b0/1dac9452b80d5b0 attr=20/20 resv=7ff7/50 size=484074/484074 fname=xxx.pdf

この意味は分かりませんでした
●画面にはこのような表示はでません
特にファイルもできてないと思います
fname=xxx.pdf　というファイルがどこかにできているんですかね？？

**Comment by polycanmei** [comment]
>再現性ある場合は、fastcopy2.ini の [main] セクションに debug_flags="1" を追加して、
>リストアップした結果（下記のような表示が出ます）を貼り付けてください。

fostcopyを●閉じて、再起動で、８行でました
以下添付します

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6315c58064/1d8eb6315c58064 attr=2020/2020 resv=0/e6 size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6315c58064/1d8eb6315c58064 attr=2020/2020 resv=0/e6 size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

DBG(compare): mode:2 flag=a02400130 fs=f21/f01 grace=0/0 mtime=1c0f21f7f4c7900/1c0f21f7f4c7900 ctime=1d8eb6449fe3aa8/1d8eb6449fe3aa8 attr=2020/2020 resv=0/999b size=26112/26112 fname=（見本）.doc

＜参考＞
「＋」 D:\....\（見本）.doc   <20010611-113746 26,112>

**Comment by shirouzu** [comment]
これらのDBG内容を見る限り、これらのファイルは skip になりそうですが、一部 or 全件で、更新(+)表示されたということですか？
DBG行だけではなく、「リストアップした結果」を貼り付けてもらえますか？

**Comment by polycanmei** [comment]
>これらのDBG内容を見る限り、これらのファイルは skip になりそうですが、

そうです
スキップ処理の間違いはありませんか？


>一部 or 全件で、更新(+)表示されたということですか？

さすがに全部を検証していません


>DBG行だけではなく、「リストアップした結果」を貼り付けてもらえますか？

一旦DBG行をやめて、本来の「リストアップした結果」を貼り付けですか
５４６５５行全部ですか？

そうすると全部のファイル名が明らかになってしまいます

さすがにこれからファイル名全部の加工をすれば徹夜になりかねません
難しいですね

他の方法はありませんか？

**Comment by shirouzu** [comment]
いやいや、もし本当に頻発してるなら、ターゲットを絞った source /destdir 指定で再現するのでは？

**Comment by polycanmei** [comment]
少々頭を冷やしてみます
思い違い？
SSDの異常？
ファイルシステム壊れ？

含め検証してみます

進展があればまた報告します
一旦忘れて、他を優先いただければ効率的かと、思います

なお、もし可能でしたらリストアップに
「スキップ」という一行が欲しいです
今回ログに
「ー」 削除
「＋」 追加
しかないので、混乱していました

「S」 スキップ

いままでずっと欲しいと思っていました
