### ISSUE TITLE
batch operation order

### ISSUE THREAD

**Issue by rond056** [FastCopyLab/FastCopy#343]
Hi,
Hope someone can help.
I have a batch file that runs several copy operations for syncing two disks.
Due to my directory set up, the copying operations will need to follow a certain order, in other words they cannot run simultaneously.
In parallel running settings I limited the process to 1.
That seems to be stopping the simultaneous running.
But for some reason, the program is not following the copying order in batch files?
Is there a way to achieve that please?
Thank you,
Ron

**Comment by shirouzu** [comment]
I'm not sure about the situation, but if it's a batch run, using fcp.exe instead of fastcopy.exe might solve the problem.

**Comment by rond056** [comment]
Thank you. I appreciate the quick response.
I did a quick test, and indeed, it seems to be following the order.
The nice thing about using fastcopy.exe is that I am able to define the rules via the GUI. 
Based on my initial observation, they are still valid when using the fcp.exe. Can you confirm that please?
Also the command window is disappearing after the job is finished.
Is there a way to keep it up for checking it?
I'm afraid, I have already asked too many questions.
Thanks again

**Comment by shirouzu** [comment]
fcp.exe uses the same settings as fastcopy.exe.
You can also use in the following command instead of fcp.exe.
 start "" /wait fastcopy.exe ...

**Comment by rond056** [comment]
Many thanks
