### ISSUE TITLE
backup android to pc

### ISSUE THREAD

**Issue by hyky12** [FastCopyLab/FastCopy#345]
Hi, when you long press a folder in Android, the program does not select the folder. Is there a solution to this?

**Comment by shirouzu** [comment]
The Android folder in Explorer is a pseudo file system.
It cannot be accessed with the Win32 file API, so it cannot be accessed with FastCopy. (The same is true for robocopy and xcopy.)
However, I am considering a mechanism to handle pseudo file systems in the future.

**Comment by hyky12** [comment]
Thank you very much for the answer
