### ISSUE TITLE
estimate destination freespace before copying ,copy interrupted disk is full 

### ISSUE THREAD

**Issue by mantrasiva** [FastCopyLab/FastCopy#36]
Hi
I have some issues copying file with fastcopy 4.1 ,because the disk was full
could be added an estimate destination freespace ?
about listining feature would be great if we could customize , mib doesn't help
TotalSize  = 435,280 MiB
TotalFiles = 10,423 (4)
TotalTime  = 0.0 sec

---- Listing Done ----

TotalSize  = 435,280 MiB should be 425 GB (456.424.917.594 byte) right? 
sometime it's hard to calculate Mib to GB or TB
thanks
Love facopy ♥

**Comment by FastCopyLab** [comment]
Sorry, I'm not really interested in that.
