### ISSUE TITLE
How to delete files but not folders (root folder or all folder)?

### ISSUE THREAD

**Issue by qwas368** [FastCopyLab/FastCopy#38]
**Question**
I want to delete folder file and keep my folder structure, but FastCopy will delete all empty folder.
It is a common scenario and I can't find any related function in FastCopy. 
How to delete files but not folders ?

**Comment by FastCopyLab** [comment]
Try to set * to the include filter.

**Comment by qwas368** [comment]
It's worked! Thansk for your reply.
