### ISSUE TITLE
Request ability to play Success and Error sounds.

### ISSUE THREAD

**Issue by a-raccoon** [FastCopyLab/FastCopy#39]
Currently it is not possible for FastCopy to play a success-sound when there is a success, and an error-sound when there is an error.  You have to choose either one event or the other to play a sound, but not both.

This behavior is handled through the Option -> Post-Process menu, and the Add/Modify/Del editor gives you the option to Play Sound [file] after FastCopy completes its operation, or, with a checkbox option; Only play if an error occurred.

I wish to request the ability to select a Success Sound file and an Error Sound file.  FastCopy will then play the appropriate sound file when there is either a success or a failure.

**Comment by FastCopyLab** [comment]
hum...

**Comment by a-raccoon** [comment]
I intended to make this suggestion 20 years ago, but it slipped my mind. :)

Here are a couple of sounds you might consider packaging with FastCopy...

[done.wav.zip](https://github.com/FastCopyLab/FastCopy/files/8117641/done.wav.zip) 10KB
[error.wav.zip](https://github.com/FastCopyLab/FastCopy/files/8117644/error.wav.zip) 7KB
