### ISSUE TITLE
Open Source FastCopy

### ISSUE THREAD

**Issue by peter-fb** [FastCopyLab/FastCopy#4]
On the homepage you state the following:

> Due to various circumstances, distribution of the source code is temporarily suspended ... Please use FastCopy as freeware with no guarantee

Please make the project open source again.

**Comment by FastCopyLab** [comment]
I am considering it.
Basically, if it is beneficial to me, I will do so.
Are you able to present it to me?

**Comment by PapaKarl0** [comment]
My two cents. It's not  financially beneficial so I guess that's the end of the conversation lol
As long as the project is being developed I'm perfectly fine with it being proprietary. Hell, I'd pay for it if it wasn't free.
