### ISSUE TITLE
fastcopy  to debian 11 samba  error

### ISSUE THREAD

**Issue by lisztk666** [FastCopyLab/FastCopy#40]
**Describe the bug**
hello, I use fastcopy to copy files to debian11 samba (with the maximum permissions), in win10 open samba some files will appear occupied or no permissions, and then fastcopy from debian11 samba fastcopy back to win10, an error log will appear

**To Reproduce**
setp1 . win10 fastcopy file to debian_11 samba (win10 open samba some files will appear occupied or no permissions )
          
setp2 . debian_11 fastopy filet to win10 disk (errorlog appears: Read File(file is modified ))
           ( But using robocopy copy in the first step and fastcopy in the second step does not have this error log)

**Command line options and various settings**
use  fastcopy windows default set copy

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.1.0
 - OS ver:   debian 11  <==>win10  (error)

**Screenshots**

![errorlog](https://user-images.githubusercontent.com/75466918/154887594-d723d4bb-a06d-4483-8006-86c0c6cfe741.jpg)

**Comment by shirouzu** [comment]
What is "with the maximum permissions"?
and what is "win10 open samba some files will appear occupied or no permissions "?

**Comment by lisztk666** [comment]
Hi, Dear Shirouzu
I have tried to use Fastcopy program to copy files to SAMBA Server (Debian 11), First, the Client(Win10) use 777 mode write files via Fastcopy with no error. But I can't open the file. It will show the "file is modified or ocuupied". Second, I update the files via I Steps to reproduce with another way,If I use Windows Explorer or Windows Command XCOPY or ROBOCOPY to copy files to SAMBA Server, No error happened as describe as above.Could you assist me to check what step do I need fix or check? Thank you very much.

**Comment by lisztk666** [comment]
Hi, Dear Shirouzu
I have tried to use Fastcopy program to copy files to SAMBA Server (Debian 11), First, the Client(Win10) use 777 mode write files via Fastcopy with no error. But I can't open the file. It will show the "file is modified or ocuupied". Second, I update the files via Fastcopy, It shows on th pic that I post. 
I Steps to reproduce with another way, I use Windows Explorer or Windows Command XCOPY or ROBOCOPY to copy files to SAMBA Server, No error happened as describe as above. Could you assist me to check what step do I need fix or check? Thank you very much.

**Comment by shirouzu** [comment]
> the Client(Win10) use 777 mode 

Win32 doesn' have UNIX style permission.
How do you confirm it?

> But I can't open the file. It will show the "file is modified or ocuupied".

who did say this message? (FastCopy never say "occupied")
(Please use "copy and paste" or "capture", please do not translate.)
