### ISSUE TITLE
Source File Log

### ISSUE THREAD

**Issue by Bzmonnerat** [FastCopyLab/FastCopy#41]
**Question**
Hello. I would like to know how can I create an output as txt of the full source path of the files I copied.

**Remarks**
Running last version on win server 2012 r2 by command line

**Comment by FastCopyLab** [comment]
Why do you need a source log instead of a dest log?

**Comment by Bzmonnerat** [comment]
To know where they came from.

Em ter., 22 de fev. de 2022 10:47, FastCopy Lab, LLC. <
***@***.***> escreveu:

**Comment by FastCopyLab** [comment]
I think it is possible to guess the source path from Dest log (with source/destdir command).

**Comment by Bzmonnerat** [comment]
Ok I will try. Working around using xcopy /L

Thanks

Em ter., 22 de fev. de 2022 10:57, FastCopy Lab, LLC. <
***@***.***> escreveu:
