### ISSUE TITLE
MAX_PATH (260 characters)

### ISSUE THREAD

**Issue by DnsIs** [FastCopyLab/FastCopy#47]
It supports UNICODE and over MAX_PATH (260 characters) file pathnames.

Please tell me how to arrange enable support for paths greater than MAX_PATH  (260 characters)?
The thing is, I can't find any program that would allow me to work with long paths.
All I need is just to get information about the file (size, attributes, time)
`(for example ls -lR)`

I don't need details, just please tell me which functions to use?

**Comment by shirouzu** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexw

**Comment by a-raccoon** [comment]
> I can't find any program that would allow me to work with long paths. All I need is just to get information about the file (size, attributes, time)

The program Everything by VoidTools handles MAX_PATH constraints elegantly.  Also displays the file details you're looking for.

**Comment by DnsIs** [comment]
[shirouzu](https://github.com/shirouzu), [a-raccoon](https://github.com/a-raccoon), Thanks.

> The program Everything by VoidTools handles MAX_PATH constraints elegantly. Also displays the file details you're looking for.

Yes, I know about this program, but I need solutions for embedding in scripts.
I think to write a simple utility that will simply show everything that I need.

**Comment by shirouzu** [comment]
Can you please stop talking about things that are not related to FastCopy?
