### ISSUE TITLE
10%ベリファイなどはできますか？

### ISSUE THREAD

**Issue by myinhyonjun** [FastCopyLab/FastCopy#48]
現状の100%ベリファイは有益ですが、
時間がもったいないです
実際ベリファイエラーここ３年間出ませんでした
10%ベリファイすればベリファイエラーがでるかでないか
推測できそうですが、、？

仮に、10%ベリファイで不安なら自分で残り90%をベリファイできますからね

**Comment by shirouzu** [comment]
できません
