### ISSUE TITLE
Copy from attached mobile device filesystems

### ISSUE THREAD

**Issue by RobWhittlestone** [FastCopyLab/FastCopy#49]
Fastcopy won't copy photos or folders from iPhone DCIM directory to Intel+WIndows 10 environment user's Pictures directory. 
The iPhone source descriptor is not recognized as a valid source. 

**Additional context**

**Comment by shirouzu** [comment]
FastCopy requires to access via Win32 File API.
But it is pseudo filesystem that can only access via explorer. (MTP/PTP or etc)

Please try to use xcopy/robocopy. (I think it will be failed)
