### ISSUE TITLE
Shrink to Root Folder

### ISSUE THREAD

**Issue by GaryMMugford** [FastCopyLab/FastCopy#5]
As Windows has developed more complex api's, certain utilities we value that worked in WinXP or Win 7 stop working in the newer versions. For me, Shrink To This Folder as a right-click menu choice was indispensable. I'd collect whole trees into one folder (name conflicts being auto handled with a numbering system until the move will work). About once a week, I'd need it. But it doesn't work anymore. It DOES strike me that it wouldn't be hard to write a function into FastCopy that would copy ALL files including sub folders to targetFolder without replicating tree. This would be greatly appreciated because I've never found a relevant hack that worked without issue in Win10 and I doubt Win11 will suddenly start allowing this old code. Thanks for reading. GM

**Comment by FastCopyLab** [comment]
I will consider it.

**Comment by GaryMMugford** [comment]
Thank you for thinking about it. That's better than existed last week. Please have a safe and sane rest of the Holiday Season. All the best to you and yours, GM
