### ISSUE TITLE
factcopy 4.1.1 is very slow to launch.

### ISSUE THREAD

**Issue by phy2022** [FastCopyLab/FastCopy#50]
factcopy 4.1.1 is very slow to launch it takes about 15 seconds , version 3.92 takes 1 second to open. 
system
Windows 10
Cpu TR3990x
128GB ram 
firecuda 530

**Comment by shirouzu** [comment]
Always? Or is it for the first startup?

**Comment by phy2022** [comment]
> Always? Or is it for the first startup?

I found out why this happened 
The problem was with the Comodo firewall, as it was blocking Fastcopy from connecting to the Internet. After I removed the entry in the firewall, no delay in the launch.

**Comment by shirouzu** [comment]
This is probably due to the fact that FastCopy v4 was self-verifying signatures.
In the latest v4.1.2, we intend to avoid the delay problem by delaying the verification to exception dump time.
