### ISSUE TITLE
Commandline option - /dlsvt 

### ISSUE THREAD

**Issue by KamikazeePL** [FastCopyLab/FastCopy#51]
Fastcopy ver4.1.1

What is **/dlsvt** this option in command line?
No informations in help.

**Comment by shirouzu** [comment]
Thank you for your report. I will add it to the help.
/dlsvt means Daylight Saving Time.
![image](https://user-images.githubusercontent.com/1759911/157976607-7d588678-a61d-4659-b1a0-f25bab8f68b6.png)
