### ISSUE TITLE
Very slow after Windows patches?

### ISSUE THREAD

**Issue by krilbe** [FastCopyLab/FastCopy#53]
**Description**
Our hosting provider recently upgraded our Windows Server 2019 Web with some Microsoft Update patches (KB5011503 and KB5011267). After that FastCopy has become over 20 times slower than before. A file of 145 Gbyte that seems to take about 35 minutes for Windows Explorer takes 3+ hours for FastCopy.

I'm using the same settings as before: Diff HDD mode and "Auto Slow" setting. Changing to "Full Speed" seems to be even slower, or about the same as "Auto Slow". We haven't changed anything else on this system (unless our hosting provider did something I'm not aware of, like upgrade FSecure).

**Command line options and various settings**
Not sure what's different from standard, but: Buffer Size 2048, I/O unit 1, Overlap I/O Num 8, nothing else checked except "Enable Large fetch mode". "Estimate" checked. "Nonstop" checked. "Verify" unchecked.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.1.2
 - OS ver: Windows Server 2019 Web

**Comment by shirouzu** [comment]
Would there be any change if I set the main buffer to 512 MB?

**Comment by krilbe** [comment]
No change, sorry. Seems to take almost 3 hours according to estimate after about 8 %.

**Comment by krilbe** [comment]
I should mention that the shorter times for Windows Explorer and Beyond Compare were probably caused by disk cache. After about 10-20 Gbyte, they slowed down, and would probably have taken much longer than 3 hours to complete if I had let them continue. The server has 64 Gbyte RAM, ~25 Gbyte free (including space taken by Windows disk cache).

**Comment by shirouzu** [comment]
Please compare speeds after eliminating the effect of cache.

**Comment by krilbe** [comment]
Difficult to do since the server should for the most part be up and running, and I also think the above scenarios fully explains that FastCopy is still faster than regular Windows file copy as well as Beyond Compare's file copy (which may actually be using Windows API to perform file copy).

But it doesn't explain why FastCopy would suddenly be 15-20 times slower than before last weekend. That said, it would seem that Windows file copy is also several times slower than before, which would point towards a hardware or infrastructure problem rather than a FastCopy problem.
