### ISSUE TITLE
ログ設定の履歴数

### ISSUE THREAD

**Issue by gnanashi** [FastCopyLab/FastCopy#54]
ログ設定の履歴数を0に設定すると次回起動時に既定の10に戻されます
(INIファイルではmax_history=0)
仕様変更ですか?

下記の環境で確認しました
OS=Win10_x64(21H2) FastCopy=64bit|32bit
OS=Win10_x64(20H2) FastCopy=64bit|32bit
OS=Win10_x32(20H2) FastCopy=32bit
OS=Win10_x64(1803) FastCopy=64bit|32bit
OS=Win7_x64(SP1)   FastCopy=64bit|32bit
OS=WinXP_x32(SP3)  FastCopy=32bit

**Comment by gnanashi** [comment]
FastCopyのバージョンを書き忘れました
4.1.2です

**Comment by shirouzu** [comment]
別件の問題修正の余波でした。
次のバージョンで修正しておきます。
