### ISSUE TITLE
FastCopy no longer preserves Date Modified timestamps (All 4.x versions)

### ISSUE THREAD

**Issue by a-raccoon** [FastCopyLab/FastCopy#55]
Since the departure of FastCopy 3.x to FastCopy 4.x, file and folder Date Modified timestamps are no longer preserved from the source to the destination.  Only the Date Created timestamps are preserved.  All of the Date Modified timestamps are representative of the time that the file was written during the copy, not the source timestamp.

This has now destroyed many backups.

Could this be caused by writing AltStream :fc_verify data? I have not tested.

**Comment by shirouzu** [comment]
Please use this template.
[https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=](https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by a-raccoon** [comment]
Have you been able to confirm the bug so I don't have to use this template?  Or do you actually require me to use this template for you to recognize the bug?  You are asking me to perform extra effort involving physical transit and exploratory surgery, which might not be needed of me.

**Comment by shirouzu** [comment]
If you don't use this template, we can't support.
In particular, it is important to clarify the environment, conditions, and procedures for reproduction.

**Comment by shirouzu** [comment]
If you don't want to pay the effort to report a reproducible procedure, please don't report your problem.

**Comment by myinhyonjun** [comment]
You don't have to be so angry, do you?
It's just a bug report.

**Comment by shirouzu** [comment]
If someone report a bug in this forum, he must follow its rules.
[https://github.com/FastCopyLab/FastCopy/issues/new/choose](https://github.com/FastCopyLab/FastCopy/issues/new/choose)

**Comment by a-raccoon** [comment]
I have reproduced the bug in FastCopy 4.1.2.  The bug is caused by the option `[x]Add verifyInfo. (AltStream(:fc_verify) with hashinfo etc)` . When this option is enabled, then all file Date Modified timestamps are not preserved.  When this option is disabled, then all file Date Modified timestamps are successfully preserved.

This is the extent of my bug report.  My rules.  My Bug Bounty fee is $100 USD.  You're welcome.

**Comment by shirouzu** [comment]
The impotant information is the type of destination drive.
I can't reproduce it in local NTFS and samba(4.13)

**Comment by a-raccoon** [comment]
The source drive is NTFS and the dest drive is NTFS.  AltStream data only exists on NTFS.

I recommend applying file timestamps again after writing AltStream verify data.

**Comment by shirouzu** [comment]
Always, the timestamp is set last.
Otherwise it would have reproduced in my/every environment.

What is Your OS version?

**Comment by shirouzu** [comment]
And dest drive is Network Machine's NTFS or local drive?

**Comment by shirouzu** [comment]
Please learn why the template is required.

**Comment by a-raccoon** [comment]
A Windows 2008 Server running backups between two local NTFS disks, one SATA one USB, drive letters C and D.

That's Windows 7 equivalent.

**Comment by shirouzu** [comment]
Which is Server2008 or Server2008R2 ?
And Destination info is important, destination=USB?

**Comment by shirouzu** [comment]
I could reproduce. The point was OS version.
The problem occurs in Win8 or earlier.
Thank you.
