### ISSUE TITLE
portable version "Extract only" on folder without creating sub folder

### ISSUE THREAD

**Issue by NSP-0123456** [FastCopyLab/FastCopy#56]
Using the installer to extract only FastCopy always create a subFolder. 
Could it be possible to add an option to not create subfolder ?
i.e. I select c:\tools\FastCopy as target folder and all is extracted in this place instead of extracting into a sub folder c:\tools\FastCopy\   >>>FastCopy4.x.y_x64<<<<

**Comment by shirouzu** [comment]
Hum... Why not use installation?

**Comment by NSP-0123456** [comment]
I was told to use extract only for "portable installation" (No registry, No Shortcut, No Menu Entry ...)  i can sync to multiple computer from a network share which should have the same name..

**Comment by shirouzu** [comment]
OK.
It can be used this command line option.
C:\> fastcopy..._installer.exe /extract /nosubdir

**Comment by NSP-0123456** [comment]
This is a silent extract in current dir ! '
I was not aware of any commad line option of the installer.
Many thanks for this as it works out of the box.
