### ISSUE TITLE
Issue when using through task scheduler 

### ISSUE THREAD

**Issue by alextg50** [FastCopyLab/FastCopy#57]
Hello there,
whenever i try to use FC from task scheduler (its on a Windows Server 2019), i get an error :

GetVolumeInformation(The system cannot find the path specified.3) : Z:\
Initialize Error

I should say here that Z is a network drive. I saw somewhere else that i need to use "net use" to somehow wake up the drives .... tried it but nothing.
If i put the command to a batch file and run it ,, FC opens just fines and starts doing its thing.
If i put the batch file to task scheduler , it doesnt run ... it gives me that error.
Any ideas on what i can do about it ?
Thank you

**Comment by shirouzu** [comment]
Please search google with the following keywords.
 Task scheduler with network drive letter

**Comment by alextg50** [comment]
Thanks alot for your help !
