### ISSUE TITLE
VeraCrypt volumes

### ISSUE THREAD

**Issue by jk-85** [FastCopyLab/FastCopy#58]
First: For me FastCopy is the best tool for years now doing what I want. A big thanks for it. I also donated some time ago.

I have some VeraCrypt volumes that I can't copy with "Sync", because the file size and the file date of these volumes does never change. I created manual tasks for them, but it would be great if I could manage to copy these volumes with thousands of other files on-the-fly for backup-reasons. I tried an string with semicolon for these volumes with the "Include" option, but it didn't work as expected.

**Comment by shirouzu** [comment]
I don't use VeraCrypt so I can't say for sure, but if you unmount the volume before copying, won't the timestamps be updated?

**Comment by a-raccoon** [comment]
It is a behavior of VeraCrypt, TrueCrypt, etc to falsify the volume container file's timestamp to hide activity.  "Say, is this an encrypted file? It says you modified it only 2 hours ago. Please open it for us."

**Comment by shirouzu** [comment]
I see.
In that case, it would be better to use "Copy(Overwrite)" instead of "Sync".

**Comment by jk-85** [comment]
Yes, I used Copy(Overwrite) in separated tasks now. For this single usecase of VeraCrypt an additional field would be nice like "copy/overwrite always" or so. Only an idea, but this case seems rare.
