### ISSUE TITLE
フォルダのファイル数が多すぎるとエラーになる

### ISSUE THREAD

**Issue by nokemono** [FastCopyLab/FastCopy#59]
**エラー内容**
フォルダのファイル数が多すぎるとエラーになる

FindNextFile(ファイルまたはディレクトリが壊れているため、読み取ることができません。1392) 

他のコピーソフトも落ちるなどして駄目でしたが、エクスプローラでは普通に表示できていて壊れた形跡は見当たりません。
robocopyでコピーすると「壊れています」という表示の後、再試行してコピーが始まります。（読み込みに時間がかかりすぎている？）

**再現方法**
フォルダに1000万以上のファイルがあると表示。

**コマンドライン・オプションや各種設定**
なし

**バージョン・環境**
FastCopy ver（原則として最新版のみ） :　4.1.3
OS ver:  win 10 21H3

**スクリーンショット**
![image](https://user-images.githubusercontent.com/1759911/160259436-55ce33e4-e1f7-4a62-a076-332453d70fa8.png)

**Comment by shirouzu** [comment]
このエラー(1392)は OSから届いているエラーです。
つまりファイルシステムの一部が壊れています。
（Explorerでエラーが出ないのは、全てのファイルを表示していない等？判りませんが）

chkdsk /f で修復できるかもしれません。
（それでダメな場合 chkdsk /r の必要があるかも）
