### ISSUE TITLE
Command-line option to specify /bufsize as a percentage

### ISSUE THREAD

**Issue by tjhiggin** [FastCopyLab/FastCopy#6]
FastCopy an awesome utility.  It's a thing of beauty to write a bat file and see FastCopy utilize over 99% of network bandwidth when copying a large data set to a network drive.  It's 5 times faster than xcopy!

Please consider adding a command-line option to specify the /bufsize as a percentage rather than an absolute value, like how you do it for /speed; i.e., /bufsizepct=9 will use 90% of the machine's RAM for the buffer.  This will allow me to use the same bat file on different machines without having to modify the /bufsize for each machine.  Thank you.

**Comment by FastCopyLab** [comment]
Thank you.
There is no point in having a buffer size that is too large.
I think the limit is 512MB～1024MB.

Buffers absorb fluctuations and delays.
It can reduce the number of seeks for the same partition.

However, the effect of increasing the size of the buffer will gradually fade away.
Therefore, increasing the buffer in proportion to the installed memory is not very beneficial.
