### ISSUE TITLE
Option: Make FastCopy replace Windows Explorer file copy/move operations

### ISSUE THREAD

**Issue by Daver4** [FastCopyLab/FastCopy#62]
Like other third party file copiers, please have an option for FastCopy to **replace** the file copy or move operations within Windows Explorer: when the user performs **cut**/**copy** and **paste** in Windows, invoke FastCopy.

(Apologies for posting this elsewhere on your GitHub - I could not find the "Feature request" page until now).

**Comment by shirouzu** [comment]
This has been a common request for a long time :-)
I will consider it.

**Comment by ibay770** [comment]
When you do, it will be my default copier. I'm using extremecopy because it has this feature but yours is much better.
