### ISSUE TITLE
DestDirの末尾の￥を付けなくする設定

### ISSUE THREAD

**Issue by karimero2203** [FastCopyLab/FastCopy#63]
**質問**
いやぁ～やぁっっと掲示板に入れたわ。送信testも兼ねてます。

DestDirの末尾の￥を付けなくする設定はありますか？

**Comment by shirouzu** [comment]
すみませんが、ありません。

**Comment by karimero2203** [comment]
・本ツールの作動中エクスプローラーで送元/送先を確認することを繰り返していたら動作がおかしくなり
また、USBで接続していたデバイスの通信(接続)が切れてしまいました。
→ツール動作中のエクスプローラー使用は禁忌ですか？

・メモリリソースが少ない状態で本ツールを使うと、若しくは本ツール使用中にメモリリソースが少なくなった場合、動作に異常をきたしますか？システムからは知らされてない状態でです。本ツールからのエラー予告
等は出ますか？メモリクリーニングツールは有効ですか？

※10時間以上を要したファイル整理の際に生じた事態です。

よろしくお願いします。
