### ISSUE TITLE
Lost .dlls for shell extension in portable version

### ISSUE THREAD

**Issue by dirtyballoonot** [FastCopyLab/FastCopy#65]
**Question**
Fastex64.dll / fastex1.dll can't be loaded, so, it can't install shell extension
**Remarks**
This is the 2nd time this has happened; The previous time luckily, I had the portable app folder backed up and copied them over; I am not sure if they were pulled from the portable version or what, but, even if I extract the installer the files are not present, or they are already compiled.

![image](https://user-images.githubusercontent.com/103008191/161653807-b3eef1c8-158e-44b1-bb06-ef5287dd1f98.png)

**Comment by FastCopyLab** [comment]
What is "the portable version"?
Anyway, I recommend to use the normal installer and to do normal installation, if you want to use shell extension.

**Comment by dirtyballoonot** [comment]
Portable version. As in portableapps.com. i have used it for several years
with no issues until recently. I prefer portable apps to keep my system as
close to 'stock'as possible. I suppose I can install it on a VM and copy
them over.

**Comment by FastCopyLab** [comment]
Sorry, I don't know about "the portable version".
If you have problems with the portable version, please contact the portable version vendor.
