### ISSUE TITLE
Delay after copying each file

### ISSUE THREAD

**Issue by mikeyww** [FastCopyLab/FastCopy#66]
I was copying 97,276 files from a QNAP NAS to an OpenMediaVault NAS. I experienced repeated computer crashes, causing a BSOD with the computer then rebooting at various times during the copying. I tried the copying 5-10 times; all failed. I used four different copying methods: Bvckup 2 (v81.22, tried various options for processing, shadow copying, and delta copying), Syncovery (v9.47g), FastCopy (v4.14, tested at a speed control of 70%), and Windows File Explorer (Win 10 Pro 64-bit v20H2.19042.1586, Intel Core 2 Quad Q8400 @ 2.66GHz, 8GB Dual-Channel DDR3 RAM @ 534MHz, ASUSTek P5QC Motherboard). Each crashed the computer. I finally wrote my own separate copying routine in AutoHotkey (v1.1.33.10). It, too, crashed the computer. In my AutoHotkey script, I then added a 50 ms sleep after every file copy. The copying then completed successfully. It seems that the commercial copying programs that I tested do not have a feature like this, to wait or delay after each file is copied. As a result, none of these programs succeeded in copying all of my files, but my own AutoHotkey script did succeed.

**Comment by shirouzu** [comment]
Oh... I recommend to replace your PC with a new machine that won't crash :-)

**Comment by mikeyww** [comment]
A wonderful idea. Thank you for providing the solution.

**Comment by a-raccoon** [comment]
Try changing the slider from Full Speed to 70%.

**Comment by mikeyww** [comment]
Thanks. It was already at 70%.

**Comment by a-raccoon** [comment]
Try the Elevate menu option on the top-right, so that FastCopy is running As Administrator.
