### ISSUE TITLE
How to speed up delete file?

### ISSUE THREAD

**Issue by qwas368** [FastCopyLab/FastCopy#67]
**Question**
I have a schedule job to delete a lot of old log files (700,000+ per day) in many folders. My fastcopy setting is default and only one filter (below). But performance is not good. How to speed up delete file by any setting? 

**Remarks**
![image](https://user-images.githubusercontent.com/26789196/162111340-d0bac317-2a7c-44d5-bf66-1bf8be9e4cf5.png)
![image](https://user-images.githubusercontent.com/26789196/162128096-5a701c54-d748-4019-ae28-dcc71f5afd9f.png)
![image](https://user-images.githubusercontent.com/26789196/162128188-8da22707-5fe5-4e7c-818d-8f25178933d0.png)

**Comment by shirouzu** [comment]
Does the speed change when you use other tools?

**Comment by qwas368** [comment]
> Does the speed change when you use other tools?

I benchmark windows cmd 'del /f/s/q' and del command is better than fastcopy.

Process Explorer data
![RDCMan_IsQos8DO46](https://user-images.githubusercontent.com/26789196/163120763-51a24ca5-f3e9-4bf1-ad91-9afdc695e142.png)
![RDCMan_yFIAXPZ3OZ](https://user-images.githubusercontent.com/26789196/163120767-3f3e1bf0-63b8-4d4c-a2d4-6adfec400251.png)

**Comment by shirouzu** [comment]
Did you use Low I/O prioirty?
![image](https://user-images.githubusercontent.com/1759911/163122900-079b6335-528b-42ec-b5f8-f31145bf75ac.png)

**Comment by qwas368** [comment]
I don't change any Fastcopy or windows system setting . It's seems like fcp.exe behavior, right ?
![image](https://user-images.githubusercontent.com/26789196/163155901-5ae95b3f-32c5-4cf8-951c-6703661bec95.png)

**Comment by shirouzu** [comment]
Hum...fcp settings depends on fastcopy.ini
This checkbox is off?
![image](https://user-images.githubusercontent.com/1759911/163173499-fc18e3da-4f91-495c-b51c-68ceec2375e6.png)

**Comment by qwas368** [comment]
My FastCopy.exe and fcp.exe is in same folder :(
![image](https://user-images.githubusercontent.com/26789196/163290750-e77c63aa-3535-4fa8-a8e1-6bb70dd95754.png)

**Comment by shirouzu** [comment]
Hmmm, I am not sure.
Anyway, in my environment, fcp /cmd=delete is faster than the del command.
But in your environment, it seems to be better to use the del command.

**Comment by shirouzu** [comment]
By the way, the I/O priority of fcp.exe's parent process (cmd.exe?) is low?
It is possible that the priority is inherited.

**Comment by qwas368** [comment]
> By the way, the I/O priority of fcp.exe's parent process (cmd.exe?) is low? It is possible that the priority is inherited.

Windows Task Scheduler use Low Priority to launches process, it will overwirte fastcopy setting. [Stackoverflow link](https://stackoverflow.com/questions/2427142/is-there-any-way-for-a-win2k8-scheduled-task-to-have-normal-priority-io)
Thanks for your reply soon, @shirouzu san.
Issue close :)
