### ISSUE TITLE
variable filter lenght to get a too long string error

### ISSUE THREAD

**Issue by Okeanos86** [FastCopyLab/FastCopy#68]
**Describe the bug**
The a lenght limit for the exclusion filter is not fixed, but is variable.
In my short trial and error I've encountered different beaviour before I get the "Bad or Too long windcard string"
Test1: exclusion list of 34 items for about 1900 total characters.
Test2: exclusion list of 196 items for about 5000 characters.
But I don't know how to reproduce this beaviour for testing, I attacched used lists.

**To Reproduce**
see exclude lists attacched.
[test-list-1.txt](https://github.com/FastCopyLab/FastCopy/files/8474099/test-list-1.txt)
[test-list-2.txt](https://github.com/FastCopyLab/FastCopy/files/8474100/test-list-2.txt)

**Command line options and various settings**
same beaviour from GUI or CLI.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.1.4
 - OS ver: Windows 10 21h2

**Comment by Okeanos86** [comment]
If you delete last item in both lists fastcopy works as expected.

**Comment by shirouzu** [comment]
This is a specification.
There is a limit of approximately 2000 characters.
However, for internal reasons, absolute paths may allow up to a few more characters.
