### ISSUE TITLE
Temporary File Names

### ISSUE THREAD

**Issue by BigRedBrent** [FastCopyLab/FastCopy#69]
**Describe the solution you'd like**

Please add an option to enable unique temporary file names when copying files. When a file is being copied, it should be named something like ".fc87847.tmp". And only when it finishes copying and verifying should it be renamed to the desired file name, replacing any files that already exist with the same file name.

This is useful if you are using Sync (Size/Date) with Verify enabled. If the process is interrupted when reading the data to verify it, currently starting the process again will skip verifying that file.

I personally believe that using temporary files while copying and verifying is the best practice for any file copying software. Even though I don't know why anyone wouldn't want this feature enabled, it should be able to be disabled for those who do not want it.

**Additional context**

For instance:
If I were to Copy (Overwrite) a file with Verify enabled from "C:\folder1\test.txt" to "D:\folder2\\".
It would begin by copying "C:\folder1\test.txt" to "D:\folder2\\.fc73829.tmp".
When finished copying it would then read "D:\folder2\\.fc73829.tmp" to verify it.
Once "D:\folder2\\.fc73829.tmp" is verified, it would move "D:\folder2\\.fc73829.tmp" to "D:\folder2\test.txt".
If "D:\folder2\test.txt" already exists, it would be replaced by "D:\folder2\\.fc73829.tmp".

Please make the temporary file names easy to search for. What I have suggested could easily be found with a search for ".fc*.tmp".

**Comment by shirouzu** [comment]
I will consider it.
