### ISSUE TITLE
wrong speed estimate since v4.1.4?

### ISSUE THREAD

**Issue by hp48gx** [FastCopyLab/FastCopy#70]
Hello,

We use self-updates, so we can't say precisely when this problem started, but it's definitely a recent issue.
Basically, sometimes time prediction seems completely off (i.e. much larger).

It happened several times, but we can mention two relevant cases: we have a folder containing 700GB of _homogeneous_ files (i.e. most of them have similar size, say between 10MB and 20MB each), and we keep backup copies on different machines.

1. When copying the folder from our NAS to a very powerful windows machine, the estimate was 20 hours, but it actually took about 4 (we don't know precisely). The machines are connected via gigabit ethernet (iperf3 reports that it's almost full gigabit bandwidth), and both have very fast drives.
2. We have a replica of _the same folder_ on another machine, which has 3 identical drives: two in RADI1 and the other as a single disk. when copying the folder from the RAID1 device to the other disk, the prediction was -again- about 17 hours.
After an hour, it was still showing 16 hours left, so we just let it run, but it actually completed in about 6.
For this transfer we do have this log entry:

```
=================================================
FastCopy(ver4.1.4 (Admin)) start at 2022/04/20 12:18:34
<Source>  F:\Library\
<DestDir> H:\Snapshots\
<Command> Sync (Size/Date) (with Verify)
<JobName> Sync_F_H
<FileLog> C:\FastCopy\Log\20220420-121834-0.log
-------------------------------------------------

TotalRead  = 672,385 MiB
TotalWrite = 672,385 MiB
TotalFiles = 44,871 (6,691)
TotalTime  = 05:53:26
TransRate  = 33.3 MB/s
FileRate   = 2.12 files/s
VerifyRead = 672,385 MiB
VerifyFiles= 44,871

Result : (ErrFiles : 0 / ErrDirs : 0) at 2022/04/20 18:12:01
```

The low speed (33MB/s) is probably ok, as this machine is not super powerful, but as the transfer rate should be constant, it's a bit strange that the prediction was so wrong.

Maybe we accidentally enabled some option that causes this?

thanks

**Comment by shirouzu** [comment]
The Estimation algorithm is not changed since v3.x.
The Estimation are only a rough guide.
In verifying, if the speeds of Source and Dest are very different, the estimation tends to deviate significantly.
