### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by GregSlim** [FastCopyLab/FastCopy#71]
**Describe the solution you'd like**
Hello, i would like CLI to permit doing "Listing", "Shift+Listing" and "Ctrl+Listing".

**Additional context**
It would permit to see or use the list before executing actualy a job. Thank you very much for Fastcopy !

**Comment by shirouzu** [comment]
Yes, I will consider it.

**Comment by GregSlim** [comment]
Thank you very much ^^

**Comment by GregSlim** [comment]
Hello @shirouzu ,

Did you have time to look at this CLI request for enhancement ?
