### ISSUE TITLE
Windows 10 integration not working well.

### ISSUE THREAD

**Issue by RAGEdemon** [FastCopyLab/FastCopy#72]
**Describe the bug**
Right click COPY - Right click in new folder - no PASTE option except windows default.

**To Reproduce**

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (latest ver) :
 - OS ver: Windows 10 latest

**Screenshots**

**Comment by shirouzu** [comment]
I can't reproduce it.
Can you show movie or step by step capture?

**Comment by RAGEdemon** [comment]
Please see my video as proof:
https://www.loom.com/share/c79b0425b89d495e8dfec2133c7a5b38 [fixed]

**Comment by shirouzu** [comment]
The "Copy(FastCopy)" of menuitem, is just to open fastcopy with the selected path.
(it is not used clipboard)

If you want to use the FastCopy paste menu with right click, it is required to use Ctl+C (Windows default copy) beforehand.
