### ISSUE TITLE
Proper Windows default copy/paste replacement please.

### ISSUE THREAD

**Issue by RAGEdemon** [FastCopyLab/FastCopy#73]
**Describe the solution you'd like**
Proper Windows default copy/paste replacement please. FastCopy is the best software however TeraCopy etc are more popular because they have better integration. 

**Additional context**

**Comment by shirouzu** [comment]
I will consider it.

**Comment by GregSlim** [comment]
Fastcopy being portable and us being able to choose if it integrates more is part of why i love Fastcopy so much.
Better integration, like with proper Windows default copy/paste replacement, would be great but please i hope if you can manage that we will be able to choose the usage we prefer like it's the case today (just running, right drap and drop, right clic, the marvelous CLI of course, ...)
