### ISSUE TITLE
Right clicking copy multiple times opens multiple FastCopy windows. [Updated with video]

### ISSUE THREAD

**Issue by RAGEdemon** [FastCopyLab/FastCopy#74]
**Describe the bug**
Right clicking copy multiple times opens multiple FastCopy windows.

**To Reproduce**

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (latest ver) :
 - OS ver: Windows 10 latest

**Screenshots**

**Comment by shirouzu** [comment]
?? Sorry, I don't understand what you say.
Can you show movie or step by step capture?

**Comment by RAGEdemon** [comment]
Please see my video as proof:
https://www.loom.com/share/d67d0554fd034c94a98ea13915dafd31

Expected behaviour: Only one window opens, old window automatically closes. Or better - no windows open, or if a window NEEDS to open, sent it to tray without bothering the user. Why does window open? It's useless, gets in the way, and adds extra steps to the copy process, which should be simple as possible:

Right click -COPY-
Right click in new place -PASTE-

There ought not be any windows appearing, nor the user having to click on any windows for additional options which are not required most of the time. Maybe program it so ALT+click on copy makes window appear only, but normal click makes no window appear...

Thank you.

**Comment by shirouzu** [comment]
Sorry, it is FastCopy specification.
If you don't want to open multiple window, please use drop multiple files to a FastCopy window with Ctrl-key.
