### ISSUE TITLE
Send to Tray instead of Taskbar does not work.

### ISSUE THREAD

**Issue by RAGEdemon** [FastCopyLab/FastCopy#75]
**Describe the bug**
Tickbox Send to Tray instead of Taskbar does not work. Icon only appears in tray when in this options menu and never again.

**To Reproduce**

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (latest ver) :
 - OS ver: Windows 10 Latest

**Screenshots**

**Comment by shirouzu** [comment]
The checkbox "Use taskbar instead of tasktray at minimizing" works,
   checked ... Use taskbar at minimizing.
   unchecked(default) ... Use tasktray(task notification area) at minimizing.
