### ISSUE TITLE
Immunet AntiVirus gives a false positive from FastCopy.

### ISSUE THREAD

**Issue by robkam** [FastCopyLab/FastCopy#76]
On Windows 10, [Immunet AntiVirus](https://www.immunet.com/) gives a **false** positive from FastCopy and breaks it.

**Comment by shirouzu** [comment]
Hum...and so what?

**Comment by a-raccoon** [comment]
The link he meant to give you is --> https://www.immunet.com/false_positive
so that you can report your software to them for green lighting.

Though, anyone including OP can also report it.
