### ISSUE TITLE
Copy files minus subdirectories

### ISSUE THREAD

**Issue by Meche697** [FastCopyLab/FastCopy#77]
**Question**
I want to copy my files from a folder ... actually, some sub-directories in (example) documents to my portable drive without DELETING or disturbing the directories above.
- D:\{USER}\documents\Scan --> K:\documents\Scan    where K:\documents\DOC, K:\documents\PDF, etc. are not affected.

Another software wiped out data due to this scenario (deleted K:\documents\DOC, K:\documents\PDF, etc.) ... thankfully, I had a 2nd backup that was only 1 month out.
Hope this question makes sense. I'd also recommend a YouTube Channel with videos :)

**Remarks**
I think it's similar to [https://groups.google.com/g/fastcopy-bb-eng/c/UuHCUuQLEGA](url) and was surprised at the response.

**Comment by shirouzu** [comment]
Sorry, I can't understand.
Could you tell me more detail/example?

**Comment by Meche697** [comment]
Sorry for the delay. You appear to have closed it too fast. I'm mostly in the field as of late and not on computer/personal email.
I think my request is similar to [https://groups.google.com/g/fastcopy-bb-eng/c/UuHCUuQLEGA](https://github.com/FastCopyLab/FastCopy/issues/url)

I want to copy my files from sub-directories on my laptop to higher level directories on my external drive without DELETING or disturbing the PARENT directory.
- D:\{Laptop USER}\documents\Scan --> K:\documents\Scan
- Do NOT delete K:\documents\DOC, K:\documents\PDF, etc.
Another "copy" software wiped out any that was NOT K:\documents\Scan; DELETED K:\documents\DOC, K:\documents\PDF, etc.). If you notice, transferring to portable drive "raises" the sub-directory level

My goal is to work off of my laptop and have a mirror on my external drive with multiple Jobs depending on the directory. In this case, I just need to back up the scans from the documents directory without DELETING everything else in K:\documents\. I will have another JOB where I want to backup the entirety of D:\{Laptop USER}\Pictures.

**Comment by shirouzu** [comment]
Sorry, FastCopy doesn't support scatter/gather copy.

> I think my request is similar to [https://groups.google.com/g/fastcopy-bb-eng/c/UuHCUuQLEGA](https://github.com/FastCopyLab/FastCopy/issues/url)
