### ISSUE TITLE
Strange behavior of file date and time during and after copy

### ISSUE THREAD

**Issue by noto10** [FastCopyLab/FastCopy#8]
Fastcopy v3.92

During the copy process, the destination file has the **_current_** date and time but immediately after the copy operation has finished, the date and time of the destination file changes to the **_original date and time_**.

Is this a bug?

Please have a look at the attached video clip which shows this (Please pay attention to the date and time of the file being copied during and after the copying has finished). 

https://user-images.githubusercontent.com/13828004/150407981-0449b0b6-79ef-456d-8fde-62897df93d47.mp4

**Comment by FastCopyLab** [comment]
This is normal behavior.
FastCopy sets the timestamp of the file after it has been written.

**Comment by noto10** [comment]
> This is normal behavior. FastCopy sets the timestamp of the file after it has been written.

Thank you for clarifying!
