### ISSUE TITLE
Keep AD Privileges

### ISSUE THREAD

**Issue by ledelatorre** [FastCopyLab/FastCopy#80]
Hi,

I need to move the shares between two Windows NAS on the same domain. Is there an option to copy the files and folders keeping the AD privileges each one have?

I already tried but the files on the new NAS have not AD privileges.

Thanks in advance

**Comment by shirouzu** [comment]
What is "the AD privileges"? Is it ACL?

**Comment by ledelatorre** [comment]
> 

Hi,

Active Directory Privileges. I'm working on Windows Server 2008 R2 

Thanks for reply.

**Comment by shirouzu** [comment]
I don't know about the AD priviledges.
Is it a type of ACE(access control entry of ACL)?
Can you show me the screen capture of the AD priviledges that source files have?

**Comment by ledelatorre** [comment]
Well, In Windows Servers and NAS you can create diferent folders for remote access and they are called Shares. With the Active Directory you give those shares (files and foldes) permissions to control the access to such data. 

The main function of Active Directory is to enable administrators to manage permissions and control access to network resources. In Active Directory, data is stored as objects, which include users, groups, applications, and devices, and these objects are categorized according to their name and attributes.

Active Directory Domain Services (AD DS) are a core component of Active Directory and provide the primary mechanism for authenticating users and determining which network resources they can access. AD DS also provides additional features such as Single Sign-On (SSO), security certificates, LDAP, and access rights management.

I need to move those Shares from a NAS to another but I want they keep the permissions given trough the AD and the reason I create this issue or question is to know if there is an option to do this with Fast Copy. 

Thanks!

**Comment by shirouzu** [comment]
Permissions stored in NTFS are called ACLs and are retained if "ACL" is checked.
(In many cases, this must be done with administrator privileges. Please use "Elevete" in the UAC environment)

However, shared settings are not stored in NTFS (presumably in the registry), so you cannot copy shared settings.

**Comment by ledelatorre** [comment]
Awesome! thank you very much. I'll let you know if it works.

**Comment by ledelatorre** [comment]
Just to thank you. The information you posted help me a lot.
