### ISSUE TITLE
Not understanding the command behavior

### ISSUE THREAD

**Issue by Meche697** [FastCopyLab/FastCopy#83]
Thank you for the program and previous quick responses.
I am trying to sync specific files. The issue is that the program is deleting folders in the target directory. I thought it was a "/" issue, but the combinations tried have been unsuccessful. (User ERROR). I only want to SYNC specific folders from the parent (C) directory. I'm trying to follow https://fastcopy.jp/help/fastcopy_eng.htm
EX Sync from C to E (external drive)
Source
`C:\my documents\pictures\     
C:\my documents\book\      THERE are other folders I do not want to sync_`
DestDir
`E:\Documents`
The problem is that **E:\Documents** has other subfolders that keep getting deleted
**In addition, I just noticed that my Job changed from SYNC to DIFF (Size/Date) on startup** If I click the job, it fixes the issue

**Comment by shirouzu** [comment]
Sorry, FastCopy does not have that feature.

**Comment by shirouzu** [comment]
Sorry, I don't understand what you say. (My English is poor)

Please use this template.
https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=

(Steps to reproduce the behavior is very important)
