### ISSUE TITLE
The sync does not delete folders copied earlier but excluded with /exclude= in 2nd run

### ISSUE THREAD

**Issue by salemjo** [FastCopyLab/FastCopy#84]
Thanks for this small and efficient program.
**FastCopy ver: 4.1.5 x64 /   Windows 7 Professional x64**
The /cmd=sync does not delete excluded folders\files in destination.
::::
**To Reproduce**
1st Run
fastcopy.exe /cmd=sync D:\ /to=I:\Backup\D_Drive
2nd Run with exclude filter
/cmd=sync /exclude=*\FOUND.*\;"$RECYCLE.BIN\";"System Volume Information\";pagefile.sys;hiberfil.sys D:\ /to=I:\Backup\D_Drive

The 2nd sync does not delete folders copied earlier but excluded now
::::

_Is it by design ?
Do i need to delete and recreate backup to exclude folders\files?_
Thanks in advance

**Comment by shirouzu** [comment]
> Is it by design ?

Yes.
