### ISSUE TITLE
FCの動作について・他

### ISSUE THREAD

**Issue by karimero2203** [FastCopyLab/FastCopy#86]
・本ツールの作動中エクスプローラーで送元/送先を確認することを繰り返していたら動作がおかしくなり
また、USBで接続していたデバイスの通信(接続)が切れてしまいました。
→ツール動作中のエクスプローラー使用は禁忌ですか？

・メモリリソースが少ない状態で本ツールを使うと、若しくは本ツール使用中にメモリリソースが少なくなった場合、動作に異常をきたしますか？システムからは知らされてない状態でです。本ツールからのエラー予告
等は出ますか？メモリクリーニングツールは有効ですか？

※10時間以上を要したファイル整理の際に生じた事態です。

よろしくお願いします。

**Comment by shirouzu** [comment]
>ツール動作中のエクスプローラー使用は禁忌ですか？

そんなことはないはずですが…

>使用中にメモリリソースが少なくなった場合

FastCopyでメモリが確保できなくなった場合、その旨のエラー表示が出ます。

>メモリクリーニングツールは有効ですか？

無効です。

**Comment by karimero2203** [comment]
貴社の開発環境及び世間一般の只今の極普通のPC/窓環境では想定できない事であること。から
私のPC環境が劣悪なために起こった事故だということが分かりました。
大変失礼致しました。
