### ISSUE TITLE
Command line generator

### ISSUE THREAD

**Issue by chamac-h** [FastCopyLab/FastCopy#87]
Hello,

Form time to time, my colleagues and I have to create some complex FastCopy commands. Most of the time we use the graphical interface, because it is not always easy to remember all the command line switches.
So after we have set all parameters within the graphical interface, could it be possible to have a button which would generate a full command line that we could use in our scripts ?

Thanks in advance.

Thanks for this wonderful software.

**Comment by shirouzu** [comment]
I think it is better to use JobMng
https://fastcopy.jp/help/fastcopy_eng.htm#job
