### ISSUE TITLE
ベリファイのみを実行することは可能でしょうか

### ISSUE THREAD

**Issue by RYOSAKA1986** [FastCopyLab/FastCopy#88]
**質問**
コピーは実行せず、ベリファイのみを実行することは可能でしょうか。
もしくは、差分コピーでSkipしたファイルに対してもベリファイを行うことは可能でしょうか。

**備考**
コピーに時間制約がある環境でFastCopyを使用させていただくことを考えております。

コピー容量対象はUSBHDDに保存されている1TB程度のデータ量で、
検証環境ではベリファイ含め13時間程度かかる見込みなのですが、コピーを許されている時間が11時間程度しかありません。
(業務中は上記USBHDDをコピー用の端末とは別の端末で使用し、業務終了後にコピー用端末にUSBHDDを接続し夜通しでコピーを実施、翌日業務中はまた上記USBHDDを別の端末で使用するため、取り外しが必要となります。)

業務時間開始前にコピーを中断し、その後の業務完了後に差分コピーを実行することとなりますが、
中断前のコピーが完了しているデータに対して、ベリファイをかけられますでしょうかということが質問の意図です。

**Comment by shirouzu** [comment]
下記のような機能はあります。
（スキップ対象＝コピー済みファイル、と思って貰ってよいです）

「CTLキーを押しながらリストアップを押す（ボタン名「リストアップ」→「リストアップ+V」）と、スキップ対象（ただしフィルタ除外は除く）のファイルペアについて、読み込み＆ハッシュ値比較を行います」
https://fastcopy.jp/help/fastcopy.htm#buttons
