### ISSUE TITLE
Fastcopy not working anymore when invoked from Windows Explorer

### ISSUE THREAD

**Issue by Kal999** [FastCopyLab/FastCopy#89]
When selecting a source file or source folder with right-click (Windows-copy or FastCopy-copy) and then right-click again in different location (Windows-paste or FastCopy-paste) FastCopy does literally nothing (even when FastCopy is run as Admin).

When selecting source file or source folder and destination folder within FastCopy everything works as expected.

**Version/Environment**
 - FastCopy ver (principle, latest ver) : 4.1.5
 - OS ver: Windows 10 64 bit 21H1 build 19043.1706

**Comment by shirouzu** [comment]
Can you show us the movie(or some screenshots) of these action?

**Comment by Kal999** [comment]
Yes of course. Thank you
[Screen Recording (26-05-2022 17-59-11).zip](https://github.com/FastCopyLab/FastCopy/files/8780344/Screen.Recording.26-05-2022.17-59-11.zip)
.

**Comment by shirouzu** [comment]
Thank you.
Indeed, it is strange.
But I cannot reproduce it in my environment.
Do you have any special settings?

**Comment by Kal999** [comment]
The only thing I did was running Chris Titus's Windows Utility (https://christitus.com/windows-tool/) and that could be the cause. 
I ran the undo in that utility with no effect to FastCopy strange behaviour. I also restored a Windows restore point prior to the utility but FastCopy still not working. Do you know there are some Windows services and/or registry settings that FastCopy must use?

**Comment by shirouzu** [comment]
> Do you know there are some Windows services and/or registry settings that FastCopy must use?

I think there is nothing like that.

**Comment by Kal999** [comment]
Ok, thank you. If I sort the problem I'll post the solution here.
