### ISSUE TITLE
Copy/Move (keep both)

### ISSUE THREAD

**Issue by PapaKarl0** [FastCopyLab/FastCopy#9]
Not sure why this option is not present... Anyway, would be nice to have it. 
If there's a file with the same name in destdir then rename the new file which is being copied. Just like Windows does it: file (1).pdf, file (2).pdf, file (3).pdf, file (4).pdf etc etc.

**Comment by shirouzu** [comment]
If source and destination are same dir, FastCopy will duplicate source files/dirs.
Example)  fastcopy C:\temp\file.txt /to=C:\temp\
   --> C:\temp\file(1). txt will be created.

**Comment by PapaKarl0** [comment]
Sorry, I'm a bit confused, but which /cmd= option do I use for that?

**Comment by shirouzu** [comment]
Sorry, it doesn't exist.

**Comment by PapaKarl0** [comment]
> Sorry, it doesn't exist.

Well, then there's no way to achieve this:

> If source and destination are same dir, FastCopy will duplicate source files/dirs. Example) fastcopy C:\temp\file.txt /to=C:\temp --> C:\temp\file(1). txt will be created.

**Comment by shirouzu** [comment]
I misunderstood.
You can use /cmd=diff

> If source and destination are same dir, FastCopy will duplicate source files/dirs. Example) fastcopy C:\temp\file.txt /to=C:\temp --> C:\temp\file(1). txt will be created.

**Comment by PapaKarl0** [comment]
if New folder2 already contains test1.txt (of a different size) the following command 
 
fcp.exe /cmd=diff "C:\New folder\test1.txt" /to="C:\New folder\New folder2\" overwrites test1.txt in New folder2

**Comment by shirouzu** [comment]
There is a condition for the duplication operation.

>If source and destination are same dir, FastCopy will duplicate source files/dirs.

**Comment by PapaKarl0** [comment]
There's no way to have 2 files with the same name in the same folder. Windows doesn't allow that :). So the condition is impossible.

**Comment by shirouzu** [comment]
??
At the condition, FastCopy will duplicate/create file(1).txt or etc, OK?

**Comment by PapaKarl0** [comment]
C:\folder1\file.txt
C:\folder2\file.txt
C:\folder3\file.txt

Copy to:

C:\folder4\ (which already contains file.txt)

good result:

C:\folder4\file.txt
C:\folder4\file(2).txt
C:\folder4\file(3).txt
C:\folder4\file(4).txt

**Comment by shirouzu** [comment]
I know what you want, but FastCopy only duplicates copying C:\folder1\file.txt to C:\folder1\

**Comment by PapaKarl0** [comment]
I'm going to donate a $100 if you give me what I want :))
Cross my heart and hope to die. I love FastCopy too much to use anything else...

**Comment by shirouzu** [comment]
Sorry, but no thanks.
I want to decide FastCopy development plan by myself.
