### ISSUE TITLE
Buffersize and buffers sometimes can not be set

### ISSUE THREAD

**Issue by PJTraveler** [FastCopyLab/FastCopy#91]
**Describe the bug**
In IO settings, initial state is 
Bufsize = 96
IO unit = 1
Overlap IO = 1
-----------
**Scenario 1**
Set Overlap IO to 96,  with "apply"
a popup prevents it from being set

**Scenario 2**
Change the buffersize to 1 and "apply"
Same popup occurs that prevents it from being set

**Scenario 3**
Change the IO unit to 96 and "apply"
same popup occurs and prevents the change

**To Reproduce**

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
ver 4.1.5
Windows 11

**Screenshots**
![Fastcopy_2022-05-27_10-57-11](https://user-images.githubusercontent.com/63062762/170765398-129a267a-9919-4868-bd4d-09e48851a0ee.png)

**Comment by PJTraveler** [comment]
![Fastcopy_2022-05-27_10-58-46](https://user-images.githubusercontent.com/63062762/170765699-be88ff70-11c9-404b-9b0e-23191c1ee5a0.png)

**Comment by shirouzu** [comment]
??
This is the specification.
And I recommend to use Overlap I/O num <= 8.
(If 9 or more is set, copy speed will be reduced with HDD)

**Comment by PJTraveler** [comment]
The 'disk' is a raid array with 2 GB cache, and queued operations 32 deep.  FC uses less than 10% of the network bandwidth.    I use Free File Sync and it can drive the disks much harder than FC.
 
There is still the problem that the settings can not be changed
-----Original Message-----

**Comment by shirouzu** [comment]
Hum...
If it is so, you need to specify large buffer size that "more than twice value of Max I/O size"
(max I/O size = IO unit size * overlap-num)

**Comment by PJTraveler** [comment]
No, I do not need it, I'm trying to fix it, but can not change it.  I can't make any changes to the situation.
-----Original Message-----

**Comment by shirouzu** [comment]
??
If you specify buffer size to 256, this attention will be gone.

**Comment by PJTraveler** [comment]
The issue is that I can’t any of the settings.  I can’t straighten anything out.

**Comment by shirouzu** [comment]
I can't reproduce.

**Comment by PJTraveler** [comment]
I have a 4MB video of the problem, but unable to upload it to this site.
