### ISSUE TITLE
Move files without rewriting data

### ISSUE THREAD

**Issue by JaegerFox** [FastCopyLab/FastCopy#92]
When moving the files from one directory to another in the same partition using the native Windows function, it does not rewrite the data, but the downside of this process is that it changes the timestamp of the files, in addition to speeding up the movement of files without the need for rewrite all the information..

only use this function if it detects that it is the same partition

**Comment by a-raccoon** [comment]
Read the earlier requests for this in the Closed Issues tab.  The program is called FastCopy, not FastRename.

If you need a renaming tool, I have suggested others elsewhere.

"Moving" a file from one path to another on the same volume is a rename.

**Comment by JaegerFox** [comment]
and tell me what "renamers" do that job? fastcopy also has an option for secure deletion, it is also valid to ask for an option to "move" even faster without having to do all that process... fastcopy is mainly to take advantage of copying files from one storage unit to another, or in the case of old HDDs move from a partition that is inner of the disk with a slower partition or sector of the disk (outer)

and one of the most useful advantages is that it maintains the structure of the folders and the metadata, no common renamer does that job so friendly

**Comment by shirouzu** [comment]
I will consider it.
