### ISSUE TITLE
Unable to change Buffersize settings

### ISSUE THREAD

**Issue by PJTraveler** [FastCopyLab/FastCopy#93]
https://user-images.githubusercontent.com/63062762/173890474-c03b2b88-c0f5-4100-b43b-e83cd5957b4a.mp4
I have 2 other videos of the problem, but was unable to upload  either of them.

Unable to change IO settings

**Comment by shirouzu** [comment]
??
It is the specification.
If you want to set Overlap=63(and I/O unit is1), Buffer size is required more than 128 or more.
