### ISSUE TITLE
Network copy support

### ISSUE THREAD

**Issue by shu7734** [FastCopyLab/FastCopy#95]
**Describe the solution you'd like**
I need backup all users files between 2 computer

I tried SMB share all users file,And fastcopy sync files,
but,can't async NTFS ACL

I hope Fastcopy support copy file between 2 computer

**Additional context**

**Comment by shirouzu** [comment]
Please use this format, because I can't reproduce it.
https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=
