### ISSUE TITLE
change 5 string table language id to english ?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [FastCopyLab/FastCopy#96]
![Snipaste_2022-06-28_13-46-50](https://user-images.githubusercontent.com/5471433/176102651-46d0c888-8739-4b17-8bc0-a850894d4eb1.png)

`LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US`

**Comment by shirouzu** [comment]
Why do you want to modify it?

**Comment by kokutoukiritsugu** [comment]
translate fastcopy to other language.
It's a translation automation problem.
not bug or anything.

In the translate software,
if select extract japanese string,
all above 1-20 japanese string and english string extract together...

if select extract english string only,
then i need translate this 70-76 manually...

if 70-76 is correct english language id, i don't need manually do that...

**Comment by shirouzu** [comment]
I will consider it.
