### ISSUE TITLE
FR/Enhancement suggestion: Simultaneous transfers to/from SSD

### ISSUE THREAD

**Issue by vertigo220** [FastCopyLab/FastCopy#97]
**Describe the solution you'd like**
Currently, FastCopy uses a queue so a file transfer to/from a drive with a transfer already active waits until the drive is no longer busy, unless the user tell sit to "Start at once," and it has the ability to identify different drive letters as separate partitions on the same drive so FC will treat them as the same drive and not start a transfer involving one if one of the others is busy. What I suggest is adding another layer to this, where drives can be identified as SSD or HDD, either automatically or by the user via settings, and if an SSD is involved in a transfer with a HDD, and another transfer involving that SSD is initiated, it will start automatically, since the SSD will only be operating at partial capacity with the HDD transfer due to the HDD being a bottleneck, and it can easily do two or more transfers at once without slowing down.

**Additional context**
For example:

C - SSD
D - HDD
E - SSD
F - HDD

Start transfer C->D, starts automatically
Start transfer E->D, waits because D is a HDD and can only handle one at a time
Start transfer C->F, starts automatically because C can handle several hundred MB/s yet is only currently using ~100-250, depending on D's speed, and seeking is not an issue (so won't be slowed by doing reads/writes for multiple transfers like a HDD would be)
Start transfer C->E, starts automatically because C likely still has available unused performance despite running two transfers, since both are to HDDs, but with a lower priority so previous transfers are able to run at full speed allowed by D and F

Alternately:
C->D, starts automatically
E->D, waits
C->E, starts automatically
E->F, starts automatically, even though E might be at its limit due to C->E (SSD->SSD), but it may not be, and as an SSD it can handle multiple transfers without much slowdown, so better to cause C->E and E->F to each run slower running simultaneously than if they ran separately but to take less time overall than they would by running separately, as separately there may be some unused/wasted speed.

There should of course be limitations, as you wouldn't likely want 3+ transfers at the same time, unless the SSD is significantly faster than the other drives, including other SSDs. This could be handled by FC performing speed tests on each drive and keeping that data for determining how much overhead they have when being used for one or more transfers currently (e.g. if it's tested at 1,000MB/s and it's running two transfers, one at 150 and one at 500, then it has ~350MB/s performance available still, and so should probably allow another transfer to start automatically). That would probably be the best method, but alternately and simpler, the user could just set the maximum allowable parallel transfers for each drive, ideally with a separate setting for SSDs vs HDDs (e.g. 3 simultaneous transfers with HDDs, 2 with SSDs).

**Comment by shirouzu** [comment]
Hum...I will consider it.

**Comment by shirouzu** [comment]
FastCopy v5.0, that behavior is now possible, although it requires an optional setting.
![image](https://github.com/FastCopyLab/FastCopy/assets/1759911/fa4c0fd0-ffd6-4457-9d55-ddff9119dc8e)
