### ISSUE TITLE
please consider to add a new feature

### ISSUE THREAD

**Issue by namwah** [FastCopyLab/FastCopy#99]
**Describe the solution you'd like**

**Additional context**
![image](https://user-images.githubusercontent.com/108704011/177229312-a839f60e-cd80-4832-b656-d2f541068dd9.png)

please consider to add a new feature:
use a modified name, if destdir is NOT the same as src's parent:
if DestDir is NOT the same as src's parent directory, for the same file, create a new name like "source(1)" and continuous

thanks for your help.

This software is GREAT !

**Comment by shirouzu** [comment]
I will consider it.
